### ISSUE TITLE
Proposed change: improper argument ordering breaks non-glibc code

### ISSUE THREAD

**Issue by roryk** [amoffat/sh#128]
Hi Andrew,

I think the getopt function in glibc is more agnostic regarding where options are than in libc. For example on OSX:

```
ls dir -l
```

Will not work, it treats "-l" as a directory.

So if you do something like 

```
sh.ls(dir, l=True)
```

it gets expanded to the above and it doesn't work the way you expect.

What do you think about sh and sh.bake constructing the calls such that positional arguments are always placed at the end?

**Comment by jorpilo** [comment]
I am having a similar issue than here...

I have a command with multiple subcommands, each subcommand might accept different parameters.

If I try to bake the arguments the final command will bake each argument as you have added them and the program fails as it expects all arguments at the end
```
tsh=Command("tsh")
tsh=tsh.bake(proxy=myproxy)
print(tsh.login(user=myuser, myserver))
```
this produces `tsh --proxy=myproxy login --user=myuser myserver` which fails as it expect to be `tsh login --proxy=myproxy --user=myuser myserver`

Is there any way to bake arguments always at the end of the command but prior any arguments passed
