### ISSUE TITLE
Setting UID (e.g. dropping root privileges)

### ISSUE THREAD

**Issue by tomekwojcik** [amoffat/sh#133]
Hello,
I'm working on adding `_uid` special keyword argument and I thought I'd ask for suggestions before actually opening a pull request. The code in question is available [here](https://github.com/tomekwojcik/sh/commit/5011bdeaf1042bed6b7e10b6eb33d3a90669fd1e).

Now, as you can see this is clearly a dirty hack at the moment. What I'd like to know is how to properly handle the situation when the parent process isn't owned by `root` (currently raising `RuntimeError`). Also, I have to explicitly turn off TTYs on `stdin` and `stdout` (which isn't that much of a problem, I guess).

Would you even consider adding this functionality to the library?

Best regards.

EDIT:
An example of the feature in action:
```bash
twojcik-mb:sh bilbo$ sudo python -c "import sh; print sh.whoami().stdout.strip(); print sh.whoami(_uid=501).stdout.strip()"
root
bilbo
```

**Comment by amoffat** [comment]
Merged what was in your branch into the 1.2 release and it will go out then.  Thanks for your contribution :+1:
