### ISSUE TITLE
Repeating keyword arguments

### ISSUE THREAD

**Issue by amackera** [amoffat/sh#159]
Hello all,

I'm writing a script that interfaces with `jmeter`, and I'm using `sh` to interface with `jmeter`. 

I'm running into a problem now, where I'd like to pass `jmeter` some user defied properties. The way that's done in `jmeter` resembles the following:

``` sh
jmeter -Jgroup1.threads=7 -Jhostname1=www.realhost.edu
```

`sh` doesn't like it when do the following

``` python
sh.jmeter(n=True, J="group1.threads=7", J="hostname1=www.realhost.edu")
```

Python throws an exception: `SyntaxError: keyword argument repeated`.

I could compose a string that has all my arguments, but I really like the keyword argument interface that `sh` exposes. Is there support for a use case like mine?

**Comment by carlwgeorge** [comment]
@amackera I just found this issue trying to solve a similar problem (passing multiple `--define` flags to `rpmbuild`).  It looks like you can (ab)use the bake function to accomplish this.

```
sh.jmeter.bake(J='group1.threads=7').bake(J='hostname1=www.realhost.edu')()
```

Or broken out a bit for readability.

```
cmd = sh.jmeter
cmd = cmd.bake(J='group1.threads=7')
cmd = cmd.bake(J='hostname1=www.realhost.edu')
cmd()
```

**Comment by kbd** [comment]
I naively converted some shell to `sh` and had the following:

```python
poetry.init(
  no_interaction = True,
  name = sys.argv[1],
  author = sh.git.config('--get', '--global', 'user.name').strip(),
  dev_dependency = 'black',
  dev_dependency = 'ipython',
  dev_dependency = 'mypy',
  dev_dependency = 'pylint',
  dev_dependency = 'pytest',
)
```

Of course, you can't have multiple keyword arguments. It's too bad, because making shell look like Python is one of `sh`'s strengths. To make any remaining use of keyword arguments, the above has to be converted to:

```python
poetry.init(
  '--dev-dependency=black',
  '--dev-dependency=ipython',
  '--dev-dependency=mypy',
  '--dev-dependency=pylint',
  '--dev-dependency=pytest',
  no_interaction = True,
  name = sys.argv[1],
  author = sh.git.config('--get', '--global', 'user.name').strip(),
)
```

It would be nice if the following worked:

```python
poetry.init(
  no_interaction = True,
  name = sys.argv[1],
  author = sh.git.config('--get', '--global', 'user.name').strip(),
  dev_dependency = ['black', 'ipython', 'mypy', 'pylint', 'pytest'],
)
```

Currently that results in the following being passed:

```
--dev-dependency=['black', 'ipython', 'mypy', 'pylint', 'pytest']
```

Since that's never what you'd want (or you could stringify that if you did), it'd be nice if passing a list or tuple as a keyword value expanded into:

```shell
--dev-dependency=black
--dev-dependency=ipython
--dev-dependency=mypy
--dev-dependency=pylint
--dev-dependency=pytest
```
