### ISSUE TITLE
pypi page renders incorrectly

### ISSUE THREAD

**Issue by joe42** [amoffat/sh#216]
Hi,

The pypi page does not render the build/coverage status images correctly:
https://pypi.python.org/pypi/sh

Regards,
joe

**Comment by TomRoche** [comment]
Note the text [currently visible @ PyPI](https://pypi.python.org/pypi/sh) still (as of 0226 UTC 7 Sep 2016)

* renders incorrectly
* is very definitely not (according to my reSTful eye :-) reStructuredText

**Comment by esc** [comment]
No it is still markdown which is why it renders so funnily.
