### ISSUE TITLE
Unable to get an interactive shell

### ISSUE THREAD

**Issue by zdexter** [amoffat/sh#218]
I would like to get a shell using `sh`. I am currently not sure whether this is a feature request, a bug report, or user error :)

```
import sys
from sh import sudo
out_kwargs = {'_out': sys.stdout, '_out_bufsize': 0, '_tty_in': True}
sudo.bash(**out_kwargs)
```

This gives a bash prompt, but I'm unable to interact with it. How can I get an interactive prompt? Thanks.

**Comment by amoffat** [comment]
can't be done, currently: https://github.com/amoffat/sh/issues/92

**Comment by amoffat** [comment]
`_fg` option exists in the 1.2 branch, which will be shipping soon
