### ISSUE TITLE
_out stops being called after some time

### ISSUE THREAD

**Issue by zdexter** [amoffat/sh#220]
I'm using `sh` to run `some_command` inside a Docker container. Everything is going well - I can see stdout from the container. But then nondeterministically, the container stdout stops appearing in the bash shell I'm running `sh` from at some during the execution of `some_command` (`some_command` as a whole takes probably 30 seconds to run). The point at which stdout stops appearing changes on each run of the command.

I know that the problem isn't Docker or fig related per se, because a Makefile that runs the exact same `some_command` in the same way as below doesn't have this problem. Could the issue lie with one of the programs I'm running (fig, for example, or sudo) or is this probably an output redirection issue / something that can be fixed by changing `sh` settings?

```
def process_output(line): # This stops being called after some time
    print(line)
# XXX: Some commands expect a TTY STDIN
out_kwargs = {'_out': process_output, '_tty_in': True}

sudo.fig.run('--rm', '-T', 'some_container', '/bin/bash', '-c', some_command, **out_kwargs)
```

**Comment by zdexter** [comment]
Also, with this code, I'm able to get the correct error code from `some_command` and catch it as `ErrorReturnCode_1`, even though I'm never able to see output from when `some_command` errors.

**Comment by amoffat** [comment]
I believe that I've seen something related to this once, and it had to do with the encoding of the output.  Take a look at `_encoding` and `_decode_errors` [here](http://amoffat.github.io/sh/special_arguments.html#special-arguments).  Try changing `_decode_errors` to `"ignore"` and see if that changes the behavior, then we can dig in more
