### ISSUE TITLE
unclear how to run a new sub-shell commands

### ISSUE THREAD

**Issue by ovanes** [amoffat/sh#221]
I hope I named it clear. I need to run a command having this form:

``sudo unshare -u -- sh -c "sysctl kernel.hostname=test123; hostname"``

with sh 1.11 I run it like:

    from sh import sudo
    sudo.unshare('-u', '--', 'sh', '-c', '"sysctl kernel.hostname=test123; hostname"')

but I receive an error stating:

    sudo: unable to resolve host test_container4
    sh: 1: sysctl kernel.hostname=test123; hostname: not found

These commands are run in a ubuntu docker container in privileged mode. I just wonder if that syntax is right...

**Comment by amoffat** [comment]
i don't think you need to extra quote `'"sysctl kernel.hostname=test123; hostname"'`.  each argument to `sudo.unshare` should be a single argument, so the extra quotes shouldn't be necessary.  does that get you further?

**Comment by ovanes** [comment]
Yes! Thanks that work :)
