### ISSUE TITLE
How to (conveniently) run subcommand with dash in name?

### ISSUE THREAD

**Issue by nevik** [amoffat/sh#230]
Specifically, i'm trying to run `git rev-list HEAD` as `sh.git.rev_list('HEAD')` or similar.

For long keyword arguments, the underscore-to-dash conversion works well, but it seems (from the error i'm getting) that it is not applied to subcommands.

Is there some way to use subcommand-as-attribute notation with subcommands that contain dashes?

Edit: I'm aware I can just run `sh.git('rev-list', 'HEAD')` but I'd like to consistently use subcommand-as-attribute notation if possible :)

**Comment by amoffat** [comment]
Interesting.  Unfortunately that doesn't look like something that can be done right now because, under the hood, a subcommand is really just a first argument to a command.  So it would need a step to translate `_` to `-` before passing off the subcommand as an argument.  I don't know that this is possible though, because how would we know if `_` was correct or `-`?  With top-level commands, we check for the existence of the executable with `_` in it, and if it doesn't exist, check for `-`, but for sub commands...any check could have side-effects because we'd have to run the command.

So I don't think it can be done.  But this might be a little cleaner for you than what you're doing now:

```python
rev_list = sh.git.bake("rev-list")
print(rev_list("HEAD"))
```

**Comment by nevik** [comment]
Could you maybe (sometime in the future if it's a lot of work) add more functionality to the baking command, so that subcommands can be mapped (arbitrarily or for underscores only).

So, for example:

```python
g = sh.git.bake(_subcommand_map={'rev_list': 'rev-list'})
g.rev_list('HEAD') # calls `git rev-list` because mapping exists
g.imaginary_command() # calls `git imaginary_command` because no mapping
```

Since subcommand handling just seems string-based, I think a similar logic as for long keyword arguments could be applied, e.g.:
* by the explicit mappings as shown above, or
* by explicitly enabling auto-conversion (e.g. `sh.git.bake(_subcommand_underscore_conversion=True)`).

Of course, as you say, you can't really know if dash or underscore are correct, that applies to the long keyword arguments as well, right? You assume the convention to be dashes and offer the option to disable conversion. I think the same would work here, just use another option (don't bind it to keyword conversion) and maybe default it to off (for backwards compatibility).

**Comment by tersmitten** [comment]
For commands this is an issue too. For instance `ssh-keygen` :-(

**Comment by amoffat** [comment]
@tersmitten can you elaborate?

```python
import sh
sh.ssh_keygen()
```

works fine.  @nevik 's issue was for subcommands

**Comment by tersmitten** [comment]
Is there some auto converting of `_` to `-`? I'll try that tomorrow morning.

**Comment by amoffat** [comment]
yes, it's mentioned in [the documentation](http://amoffat.github.io/sh/#command-execution)

**Comment by tersmitten** [comment]
@amoffat Thanks

**Comment by amoffat** [comment]
Closing this as will not fix.  Reasoning is that subcommands with dashes are somewhat rare, and the subcommand notation is a convenience, so any additional machinery on top of the convenience makes it no longer convienent

**Comment by robertvazan** [comment]
Subcommands with dashes are actually quite common.

I don't know how sh is implemented, but I was wondering, can it tell the difference between function call and an argument? The idea is that when subcommand is added as chained function call (`sh.git.rev_list()`), then it would be automatically translated. If it is passed as an argument (`sh.git('rev-list')`), then it wouldn't be translated. This would result in correct behavior in nearly every case.

**Comment by ecederstrand** [comment]
That would require us to know that `rev_list` is in fact `rev-list`. You may as well have a sub-command that is actually named `rev_list`.

**Comment by robertvazan** [comment]
@ecederstrand The reasoning here is the same as with main commands: dashes are more common than underscores, so make them the default. People can always override the default by switching from function call to explicit argument.

**Comment by ecederstrand** [comment]
The feature for commands (http://amoffat.github.io/sh/sections/faq.html#how-do-i-execute-a-program-with-a-dash-in-its-name) relies on the fact that we can look in `$PATH` to see if `foo-command` exists, when `foo_command` doesn't.

To my knowledge, there is no general way of listing all possible sub-commands which is what we would need to support translating underscores intelligently, like we do for commands.

I don't like the magic of always converting underscores, and I definitely don't like just trying both to see whatever works.

**Comment by robertvazan** [comment]
Aha, okay. I assumed that all underscores are converted to dashes in commands. If you are searching PATH, then the same solution of course wouldn't work for subcommands.

**Comment by bersace** [comment]
Still, I think that dashes are way more common and translating attribute underscore to dash would be very convenient. But this would break compatibility. In any way, the behaviour of import and attr is different. That's a fate.
