### ISSUE TITLE
Document that windows is not supported

### ISSUE THREAD

**Issue by zephraph** [amoffat/sh#231]
It isn't really documented in the README or in the documentation that Windows isn't supported. Adding a little side note for that would be good.

**Comment by honzajavorek** [comment]
I just wrote my whole app using `sh` and now I found this :cry: I need Windows support. To which extent Windows isn't supported?

**Comment by smileboywtu** [comment]
I get the same problem.

**Comment by smileboywtu** [comment]
this can't work with windows, yes?

**Comment by amoffat** [comment]
Windows is not supported, sorry.

**Comment by dragon788** [comment]
@amoffat since pbs supported Windows but now sh doesn't, are there any plans to add in Windows support at some point or its not planned since pbs still mostly works?

**Comment by masaeedu** [comment]
@dragon788 The problem with relying on pbs as a fallback is that new tools and libraries like https://github.com/guyzmo/git-repo are starting to use this project instead, making them inaccessible for Windows users. The caveat that this library "is a full-fledged subprocess replacement *for Linux and OSX*" should be more prominently displayed in the docs and README.

**Comment by techtonik** [comment]
Would be nice to know what the problem with Windows exactly? Maybe it is possible to derive `sh` from some minimal cross-platform library that shares error codes etc. so that people who don't need all Linux power still can use that.

**Comment by amoffat** [comment]
The problem with Windows is the entire process model of launching and communicating with processes... it's built only for Unix variants.  All of it would need to be abstracted away, or duplicated, or filled with `if` statements.  Then all of the keyword options that are not compatible with windows would need to be tied to an error message or made to work some other way.

**Comment by techtonik** [comment]
I found this explanation - https://github.com/amoffat/sh/issues/155#issuecomment-25511277 - that `sh` doesn't use `subprocess`. I don't experience any warm feeling for `subprocess` too, but I can try to run some use cases with https://bitbucket.org/techtonik/shellrun Pipes are hard, though - still struggling to draw all needed diagrams.

**Comment by honzajavorek** [comment]
I'm not in any way affiliated to `plumbum` and I'm far from advertising competing libraries in issues, but since this GitHub issue still gets some traction and `sh` has AFAIK no intent in bringing back dropped Windows support, I'm letting you people know there's also https://pypi.python.org/pypi/plumbum. It's also wrapper around executing shell commands in Python, which has similar interface and seems to run on all platforms.
