### ISSUE TITLE
Using Plumbum as Bash replacement?

### ISSUE THREAD

**Issue by d33tah** [amoffat/sh#236]
In this [StackOverflow answer](http://stackoverflow.com/a/12915952/1091116), one of the users mentioned Plumbum as a Bash replacement. Is there any documentation on how to achieve that in a comfortable manner?

**Comment by amoffat** [comment]
https://plumbum.readthedocs.org/en/latest/#user-guide

**Comment by d33tah** [comment]
I flicked through that and could not see a part that would explicitly cover this use case.

**Comment by amoffat** [comment]
You'll probably want to create an issue over on that project then.

**Comment by d33tah** [comment]
Crap, sorry, used wrong issue tracker. Could you delete this issue?
