### ISSUE TITLE
Thread-safety issue

### ISSUE THREAD

**Issue by wITTus** [amoffat/sh#247]
Hi,

it seems that I stumbled upon a thread-safety issue while using multiple threads creating ssh processes. My initial undertaking was to parallelize the execution of many commands on many machines in order to gather system information. I noticed that data elements in the resulting lists were missing for no reason. Then, I wrote a test case which basically connects a hundred times to `localhost` with at most 10 connections at a time:

```python
#!/usr/bin/env python

from concurrent.futures import ThreadPoolExecutor
from sh import ssh

def fn(host):
	return ssh(host, '-f',
		'-o UserKnownHostsFile=/dev/null',
		'-o StrictHostKeyChecking=no',
		"echo -n TEST"
	)

def main():
	hosts = ["localhost" for i in range(100)]

	with ThreadPoolExecutor(max_workers = 10) as executor:
		outputs = list(executor.map(fn, hosts))
	
	print outputs 

if __name__ == "__main__":
	main()
```

Using 10 workers, the output may look like the following. Note how lots of elements in the resulting list are empty.

```bash
$ ./test.py 
[TEST, , TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, , , TEST, TEST, TEST, TEST, TEST, TEST, TEST, , , , TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, , TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, , TEST, TEST, TEST, TEST, , , , TEST, , , , , , TEST, TEST, , TEST, TEST, , , , , , , , , , , , , , TEST, TEST, , , TEST, , TEST, , TEST, , , TEST, , , TEST, TEST, , , TEST, , , TEST]
```

Using only 1 worker, the output is correct:

```bash
[TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST, TEST]
```

So I guess this is a bug in `sh`'s underlying libraries? Any chance to fix or circumvent this?

I'm using `sh 1.11` with `python 2.7.3`.

Best Regards

**Comment by amoffat** [comment]
Uh oh!  Thanks for reporting this.  This is definitely not good.  Nothing is coming to mind as the cause, and iirc there is no state shared between launched processes, so this is interesting.  

Quick question, can you reproduce this with another command besides `ssh`?

**Comment by wITTus** [comment]
I was unable to reproduce the bug with `ping`, `curl`, `bash`, `date` and `scp`.

My first test (above) was on my system, a Ubuntu 12.04.5 LTS. Tried it today on an other system with Ubuntu 14.04 LTS (python 2.7.6) and got the same strange behaviour.

**Comment by wITTus** [comment]
It does not occur when I substitute the `sh.ssh` call with `subprocess.Popen` in the above test case:

```python
import subprocess

def fn(host):
	process = subprocess.Popen(["ssh", "-f", "-o", "UserKnownHostsFile=/dev/null", "-o", "StrictHostKeyChecking=no", host, 'echo -n TEST'], stdout=subprocess.PIPE)
	return process.communicate()[0]
```

**Comment by amoffat** [comment]
Ok, after a lot of investigation (but admittedly, not a year's worth :), the problem seems to be a subtle bug related to how we were acquiring the controlling terminal.  It has been fixed here https://github.com/amoffat/sh/commit/fde5cce0275fcd67c0f7205812f52348a9209430 and it's on the release-1.2 branch, so it should ship shortly when that branch goes out
