### ISSUE TITLE
sh not displaying interactive prompts while using gentoo portage tools

### ISSUE THREAD

**Issue by Triquetra** [amoffat/sh#251]
`sh.emerge("-uDN", "--ask=y", "@world", _tty_in=True, _out=sys.stdout)` correctly invokes emerge with output to the shell, but interactive elements (like dependency calculation eye candy or confirmation prompt) are not displayed, and cannot be interacted with.  That is, even if a "y" or "n" is entered at the time/place where the confirmation prompt should appear, nothing happens.

`subprocess.call(["emerge", "-uDN", "--ask=y", "@world"], stdout=sys.stdout)` seems to work identically to running emerge directly in the shell

Similarly, `sh.dispatch_conf(_tty_in=True, _out=sys.stdout)` fails to print the input prompt or accept input for the diff/merge of config files (even though the diff itself is displayed).  However, `subprocess.call(["dispatch-conf"], stdout=sys.stdout)` seems to work identically to running dispatch-conf in a shell.

Both emerge and dispatch-conf are part of the gentoo portage package manager.

I've tried adding _tty_out=False and/or _in=sys.stdin as arguments to the sh calls without improvement, though not without effect.  Is there something I'm missing to get these programs to work with sh?

**Comment by amoffat** [comment]
The feature you're describing is [foreground mode](https://github.com/amoffat/sh/issues/92) but unfortunately it has not yet been built.  There is no way to use interactive scripts reliably with `sh` yet.

**Comment by Triquetra** [comment]
Yes, that sounds like what I'm looking for.  I see the thread you linked to is 2.5 years old.  Is there an ETA for this feature?  Pexpect looks like a great candidate to borrow code from.

**Comment by amoffat** [comment]
I think the route I will end up taking is [this comment.](https://github.com/amoffat/sh/issues/92#issuecomment-86567667)  No ETA on it yet, but I will review and merge it if someone else gets to it before I do.

**Comment by amoffat** [comment]
A very lightweight foreground mode via `_fg=True` is implemented in the release-1.2 branch
