### ISSUE TITLE
can't configure logging?

### ISSUE THREAD

**Issue by vlovich** [amoffat/sh#254]
Hi,

I'm trying to get the logging from sh to appear.  Namely I'm just looking for the unadorned command to be put onto the logs so that I can copy-paste/diagnose when issues come-up.

I've tried

    import logging
    import sh
    logging.basicConfig(level=logging.DEBUG)
    out = sh.ls()

but I don't see the ls command.  I've also tried getting the "command" logger & setting the level there to no avail.

**Comment by amoffat** [comment]
I put your code in a script, and the first line I get from logging is:

`INFO:sh.command:<Command '/bin/ls' call_args {'bg': False, 'timeo...(476 more)>: starting process`

`/bin/ls` is the command run and will contain any arguments you pass in.  Is this what you're looking for?  `DEBUG` is a bit noisy btw, you probably just want `INFO`.

**Comment by vlovich** [comment]
That's strange.  Maybe I have an old version of sh installed?  I see the logging correctly on some other machines.  Strange.
