### ISSUE TITLE
preview/print complete command line args list

### ISSUE THREAD

**Issue by fwang2** [amoffat/sh#256]
hi, is there a way to preview the command line args that `sh` is about to execute? something like a a _dry_run=True option ...? This could be useful for debugging the long command line.

**Comment by fwang2** [comment]
well, on second thought, there is a workaround: build up the list for printing, and pass it with * expansion.
I am going to close this issue.

**Comment by amoffat** [comment]
you have two other options as well:

1. turn on logging:  `logging.basicConfig(level=logging.INFO)`
2. use bake, which bakes in arguments into a partial that can be printed:
```python
import sh
my_ls = sh.ls.bake("-l", "~/")
print(my_ls)
```
