### ISSUE TITLE
cd as context manager

### ISSUE THREAD

**Issue by kyrias** [amoffat/sh#257]
Hey, would you be interested in making `b_cd` be possible to use in a `with` context so that you can easily run commands in a specific directory without having to save which one you were in and then `cd` back?

**Comment by amoffat** [comment]
I like the idea.  I wonder how easy it would be to do without breaking backwards compatibility

**Comment by reorx** [comment]
+1 for this idea!

**Comment by sureshvv** [comment]
+1

**Comment by ppannuto** [comment]
sh already has pushd for this

```bash
$ tree .
.
+-- child
¦   +-- test-child1
¦   +-- test-child2
+-- test-root1
+-- test-root2
```

```python
print(ls())
with sh.pushd('child'):
    print(ls())
```

```
test-root1 test-root2
test-child1 test-child2
```
