### ISSUE TITLE
Arguments generated from keywords do not work on some programs

### ISSUE THREAD

**Issue by minus7** [amoffat/sh#258]
For example, `sh.xrandr(output="DP1", off=True)`, which generates `["xrandr", "--output=DP1", "--off"]` does not work because `xrandr` does not understand the argument separated by an equal sign. using `_long_sep=" "` does not work either, because it still is passed as one argument (`["xrandr", "--output DP1", "--off"]`). Some tools, like `xrandr`, require arguments passed in the form `["xrandr", "--output", "DP1", "--off"]`. I suggest either interpreting `_long_sep=" "` as such or adding another configuration variable.

**Comment by minus7** [comment]
As nicely as the patch works, it can't fixed the lack of order in dicts: `/usr/bin/xrandr: --off must be used after --output`

**Comment by amoffat** [comment]
it sounds like, unfortunately, to preserve ordering, you will need to use the uglier way of calling the command:

```python
sh.xrandr("--output", "DP1", "--off")
```

**Comment by minus7** [comment]
Yeah, just did so. Nothing can be done about it though. Thanks.
