### ISSUE TITLE
add support for preexec_fn

### ISSUE THREAD

**Issue by dz0ny** [amoffat/sh#260]
This is used to change user and group of running process

**Comment by amoffat** [comment]
seems simple.  if someone gets to it first, it would probably go here

https://github.com/amoffat/sh/blob/master/sh.py#L1287

and do something like

```python
preexec_fn = self.call_args["preexec_fn"]
if callable(preexec_fn):
    preexec_fn()
```

and add the name "preexec_fn" here https://github.com/amoffat/sh/blob/master/sh.py#L669 with a default of `None`

then documentation and tests
