### ISSUE TITLE
Async exec

### ISSUE THREAD

**Issue by esc** [amoffat/sh#267]
Is it possible to execute a program asynchronously? I.e. execute 'sleep 100' and then poll it every so often to check that it is done while doing other things, e.g. handling webrequests.

**Comment by esc** [comment]
Okay, I can use `_bg=True` but how can I poll it to see if it is done?

**Comment by esc** [comment]
So If I use `_done` the callback won't be called until i block with `wait`?

**Comment by esc** [comment]
`subprocess` supports `poll` which returns None while the code is running and the exit code when it is done, but I suppose `sh` doesn't support that?

**Comment by amoffat** [comment]
You should use the `_done` callback, but I believe it doesn't work correctly in the 1.1 release.  It's fixed in the 1.2, which is shipping soon.

**Comment by esc** [comment]
ok, good to know, can't remember where I had this problem though.. :8ball:

**Comment by esc** [comment]
@amoffat btw, I LOVE `sh`---it has saved my but on a number of occasions and frankly, it's the most pythonic interface to the system yet. I would include it in the standard library.

**Comment by amoffat** [comment]
@esc Thank you!  I'm happy to hear it is helping :+1:  Maybe one day it will get included in the stdlib-- we'll see!

**Comment by esc** [comment]
Yeah, its one of those truly awesome libraries! Like, its actually a viable replacement for shell scripts. If you need me to help with reviewing code, just ping me on issues.
