### ISSUE TITLE
touch command doesn't work in touch{"f{1..10}")

### ISSUE THREAD

**Issue by rsmith31415** [amoffat/sh#274]
I noticed that `touch` doesn't expand its argument:

```
>>> sh.touch("f{1..10}")

>>> sh.ls()
f{1..10}
```

Is this a bug?

**Comment by amoffat** [comment]
No.  A shell does shell expansions.  sh just launches processes.

**Comment by rsmith31415** [comment]
Sure. I understand that but would it be possible to accommodate such use cases with something like:

```
>>> sh.bash('-c', 'echo f{1..5}')
f1 f2 f3 f4 f5
```

**Comment by amoffat** [comment]
Of course it would be possible, but I don't have any desire to include bash rules in sh.  If you need to create things programmatically, use python:

```python
for i in xrange(1, 6):
    sh.touch(f + str(i))
```

**Comment by rsmith31415** [comment]
Sure, no problem. The reason I'm asking is that I want to know if it is possible to get a useful web terminal with only sh commands without requiring something such as [tty.js](https://github.com/chjj/tty.js/)
