### ISSUE TITLE
Using sh.cd to go to the home directory

### ISSUE THREAD

**Issue by rsmith31415** [amoffat/sh#275]
Is there some way to simulate `cd` (in order to go to the home directory) without giving arguments to sh.cd? Currently:

```
>>> sh.cd
<bound method Environment.b_cd of {}>
>>> sh.cd()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: b_cd() takes exactly 2 arguments (1 given)
```

Another question: what other "Environment" methods are there besides `cd`?

**Comment by amoffat** [comment]
1.  No
2.  Take a look at [the source](https://github.com/amoffat/sh/blob/master/sh.py#L2235-L2244)

**Comment by rsmith31415** [comment]
1. Maybe it is possible to use `os.path.expanduser('~')` to provide a `cd`:

```
def b_cd(self, path):
    if path:
        os.chdir(path)
    else:
        os.chdir(os.path.expanduser('~'))
```

2. Thanks

**Comment by amoffat** [comment]
@rsmith31415 that looks pretty close.  I would make `path` have a default value of `None` though in the function.  Open a PR and I will likely merge it :)

**Comment by rsmith31415** [comment]
If you think it is that simple to solve, sure.
