### ISSUE TITLE
TimeoutException equivalent for pbs

### ISSUE THREAD

**Issue by rsmith31415** [amoffat/sh#277]
Is there some equivalent of `TimeoutException` for pbs? I'm trying to prevent something like `sh.vim()` that hangs the REPL. Currently, using a timeout (`sh.vim(_timeout=5)`) works okay, but this doesn't work in the pbs version for Windows.

By the way, it has been a while since anyone asked about Windows support. Is there some chance to provide it in the future?

**Comment by amoffat** [comment]
pbs is unsupported and I have no plans for supporting windows
