### ISSUE TITLE
ErrorReturnCode not well documented

### ISSUE THREAD

**Issue by jorisroovers** [amoffat/sh#283]
I was looking at the documentation on [http://amoffat.github.io/sh/#exit-codes]() and found that the  `ErrorReturnCode` exception is not well documented.
In particular, I found that the following members of the exception are not mentioned: `args, exit_code, full_cmd, message, stderr, stdout, truncate_cap`.

I'd be happy to submit a pull request that adds a little more detail if this issue is confirmed.

**Comment by amoffat** [comment]
Confirmed, some more docs would be welcome @jorisroovers

**Comment by amoffat** [comment]
http://amoffat.github.io/sh/sections/command_class.html#errorreturncode
