### ISSUE TITLE
Multiple arguments overwrite each other

### ISSUE THREAD

**Issue by sean-bennett112** [amoffat/sh#285]
I was trying to use sh to configure the tool Terraform, and was consistently getting errors when running it.

Running the command:

```python
bucket = '-backend-config="bucket=org-terraform"'
key = '-backend-config="key=%s/org/%s"' % (region, branch)
sh.terraform('remote', 'config', '-backend=S3', bucket, key,
             _env={
                 'AWS_ACCESS_KEY_ID': aws_access_key,
                 'AWS_SECRET_ACCESS_KEY': aws_secret_key
             })
```

returns the Terraform error:

```
RAN: '/usr/local/bin/terraform remote config -backend=S3 -backend-config="bucket=org-terraform" -backend-config="key=us-east-1/org/example"'

STDOUT:

STDERR:
missing 'bucket' configuration

If the error message above mentions requiring or modifying configuration
options, these are set using the `-backend-config` flag. Example:
-backend-config="name=foo" to set the `name` configuration
```

Though the `bucket` backend-config parameter is definitely there. Running the same command straight through the CLI also works fine.

At first I thought it might be something weird with quotes, but every change I made there exhibited the same behavior(failed through `sh`, succeeded in the CLI). Looking through the source however, it looks like in [`__call__` in sh.py](https://github.com/amoffat/sh/blob/master/sh.py#L948) the `call_args` are stored as a dict. My guess is that the second occurrence of `-backend-config` in the above command is overwriting the first, thus causing the issue.

This is just my best guess at what's going on, but thought I'd give as much info as possible along with this.

**Comment by amoffat** [comment]
The args shouldn't overwrite.  Some programs are picky about how their options are specified.  Try breaking up all the arguments where you're doing `"-key='value'"` into `"-key"`, `"value"`
