### ISSUE TITLE
piping tar

### ISSUE THREAD

**Issue by lesgrossman** [amoffat/sh#286]
I am trying to do the equivalent of:
      tar ch --exclude-file blah . | docker build -t tag -
      this takes say 7 secs (this is a know built state)

same command in "sh" which I hope is close to:
    [ print (line.rstrip()) for line in sh.docker(sh.tar("ch" "--exclude-file", "blah", "."), "build", "-t", "tag", "-", _iter=True, _tty_out=True)]
     this takes 97 secs

any ideas

**Comment by amoffat** [comment]
you want to add `_piped="direct"` to your tar command.  that will make the output of tar get streamed to docker as it goes, instead of waiting for tar to finish first.  it still won't be as fast as the shell, but it will be faster than it is now

**Comment by lesgrossman** [comment]
Thanks, although it seems just as fast...

**Comment by lesgrossman** [comment]
does the for loop make sense, or will i gain anything using _out=<function> and print there?

**Comment by amoffat** [comment]
i think it's fine.  using an `_out` callback is preferred when you want to do additional processing on each line

**Comment by lesgrossman** [comment]
awesome, thanks

**Comment by lesgrossman** [comment]
Just want to add that the "Special Arguments" page should be updated to reflect the "direct" option
