### ISSUE TITLE
time support

### ISSUE THREAD

**Issue by lesgrossman** [amoffat/sh#287]
Often running shell commands, it nice to now how long things take.

    time find . 
    time tar cf . | dosomething

Is something already supported in "sh" that supports this?  or is this a feature request?

**Comment by amoffat** [comment]
show me what you've tried so far

**Comment by lesgrossman** [comment]
well based on what little I know about the sh module, I would 
     sh.time("docker build .")
     sh.time("tar cf . | docker build -"), but what I know here would really be
     sh.docker(sh.time("tar cf . "))

but time isn't really piped into anything.  it's the elapsed time of the commands, so think 
     time "exec | exec | exec"

**Comment by lesgrossman** [comment]
Currently that is the direction I'm going.  It would be nice if it was
supported by the module itself.



Together We Win!   Looking for cloud storage, try copy.com
<https://copy.com?r=6BuEoY> (20g free <https://copy.com?r=6BuEoY>)
--
Chad - Sisel Promoter
Take Your Life Back! <http://choman.mysiselpro.com/>
Creating A More Meaningful Life

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

Some people claim if you play a Windows Install Disc backwards you'll hear
satanic Messages.
That's nothing, if you play it forward it installs Windows

**Comment by amoffat** [comment]
profiling functions is something i'd rather leave to the caller.  it's really as simple as

```python
start = time.time()
# something
print(time.time() - start)
```

**Comment by lesgrossman** [comment]
Thanks again

Together We Win!   Looking for cloud storage, try copy.com
<https://copy.com?r=6BuEoY> (20g free <https://copy.com?r=6BuEoY>)
--
Chad - Sisel Promoter
Take Your Life Back! <http://choman.mysiselpro.com/>
Creating A More Meaningful Life

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

Some people claim if you play a Windows Install Disc backwards you'll hear
satanic Messages.
That's nothing, if you play it forward it installs Windows
