### ISSUE TITLE
command list?

### ISSUE THREAD

**Issue by lesgrossman** [amoffat/sh#288]
It's not apparent in the docs, so I am just verifing.

I am building a command line by appending to a list.  once done, can I pass the list as 
arguments to my sh.xyz function.  for example:

args = []
args.append("-la")
args.append("/home")
sh.ls(args)

It seems to work, but since I could not find a direct reference in the online docs.  I'm checking

**Comment by amoffat** [comment]
yeah, lists of arguments are expanded automatically.  added a docs tag to this

**Comment by lesgrossman** [comment]
Thanks again

Together We Win!   Looking for cloud storage, try copy.com
<https://copy.com?r=6BuEoY> (20g free <https://copy.com?r=6BuEoY>)
--
Chad - Sisel Promoter
Take Your Life Back! <http://choman.mysiselpro.com/>
Creating A More Meaningful Life

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

Some people claim if you play a Windows Install Disc backwards you'll hear
satanic Messages.
That's nothing, if you play it forward it installs Windows

**Comment by amoffat** [comment]
Could you do me a favor and not spam the issues with your business please?  I understand that it's from posting from email, but I'd rather not have the issues littered with promotions.
