### ISSUE TITLE
Would like an empty form of 'bake' that allows changing arguments

### ISSUE THREAD

**Issue by virtuald** [amoffat/sh#291]
Here's what I would like to be able to do:

    redir = sh.bake(_out=something)
    redir.cat('file')  # output goes to 'something'

Currently bake seems to require a subcommand, which is undesirable for general overriding. Also, the `args` contextmanager is very similar to what I want -- but it overrides globally, which is not what I want.

**Comment by amoffat** [comment]
I think you are looking for this https://github.com/amoffat/sh/pull/271  which will be in the 1.2 release.  It would let you do...

```python
redir = sh(_out=something)
from redir import cat as my_cat
my_cat('file')
```

**Comment by virtuald** [comment]
That is precisely what I would be looking for.
