### ISSUE TITLE
Argument substitution

### ISSUE THREAD

**Issue by mbiokyle29** [amoffat/sh#294]
Hello. First off thanks for your hard work on `sh.py` it is an incredible library!
I had a quick question about argument substitution with baking. Basically I have a command line program that takes a number of parameters. I am processing a list of files with this program, so some options will remain the same across all calls (things like the directory) and some things will change (the file)

So an example might be:
```python
program = sh.program.bake("--some-flag", constant_value, "--other-flag", variable_value, "--some-flag", constant_value)

for file in files:
    variable_value = file+".output"
    program(variable_value, file)
```
with the result being 
```bash
program --some-flag constant_value --other-flag variable_value  --some-flag constant_value file
```

The issue is basically I have two variable values which must be placed between a constant value and I'd just like to call bake once and be able to substitute the variable values in like one would do with string formatting or parameter binding (like when using a SQL query from python). Is that possible?

**Comment by 20after4** [comment]
I've been trying to find an elegant solution to this problem as well. I don't think `sh` has a suitable feature for this but it would be awesome if this syntax would work:

```python
program = sh.program.bake('--some-flag', constant_value,
                          '--other-flag', '{var_name}',
                          '--some-flag', constant_value)

for file in files:
    program(file, var_name=variable_value)
```

I've started writing a class to handle this specific command templating use-case but then I thought to check if it already exists. In the process I found this.

I wonder if @amoffat would be willing to consider a pull request that adds this functionality directly to sh? I think that would be a lot more convenient than using a standalone library for such a tiny bit of functionality.

**Comment by amoffat** [comment]
Hi.  Sorry I missed the original issue... my feed can be pretty noisy.  @20after4 there is nothing there now, and I'm not sure a PR would be worth the effort--this seems like a perfect case for a simple function wrapper:

```python
def my_program(var_name):
    return sh.program("--some-flag", constant_value, "--other-flag", var_name, "--some-flag", constant_value)
```

I know it requires a little more boilerplate, but I think a special templating mechanism comes with its own problems, and this issue seems rare enough that a simple function wrapper won't seem burdensome.

**Comment by mbiokyle29** [comment]
That is actually an awesome solution. Thank you!
