### ISSUE TITLE
Most reliable way of executing a command forcing a timeout

### ISSUE THREAD

**Issue by joseangeljimenez** [amoffat/sh#296]
I am using sh.sudo() under Debian to execute administrative commands. However, some of these may hang for a long time, hence I want to add a timeout protection to the execution.

Is the _timeout parameter reliable for this is use case? Even if the command creates additional (child) processes? What would we your suggested approach?

**Comment by amoffat** [comment]
This issue went under my radar and I'm sure you've moved on past it by now, but in case anyone else is searching for a similar question, yes this is the intended use of `_timeout`
