### ISSUE TITLE
Mocking documentation/examples missing

### ISSUE THREAD

**Issue by peikk0** [amoffat/sh#297]
Issue #51 refers to wiki documentation about mocking, unfortunately it has seems to have disappeared over the rename from pbs to sh and it didn't make it into the new documentation.

In my case, I'm trying to mock a sh call and to make it:
- run a dummy command instead (like echo)
- or run nothing and return a fake result
  And I can't find a proper way to do either one.

**Comment by amoffat** [comment]
Not sure what kind of special docs are needed...standard mocking works for me:

```python
from unittest.mock import patch
import sh

@patch("sh.ls")
def test(mocked_ls):
    mocked_ls.return_value = "mocked"
    assert sh.ls("/") == "mocked"

test()
```

**Comment by amoffat** [comment]
Let me know if this solves your issue @peikk0

**Comment by peikk0** [comment]
Well I don't remember what exactly I needed that for, and the project I was working on at the time is over, so I think you can close the issue. :)

**Comment by amoffat** [comment]
Cool :)
