### ISSUE TITLE
Simpler way to redirect _out to stdout and _err to stderr

### ISSUE THREAD

**Issue by honzajavorek** [amoffat/sh#301]
Let's say I want to run linter from within my Python program. I want to redirect all its output to the wrapping program's output. This works:

```python
import sys

import sh


def redirect_stdout(line, stdin, process):
    sys.stdout.write(line)


def redirect_stderr(line, stdin, process):
    sys.stderr.write(line)


redirect_output = {'_out': redirect_stdout, '_err': redirect_stderr}


def main():
    sh.flake8('.', exclude='env', **redirect_output)
```

My question would be - is there an easier way how to do this? Without the boilerplate functions and all that.

**Comment by arthurdarcet** [comment]
I think
```python
def main():
    sh.flake8('.', exclude='env', _out=sys.stdout, _err=sys.stderr)
```
should work fine

**Comment by borgstrom** [comment]
Use `_err_to_out=True`.  https://amoffat.github.io/sh/special_arguments.html#term-err-to-out

I personally like to use it with `_iter=True`

```
for line in sh.flake8('.', exclude='env', _err_to_out=True, _iter=True):
    print(line)
```

**Comment by amoffat** [comment]
@arthurdarcet and @borgstrom are both valid solutions.  With release-1.2 (coming soon), there is also the "foreground" option... `_fg=True` which will execute your command and connect it to stdin/stderr/stdout and block until it completes.
