### ISSUE TITLE
Need reference docs

### ISSUE THREAD

**Issue by dbarnett** [amoffat/sh#302]
I don't see any reference docs at http://amoffat.github.io/sh/ covering the full list of special methods and properties a `Command` object supports, special arguments the constructor accepts, etc. Can those docs be written, or if they already exist can they be linked more prominently off of http://amoffat.github.io/sh/?

**Comment by amoffat** [comment]
docs have been rewritten.  http://amoffat.github.io/sh/sections/special_arguments.html
