### ISSUE TITLE
sh.Command __unicode__ throws if object isn't completely constructed

### ISSUE THREAD

**Issue by virtuald** [amoffat/sh#304]
We have an [exception logger](http://word.bitly.com/post/69080588278/logging-locals) that captures the inner stack frame and prints out locals. When `CommandNotFound` is thrown in the constructor, the necessary attributes (`_path` and `_partial_baked_args`) haven't been set yet, and so repr(self) throws.

It's a bit of a weird use case, but should be trivial to fix.

**Comment by amoffat** [comment]
Thanks for reporting @virtuald.  [Fix](https://github.com/amoffat/sh/commit/b08586ff8829652d300f908b37ce01f3a8417cbb) is on the `release-1.2` branch and will go out with it
