### ISSUE TITLE
git blame command works when run in ipython session but not when running script

### ISSUE THREAD

**Issue by jmsy00** [amoffat/sh#305]
I can't seem to debug this.  In my script I bake a git command:

```
def annotate_config():
    from sh import git 
    blame = git.bake('--no-pager', 'blame', '-w', '-L', '/\[Task\]/,/\[/', _cwd=fdir)
    annotation = []
    for line in blame(os.path.join('config', 'config.properties'), _iter=True):
        line = blame_to_dict(line.strip())
        if line is not None:
            annotation.append(line)
   return annotation
```

This works fine when I load/run in an ipython session, but when I run the script directly I get

```
  RAN: '/.../git --no-pager blame -w -L /\\[Task\\]/,/\\[/ config/config.properties'

  STDOUT:


  STDERR:
```
I've tried variously settting _tty_out/in to true/false to no avail.  Can anyone help?

**Comment by amoffat** [comment]
What's the error exception number?

**Comment by jmsy00** [comment]
255

**Comment by amoffat** [comment]
https://github.com/amoffat/sh/blob/master/sh.py#L1298-L1302

sh will raise 255 if there's an error between fork and execute.  One of the things that could raise an error is `os.chdir(cwd)`.  Are you sure you picked a real cwd?  Can your user change into it?

**Comment by jmsy00** [comment]
Yeah, I'm pretty sure the process can chdir to the directory, it's just the root level directory of the git branch I'm on.  Why do you think it works when I load the script into ipython and call the func in the script?

This is from a pdb session:
```
   367 def annotate_config():
--> 368     fdir=get_root_dir()
    369     blame = sh.git.bake('--no-pager', 'blame', '-w', '-L', r'/\[Task\]/,/\[/')#, 
ipdb> os.chdir(fdir)
ipdb> blame(os.path.join(fdir,'config', 'config.properties'))
*** ErrorReturnCode_255:

  RAN: '/.../bin/git --no-pager blame -w -L /\\[Task\\]/,/\\[/ /.../config/config.properties'

  STDOUT:


  STDERR:
```

**Comment by amoffat** [comment]
No idea tbh, this is everything that can go wrong between fork and exec https://github.com/amoffat/sh/blob/master/sh.py#L1225-L1286

**Comment by jmsy00** [comment]
well, I tried pdb'ing but it hangs at line 1265 when sh attempts to dup 'slave_stdout_fd', either because of the pdb session or because there's an actual issue during the duplication.

**Comment by amoffat** [comment]
Doesn't seem like anyone else has had a similar problem, so unfortunately I will close this unanswered.  I cannot reproduce it either.
