### ISSUE TITLE
Piping seems to be broken with Unicode errors

### ISSUE THREAD

**Issue by catsclaw** [amoffat/sh#307]
`mysql('db', cat('dump.sql'))` throws the following error:

    Traceback (most recent call last):
      File "db.py", line 91, in <module>
        args.func(args, access_key, secret_key)
      File "db.py", line 62, in _restore
        mysql('nwm', cat('dump.sql'))
      File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1000, in __call__
        processed_args = self._compile_args(args, kwargs, call_args["long_sep"])
      File "/usr/local/lib/python2.7/dist-packages/sh.py", line 879, in _compile_args
        processed_args.append(encode_to_py3bytes_or_py2str(arg))
      File "/usr/local/lib/python2.7/dist-packages/sh.py", line 139, in encode_to_py3bytes_or_py2str
        s = unicode(s)
      File "/usr/local/lib/python2.7/dist-packages/sh.py", line 593, in __unicode__
        self.call_args["decode_errors"])
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3024: ordinal not in range(128)

How is one supposed to handle the piping here?

**Comment by amoffat** [comment]
Can you even cat the file with sh?  Is it just the piping that is breaking?

**Comment by catsclaw** [comment]
Yes, I can run `cat dump.sql | mysql db` on the command line without errors.

**Comment by amoffat** [comment]
> with sh

**Comment by catsclaw** [comment]
I don't understand the question? If you asking if I can run `cat dump.sql` on the command line, it blows up my terminal session. I'm running this is a docker session. It's clear there are non-ascii characters in the file.

**Comment by amoffat** [comment]
```python
import sh
sh.cat("dump.sql")
```

**Comment by amoffat** [comment]
Just to circle back around on this, in case anybody else runs into the same problem, I'm guessing your terminal session has `LANG=C` or something, which is why the default encoding is "ascii" on the `sh.cat" process.  If you're in an ascii env, and you know you have unicode you need to pass around, specify the encoding on the process:  `sh.cat("dump.sql", _encoding="utf8")`
