### ISSUE TITLE
Single dash in sub commands

### ISSUE THREAD

**Issue by kirklg** [amoffat/sh#308]
Hello @amoffat, first off, thank you very much for `sh`.

So, I am trying to use `sh` to provide an interface with `hadoop` and the argument styles are one dashed (i.e `hadoop fs -ls /`), it would be nice to do something like this:

```python
from sh import hadoop

fs = hadoop.fs
fs.ls('/')
```
But again, because they are one-dashed `sh` is unable to determine the correct sub command within the `__getattribute__` function, is there something I can possibly do to get this to work, or is this something that we can get a feature request for?

Thank you!

**Comment by amoffat** [comment]
try

```python
fs = hadoop.fs
fs_ls = fs.bake("-ls")
fs_ls("/")
```

[baking](https://amoffat.github.io/sh/#baking)

**Comment by kirklg** [comment]
That works, thanks.
