### ISSUE TITLE
Bake not working as expected

### ISSUE THREAD

**Issue by raj2569** [amoffat/sh#313]
Hi,

I am a new user trying out sh, and I find that the Keyword arguments are not working as expected, given this short program

```python
from sh import fping
fping.bake(i="10", q=True, C="5")
print fping
```
I expect the output to be `/usr/bin/fping -i 10 -q -C 5` but I only get  `/usr/bin/fping` as the output. I tried using the other form of keyword arguments `fping.bake("-i", "10", "-q", "-C", "5")` also in the bake but the result is the same. 

When giving keyword argument directly in the command as in

```python
from sh import fping
ret = fping (i="10", q=True, C="5", "192.168.3.18")
print ret
```
I get this error:
```
  File "ping.py", line 2
    ret = fping (i="10", q=True, C="5", "192.168.3.18")
SyntaxError: non-keyword arg after keyword arg
```
I am using:
```
Name: sh
Version: 1.11
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
``` 
on Debian 8.3

I am not sure if this is a bug or I am doing some thing wrong. My ultimate aim is to run this ` fping -i 10 -q -C 5 192.168.3.18`. 

Also is there any way I can print the exact command sh is executing, with out the actual command being executed?

Thanks!

**Comment by amoffat** [comment]
wrt baking:

```python
from sh import fping
fping = fping.bake(i="10", q=True, C="5")
print fping
print fping("192.168.3.18")
```

`.bake` method returns a "baked" command.

```python
from sh import fping
ret = fping (i="10", q=True, C="5", "192.168.3.18")
print ret
```

This is basic Python... keyword arguments cannot be before non-keyword arguments.  This is correct:

```python
from sh import fping
ret = fping ("192.168.3.18", i="10", q=True, C="5")
print ret
```

**Comment by raj2569** [comment]
Thanks for the answer. `.bake` is now working fine.
