### ISSUE TITLE
Line-buffered iterator fails when lines are +1024 bytes

### ISSUE THREAD

**Issue by ecederstrand** [amoffat/sh#314]
I'm using sh to call an Oracle client (sqlplus) that returns the resultt of some SQL queries. I use _iter=True and _encoding='utf-8' to create a line-buffered iterator that my code can easily consume, one row at a time. This works great.

But sometimes, the client spits out a line that is more than 1024 bytes long. If this happens, get_iter_string_reader() will chop the line at 1024 bytes, resulting in either a UnicodeDecodeError (if a multi-byte char was chopped in half) or my own code will raise exceptions because the current and following line contains malformed data.

What are my options here? I could create a patch to make the 1024 byte configurable since the line-buffered iterator is very convenient for me, but maybe there's an easy workaround?

**Comment by ecederstrand** [comment]
Sorry, bad analysis. The problem is `bufsize_type_to_bufsize()` where `bufsize` is set to 1024 regardless if that actually is enough to encounter a newline. I have tested setting is to 32767 which fixes my issue.

**Comment by ecederstrand** [comment]
I'm trying to fix this in a more general way than just setting a long enough `bufsize`, but there's a design error in that quite a lot of places does `chunk.decode(self.encoding)` which is not safe in combination with a multibyte encoding because multibyte chars could be chopped in half if the line is longer than `bufsize`.

**Comment by ecederstrand** [comment]
Here's a simple script that demonstrates the problem:

```
# -*- coding: utf-8 -*-
from sh import printf
output = printf(
    'X'*1023 + 'æ',
    _iter=True,
    _encoding='utf-8',
)

for line in output:
    print(line)
```

This results in:

```
b'XXXXX[...]XXXXX\xc3'
b'\xa6'
```

which is A) of type bytes, not str and B) two lines when it should be only 1.

I have submitted two PRs to fix the problem (not decoding multibyte chunks that are not guaranteed to be decodable, supporting line-buffering with multibyte lines longer than 1024 and not silently switching to binary mode). I've run the patches in production for a couple of months without issues.

**Comment by amoffat** [comment]
I appreciate your work on this @ecederstrand.  I have been extremely busy with work and life lately, and unable to review/test and merge submissions.  It will happen eventually though.  Thank you for your patience.

**Comment by ecederstrand** [comment]
No problem. Just trying to reduce my collection of local patches :-)

**Comment by amoffat** [comment]
Great work cleaning this up and helping it make more sense :+1:  Your PRs will go out with the release-1.2 branch
