### ISSUE TITLE
How to properly debug sh.py

### ISSUE THREAD

**Issue by yitjob** [amoffat/sh#317]
I'm launching two consecutive sh commands (libreoffice --headless with different files) , but only the second time it just doesn't work as expected.

The process runs as www-data and I'm having some difficulty to know whether it is the HOME env setting or a permission issue, and get the output.

I tried setting as follows, but sometimes the logfile is truncated then it remains empty:
```Python
cmd._call_args['out'] = '/var/log/lolog'
cmd._call_args['err'] = '/var/log/lolog'
cmd._call_args['env'] = {'HOME': '/tmp/lo/'}
```

Doing the debug with Winpdb does not help too much, as the forks make the execution different from what it would be done normally by sh.py.

So, is there any particular hook or method to debug that I'm missing here?

Thank you,

**Comment by amoffat** [comment]
sh is hard to debug given the nature of process forking.  Your best bet would be to experiment in the shell and find the exact commands that work flawlessly, then translate them to sh commands.  Btw, you don't want to use `_call_args` like you're using them...it's a private attribute for a reason :)   Check out [here](https://amoffat.github.io/sh/#environments) to set environment variables
