### ISSUE TITLE
How to GIT_SSH?

### ISSUE THREAD

**Issue by Nachtfeuer** [amoffat/sh#319]
Hi,

what I'm looking for is how to pass the GIT_SSH to git.
Let's say I have following:
 - **/tmp/foo/id_rsa_foo**
 - **/tmp/foo/id_rsa_foo.pub**
 - **no passphrase**
 - and registered at a repository.
 - and a shell script **/tmp/foo/git_ssh** which does  a "/usr/bin/ssh -i /tmp/foo/id_rsa_foo $@"
 - and **chmod +x /tmp/git_ssh**

The command "GIT_SSH=/tmp/foo/git_ssh git ls-remote ssh://git@your_repo.git" should work

Can this be done with this library?

**Comment by amoffat** [comment]
Did you try this?  http://amoffat.github.io/sh/#environments
