### ISSUE TITLE
Command execution fails with sh.SignalException_11 with high resource.RLIMIT_NOFILE

### ISSUE THREAD

**Issue by bendikro** [amoffat/sh#320]
On a system where the resource.RLIMIT_NOFILE limit has been raised to above 2048, the call to https://github.com/amoffat/sh/blob/023dc557f1f272ec0b7c118d263c094b0c3e604f/sh.py#L1276 will result in a segmentation fault:

```python
$ ulimit -n 2049
$ python -c "import sh; pcmd = sh.Command('perl'); pcmd('--version')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 486, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.SignalException_11:

  RAN: '/usr/bin/perl --version'

  STDOUT:


  STDERR:


```

I'm not sure why is fails at exactly above 2048. Could be dependent on some other OS setting.

**Comment by amoffat** [comment]
I don't believe that line is causing the exception you're seeing.  If `os.closerange(3, max_fd)` segfaulted, you wouldn't see that output.  If it raised an exception, you would see an exit code of 255.  This leads me to believe it is legitimately perl throwing your exception.  Try launching perl with the `subprocess` module and/or `os.system` and let me know the results.

**Comment by bendikro** [comment]
Yeah, the python process doesn't segfault, but the process started with `os.execv` does (or I presume based in the code 11). What I meant specifically is that `sh.SignalException_11` is thrown only when `os.closerange(3, max_fd)` is called with `max_fd >= 2048`.

However, I just tried to reproduce the issue on another Linux installation but it doesn't give the same error, so I'm not sure what exactly is going on here.

**Comment by amoffat** [comment]
What happens if you hardcode `max_fd` to be 2048 (or the number that doesn't fail), but you leave your `RLIMIT_NOFILE` value the same?

**Comment by bendikro** [comment]
Oh man, after testing this further, it turns out it was the child process that segfaultet when trying to close fd 2048. Normally it would throw an invalid file descriptor error, but I forgot I had recently messed with the LD_PRELOAD variable which preloaded a library (needed for something else) that apparently makes some changes causing the segmentation fault. By not preloading the library it works as expected. Sorry for the noise :-)

**Comment by amoffat** [comment]
No worries, happy you figured it out :+1:
