### ISSUE TITLE
if subcommand name is 'import', it will report invalid syntax

### ISSUE THREAD

**Issue by starplanet** [amoffat/sh#322]
I use sh to call sqoop tool which supplies import subcommand to import data from mysql to hdfs.

If I run following codes, it will report invalid syntax:
```python
from sh import sqoop
sqoop.import()
```
it will return:
```python
  File "<ipython-input-22-3115c14a7852>", line 1
    sqoop.import()
               ^
SyntaxError: invalid syntax
```

But if I use other subcommand that sqoop supplies, it will work fine.
```python
from sh import sqoop
sqoop.export()
```

So I doubt that if subcommand name is `import`, it will conflict with python reserved word `import`.

**Comment by amoffat** [comment]
`my_import = sh.Command("import")`

**Comment by amoffat** [comment]
Sorry I just skimmed the original issue.  Try this

```python
from sh import sqoop
sqoop("import")
```

It should be equivalent to `sh.import()`

**Comment by starplanet** [comment]
Thanks for your response. I find that it' just a python problem. You can't define the methods named after `import`, `exec`  and so on which are python reserved words in class. So it's not a sh problem. 

Thanks.
