### ISSUE TITLE
_cwd doesn't work with _fg

### ISSUE THREAD

**Issue by amoffat** [amoffat/sh#330]
And I'm sure a few more useful options don't work with `_fg` either.

**Comment by amoffat** [comment]
cwd supported with fg

**Comment by j-vizcaino** [comment]
Hello,

I stumbled upon this bug today.

### Environment

* MacOS 10.12.6
* python 3.4.4
* sh 1.12.14

### How to reproduce

```
import sh

sh.ls(_cwd='/', _fg=True)
```

It prints the result of `ls` run is the current working dir, not `/`

**Comment by akhy** [comment]
@amoffat @j-vizcaino I can reproduce it as well

- macOS 10.12.5 and Debian Jessie
- python 2.7.14 and 3.5.2
- sh==1.12.14

```py
from sh import pwd, mkdir

mkdir('-p', 'test')

pwd(_fg=True)  # output: /app (CORRECT)
pwd(_cwd='test', _fg=True)  # output: /app (WRONG, should be /app/test)
print(pwd(_cwd='test'))  # output: /app/test (CORRECT)
```

**Comment by ioben** [comment]
Also ran into this issue. Hopefully @amoffat can chime in as to whether it's a regression or intended behavior (sounds like the former?)

**Comment by amoffat** [comment]
Seems like a regression, confirmed on Ubuntu
