### ISSUE TITLE
out and err callbacks

### ISSUE THREAD

**Issue by retr0h** [amoffat/sh#333]
Is it possible to prevent the callbacks from running when an error occurs?  The beautify of the callbacks, is the ability to print output as it occurs vs printing stdout once the command completes.

However, that prevents me from wrapping a module with a try and squelching stderr/err.

For example.  The following will prevent the error from getting displayed.

```
try:
    sh.ls('/invalid')
except sh.ErrorReturnCode:
    pass
```

However, as soon as I implement callbacks I get output regardless.

```
from __future__ import print_function

import sh


def print_it(msg):
    print('{}'.format(msg.rstrip()))


try:
    sh.ls('/invalid', _out=print_it, _err=print_it)
except sh.ErrorReturnCode:
    pass
```

I'm trying to determine a way in which I can selectively capture and print stdout/err.

Thanks
- @retr0h

**Comment by amoffat** [comment]
I think it's a contradiction.  Like you said, the beauty of the callback is that it receives output as the program produces it.  However, an error is only known once the program completes (by examining its exit code).  To do what you ask, the callback would have to know the exit code before it prints output, meaning the program would have terminated, which means that the callback cannot respond in real time to the output.

**Comment by retr0h** [comment]
Yeah, well stated.  Thanks for getting back to me.
