### ISSUE TITLE
sh 1.12 & Python 2.7: NameError: global name 'UnsupportedOperation' is not defined

### ISSUE THREAD

**Issue by georgevreilly** [amoffat/sh#335]
Several of our builds are failing with errors like this:
```
  File "/home/rundeck/job/engineering/5625/.env/local/lib/python2.7/site-packages/sh.py", line 621, in __init__
    self.call_args, pipe, process_assign_lock)
  File "/home/rundeck/job/engineering/5625/.env/local/lib/python2.7/site-packages/sh.py", line 1512, in __init__
    stdout_is_tty = ob_is_tty(stdout)
  File "/home/rundeck/job/engineering/5625/.env/local/lib/python2.7/site-packages/sh.py", line 843, in ob_is_tty
    except UnsupportedOperation:
NameError: global name 'UnsupportedOperation' is not defined
```

Looking at the 1.12 code, you import `UnsupportedOperation` for Python 3, but not for Python 2.

**Comment by amoffat** [comment]
@georgevreilly `UnsupportedOperation` doesn't exist in py2 unfortunately.  But it is masking the real error, which would be an uncaught exception from calling `ob.fileno()`.  What are you passing in for `_out`?

**Comment by amoffat** [comment]
Just to clarify my last question, it seems like your builds are passing in an object for `_out` that looks like it has a `.fileno()` method, but calling it raises an exception.  It's probably not `StringIO` and `cStringIO`, because `getattr(ob, "fileno", None)` returns `None` for instances of both of those types, so it would never get to the part where we call `ob.fileno()`.  So it must be some other weird kind of object.

**Comment by georgevreilly** [comment]
`UnsupportedOperation` is supported in [Python 2.7.12](https://docs.python.org/2/library/io.html#io.UnsupportedOperation). I don't know when it was introduced to Python 2.x.
```
georgevreilly@george-mb16:~/src/cookbrite/flyingcloud$ (master) python
Python 2.7.12 (default, Oct 11 2016, 05:20:59)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.version
'2.7.12 (default, Oct 11 2016, 05:20:59) \n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]'
>>> import io
>>> dir(io.UnsupportedOperation)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__getslice__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', '__weakref__', 'args', 'errno', 'filename', 'message', 'strerror']
```

Here's the code that produced the above partial stack trace:
```python
def run_command(path, *args, **kwargs):
    with io.BytesIO() as output:
        cmd = sh.Command(path)
        cmd(*args, _out=output, **kwargs)
        return output.getvalue()
```

**Comment by amoffat** [comment]
Oh, interesting.  It appears that `io` exists as far back as python2.6, but sh's support of `io.BytesIO` was only incidental (favoring `cStringIO.cStringIO` and `StringIO.StringIO` instead).  1.12.0 broke that support

I've added support for python2 `io.StringIO()`.  The new version is live on pip as version 1.12.2.  Give it a try and close the issue if that resolves it for you.

btw I see you're in Seattle.  I'm moving there early next year.  Any recommendations on good neighborhoods and good places to work?

**Comment by georgevreilly** [comment]
Yes, 1.12.2 seems to work. Thanks for the fix.

I'll email you about Seattle.
