### ISSUE TITLE
Regression: file descriptor leaked

### ISSUE THREAD

**Issue by tronical** [amoffat/sh#336]
Hi,

Since version 1.12.0 there exists a leak in file descriptors. That leak was not present in 1.11 but it's there in >= 1.12 and quite easy to reproduce for example in ipython:

    from sh import ls
    ls()
    ls()
    ls()
    ls()

Repeat the ls() calls a few times and observe how for each invocation a (pipe) file descriptor is leaked in /proc/$pid of ipython/fd

(and it's not related to gc, as "import gc" followed by "gc.collect()" doesn't close any descriptors)

git bisect points to commit dd571459719473a00c143eb37b7661207c5ff9ef as the one that introduces the regression/leak. Simple program used for git bisect run:

    from sh import echo, ls
    import os
    import sys
    
    for i in range(1, 100):
        echo()
    
    count = len(ls("-1", "/proc/%s/fd" % os.getpid()).split())
    print(count)
    if count < 100:
        sys.exit(0)
    else:
        sys.exit(1)

**Comment by tronical** [comment]
Fix submitted in PR https://github.com/amoffat/sh/pull/337

**Comment by amoffat** [comment]
Great work.  1.12.3 is live with your fix.  How did you detect the bug?  I hope it wasn't that your system ran out of file descriptors :fearful:

**Comment by tronical** [comment]
We've had a Python process that powers our CI system itself run into problems. It is using sh and started throwing exceptions in sh on the use of select() with FDs > 1024. That's when we figured there is a leak, it shouldn't have so many files open.

The use of select() in sh is still a problem for processes with lots of open files,  but that's for another day :)

Thanks for the quick merge!
