### ISSUE TITLE
No such file or directory: 'requirements-dev.txt'

### ISSUE THREAD

**Issue by frankgould** [amoffat/sh#345]
I was following the install instructions and tried the following command:  pip install -r requirements-dev.txt. Results are in subject line above. I searched C: and returned file not found. I am trying to restore my kivy interpreter and continue to get failure on 'from kivy.app import app.' Not sure how to resolve these issues.

Update: I also retrieved this error from the pip.log:
ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

When I go to pbs, it says to install sh.py.

**Comment by amoffat** [comment]
if you're trying to install sh, you don't need the sh developer instructions, just do `pip install sh`

if you're on windows, do `pip install pbs`  but keep in mind that pbs is unmaintained
