### ISSUE TITLE
Add support for old-style `-option` options

### ISSUE THREAD

**Issue by Lucretiel** [amoffat/sh#354]
Some commands– including many older programs, and most programs using [Golang's builtin argument parser](https://golang.org/pkg/flag/)– use a single dash for long arguments, instead of two. I propose adding a new command special flag, `_single`, which would allow these commands to be supported. For example:

```
sh.echo(_single=True, test=True)  # prints "-test"
```

**Comment by amoffat** [comment]
I think you're looking for the `_long_prefix` option http://amoffat.github.io/sh/sections/special_arguments.html#long-prefix

**Comment by Lucretiel** [comment]
Ah, indeed! Ty. Does sh not do any collapsing of single letter options?
Like, does it turn -a -b -c into -abc?

**Comment by amoffat** [comment]
No, you'll have to handle that in your program
