### ISSUE TITLE
.wait() causes 100% cpu load

### ISSUE THREAD

**Issue by rbonthond** [amoffat/sh#357]
the following script seems to cause the cpu load to go to 100%, not sure why though...

```
#!/usr/bin/env python3
import sh
import random
r = list(range(10,20))
random.shuffle(r)
for i in r:
    p = sh.sleep(i, _bg=True)
    p.wait()
```

**Comment by amoffat** [comment]
Your script doesn't really make much sense, but older versions of sh suffered from high cpu on waiting.  Based on the other issue you opened and this one, I think you are using an older version of sh https://github.com/amoffat/sh/blob/master/CHANGELOG.md#1125---120116

**Comment by rbonthond** [comment]
I've upgrade from 1.12.0 to 1.12.9 and the issue went away, thanks!
