### ISSUE TITLE
Changelog entry missing for 1.11

### ISSUE THREAD

**Issue by jakirkham** [amoffat/sh#359]
Not sure why, but the changelog seems to skip right over 1.11. Maybe I missed it, or it's out of place, or it got deleted accidentally, but is still in git history. 😕 

ref: https://github.com/amoffat/sh/blob/268c191a73a3529a7d704f9e7339316291e64b4c/CHANGELOG.md#1120---112116
ref: https://github.com/amoffat/sh/blob/268c191a73a3529a7d704f9e7339316291e64b4c/CHANGELOG.md#110---123014

**Comment by amoffat** [comment]
Hm..not sure what happened to it.  Must have gotten skipped over.  Not much I can do if it's not in the history.

**Comment by jakirkham** [comment]
Why not just edit the file? 😕

**Comment by amoffat** [comment]
How easy do you think it is to do?  How many people will it benefit? :)
