### ISSUE TITLE
Buffered output

### ISSUE THREAD

**Issue by AndreaCrotti** [amoffat/sh#360]
I can't seem to get the stdout to be unbuffered.

I just tried to do
` sh.command('some_command', _out_bufsize=0)`

which I thought was enough from the docs, but it's still buffering.
I also tried to set `export PYTHONUNBUFFERED=1` but that also doesn't work.
Any ideas of what I'm missing?

Thanks

**Comment by amoffat** [comment]
What's your actual full command?

**Comment by AndreaCrotti** [comment]
It has the same issue with many commands, for example here was a pip install.

`sh.pip('install', '-r', 'requirements.txt', _out_bufsize=0)`
for example

**Comment by amoffat** [comment]
You will only get the output when a command finishes.  Are you using `_iter` or an `_out` callback to see the output incrementally?

```python
for line in sh.pip('install', '-r', 'requirements.txt', _out_bufsize=0, _iter=True):
    print(line)
```

**Comment by amoffat** [comment]
Just to clarify the above snippet...using `_out_bufsize=0` combined with `_iter=True` will output character-by-character if the source command is indeed unbuffered.  If you just want line by line, leave `_out_bufsize=1` (the default) when you use `_iter=True`

This stuff is covered in detail in the docs http://amoffat.github.io/sh/sections/asynchronous_execution.html

**Comment by AndreaCrotti** [comment]
Ok thanks I ended up with something like this

    def sh_verbose(cmd: str, *args, **kwargs):
        proc = getattr(sh, cmd)(*args, **kwargs, _iter=True)
        for line in proc:
            logger.info('[%s] => %s', cmd, line)
    
        return proc


which it's a good default for all the commands I have to execute really.
Seems to work well as expected, can you see any potential issue with something like that?

**Comment by AndreaCrotti** [comment]
This still doesn't work with commands like *docker pull* sadly since they are doing some extra magic behind the back, for example:

In [7]: sh_verbose('docker', 'pull', 'mysql:5.7')

is that possible to show that correctly at all of it doesn't really make sense?

**Comment by amoffat** [comment]
I'm not familiar with using sh and docker, so you'll have to experiment on your own.
