### ISSUE TITLE
Dynamically sending data to a stdin

### ISSUE THREAD

**Issue by Taronyuu** [amoffat/sh#363]
Hi guys,

I'm trying to use Python and this package to manage a few long running processes. While running these processes there needs to be send some data/commands to the process. And as far as I know this isn't possible.

I know I have access to stdin when there is a log output (e.g. https://amoffat.github.io/sh/tutorials/interacting_with_processes.html), I also know you can add the `_in` argument (https://amoffat.github.io/sh/sections/stdin.html#stdin) however both aren't what I'm trying to do. The first will only execute a command when there is output, and that isn't guaranteed. And the later can't be dynamically set. It will only run when creating the process. 

As far as I know there isn't anything in the docs that explains how (if?) this can be done, so I'm hoping on some support here. 😄

**Comment by amoffat** [comment]
You can pass a [queue.Queue](https://docs.python.org/2/library/queue.html#Queue.Queue) to `_in`, then you can populate it with whatever you like, whenever you like.  Does that solve your problem?

**Comment by Taronyuu** [comment]
Yes it did, al I needed.

Thank you!

**Comment by Asuranceturix** [comment]
How does the producer signal the end of input to the consumer?

**Comment by lgrahl** [comment]
@Asuranceturix Put `None` into the queue. See #419

**Comment by Asuranceturix** [comment]
@Igrahl Thanks a lot!
