### ISSUE TITLE
Duplicate FAQ entries for running program with dashes

### ISSUE THREAD

**Issue by samueldg** [amoffat/sh#368]
The following entries are pretty much duplicates (same problem, same example):

- [How do I run a program with dashes in its name?](http://amoffat.github.io/sh/sections/faq.html#how-do-i-run-a-program-with-dashes-in-its-name)
- [How do I execute a program with a dash in its name?](http://amoffat.github.io/sh/sections/faq.html#how-do-i-execute-a-program-with-a-dash-in-its-name)

**Comment by amoffat** [comment]
Fixed, thanks for reporting
