### ISSUE TITLE
How do I create a dry-run?

### ISSUE THREAD

**Issue by thescouser89** [amoffat/sh#370]
I'd like to know if there are any ways to simulate the execution of the program to run with `sh`?
What I mean is that `sh` prints out the command it is going to run, but doesn't actually execute it.

**Comment by amoffat** [comment]
You can print the path of the command without running it

```python
import sh
print(sh.ls)
```

You can also partially apply arguments to a command and print the result

```python
import sh
my_ls = sh.ls.bake("-a", "-l", "--colors")
print(my_ls)
```

But there is no real dry-run feature.  Are you trying to debug arguments?

**Comment by thescouser89** [comment]
Ah the solution you provided works perfectly! Thanks @amoffat for the fast reply! Greatly appreciated!

And thank *you* for creating `sh`. It is amazing! 😃

**Comment by carlwgeorge** [comment]
@amoffat On a related note, what would you think about adding a special kwarg to print the command before execution?  As you noted above it can be done with baking, but it would be nice to simplify it.

Current:
```
cmd = sh.echo.bake('hello')
print(cmd)
cmd()
```

Proposed:
```
sh.echo('hello', _print_prior=True)
```

**Comment by amoffat** [comment]
@carlwgeorge I like the idea of making command debugging more clear.  A good place to expand on this would be the logging functionality that is *somewhat* already there in sh, but lacking, and not very well documented:

```python
import logging
import sh

logging.basicConfig(level=logging.INFO)
sh.echo("hello")
```

The output definitely needs some love (seeing duplicate completion messages currently), but I see this as the place to expand on for better print debugging going forward:
```
INFO:sh.command:<Command u'/bin/echo hello'>: starting process
INFO:sh.command:<Command u'/bin/echo hello', pid 30646>: process started
INFO:sh.command:<Command u'/bin/echo hello', pid 30646>: process completed
INFO:sh.command:<Command u'/bin/echo hello', pid 30646>: process completed
INFO:sh.command:<Command u'/bin/echo hello', pid 30646>: process completed
hello
```
