### ISSUE TITLE
How do I use run "sudo" on remote host with ssh

### ISSUE THREAD

**Issue by wingerted** [amoffat/sh#371]
I try this `sh.ssh('winger@winger01', 'sudo df', _tty_in=True)`
But I get `sudo: no tty present and no askpass program specified`
How can I do that ?

**Comment by amoffat** [comment]
try this
```python
sh.ssh("winger@winger01", "sudo -S df", _in=password+"\n")
```

**Comment by wingerted** [comment]
That's work ! Thanks a lot
