### ISSUE TITLE
Commands such as mkfs.ext4 cannot work as '.' is also namespace separator

### ISSUE THREAD

**Issue by Cheaterman** [amoffat/sh#376]
Hi everyone, I hope you're all doing goodie ^__^

I noticed commands like mkfs.ext4 can't be called as sh.mkfs.ext4, however getattr(sh, 'mkfs.ext4') works so I suspect you can do something about it.

Thanks in advance! sh is awesome! ^__^

**Comment by amoffat** [comment]
Thanks @Cheaterman, it's a known issue.  If you have a command with non-alphanumerical characters, the canonical way is to use the `sh.Command` class:

```python
import sh
mkfsext4 = sh.Command("mkfs.ext4")
mkfsext4() # run it
```

I'll add something to the FAQ to cover this topic specifically

**Comment by Cheaterman** [comment]
Thanks a lot for clarifying the canon way to do this, as I indeed expected it to be a known issue. Thanks a LOT for the awesome library by the way, and for adding this to the FAQ/documentation :-)
