### ISSUE TITLE
perfomance problems in python-for-android since 1.12.5

### ISSUE THREAD

**Issue by bobatsar** [amoffat/sh#378]
I am using python-for-android and since sh 1.12.5 I see a delay of 1 second to every call of sh.

The usage of sh can be seen in https://github.com/kivy/python-for-android/blob/master/pythonforandroid/logger.py#L141

typical usages are sh.cp or sh.rm

With a git bisect I figured out that the following commit introduced the performance problems.

commit a500762f0915b2a3877a136c3c3d81f11dfdc95b
Author: Andrew Moffat <andrew.robert.moffat@gmail.com>
Date:   Thu Dec 1 02:27:00 2016 -0600

    use a quit event to reduce sleeping/spinning in threads

**Comment by amoffat** [comment]
Thanks for reporting and finding the regression.  I'm able to reproduce the issue when using `_iter`, which is how `shprint` is working.  I'll try to dig into it soon

```python
# takes 1 second
for line in sh.ls(_iter=True): pass
```

**Comment by amoffat** [comment]
Fixed on master, version `1.12.14`
