### ISSUE TITLE
OSError: out of pty devices

### ISSUE THREAD

**Issue by amraks** [amoffat/sh#381]
I am running a pyinstaller binary in a chroot environment. The following code produces a traceback.

`grep(ps('-ef'), '[p]rovision_storage.py', _tty_in=True)`

  File "sh.py", line 1427, in __call__
  File "sh.py", line 767, in __init__
  File "sh.py", line 1780, in __init__
  File "pty.py", line 29, in openpty
  File "pty.py", line 70, in _open_terminal
OSError: out of pty devices

_tty_in set to False also produces the same traceback.

Environment: Pyinstaller binary compiled with Python 2.7.13
Compile/Runtime chroot OS: Debian Stretch

**Comment by amoffat** [comment]
Hi @amraks.  There are [2 TTY special arguments](http://amoffat.github.io/sh/sections/special_arguments.html#ttys), `_tty_in` (defaults to False) and `_tty_out` (defaults to True) .  If you set them both to False, on both commands (grep and ps), no TTY should be used at all.

If you want to globally disable your commands using TTYs, you can use [default arguments](http://amoffat.github.io/sh/sections/default_arguments.html):

```python
import sh
sh2 = sh(_tty_out=False, _tty_in=False)
from sh2 import grep, ps
```
Now `grep` and `ps` (and all future commands that you use on or import from `sh2`) will have TTY disabled.

This should solve the problem of sh not using TTYs, but it's interesting that you're not able to allocate any pty devices.  Is your environment sane?

**Comment by amraks** [comment]
Thanks @amoffat. What worked for me was this: 

grep(ps('-ef', _tty_out=False), '[p]rovision_storage.py', _tty_out=False)

You are correct, something is wrong with the compile time chroot environment. No pty devices available.

**Comment by richarson** [comment]
Sorry for hijacking the thread, but a tip to @amraks , if you build inside a chroot remember to:
```
mount --bind /dev $CHROOT/dev
mount --bind /dev/pts $CHROOT/dev/pts
mount --bind /sys $CHROOT/sys
mount --bind /proc $CHROOT/proc
```

Or follow http://www.linuxfromscratch.org/lfs/view/stable/chapter06/kernfs.html, which might be more apropriate

-- 
richarson, Former LinuxFromScratch user :)

**Comment by AMzhanghan** [comment]
> [``](

- 

- [ ] url

)

**Comment by dtenenba** [comment]
FYI, I get this same error when running `sh` in an AWS Lambda function. The suggested fix seems to work.

**Comment by jacobisaliveandwell** [comment]
@dtenenba do you have a working example? try the suggested workaround in lambda results in `FileNotFound` for `/dev/fd`
