### ISSUE TITLE
travis-ci broken on pypy3 and python3.2

### ISSUE THREAD

**Issue by amoffat** [amoffat/sh#385]
If anyone wants to be a buddy and see if they can hammer this one out, it would be a big help.  Out of the blue, a few job environments are failing.  It seems to be related to pip, but the pypy3 build is interesting, because it shouldn't be using a broken pip, but it is:

https://travis-ci.org/amoffat/sh/jobs/232286260
https://travis-ci.org/amoffat/sh/jobs/232286255

**Comment by Daniel599** [comment]
Hi, do you still need help with that?
looking at your travis now, it seems fine, or am I missing something?

**Comment by amoffat** [comment]
I just restarted those individual jobs (for pypy3 and python3.2) and they're still failing.  What's more is now `pypy` environment is also failing https://travis-ci.org/amoffat/sh/jobs/255932704

**Comment by amoffat** [comment]
Ah..looks like related to naming convention... https://github.com/travis-ci/travis-ci/issues/6865#issuecomment-307187192

**Comment by Daniel599** [comment]
wow you caught that much faster then I ever could hehe,
anyway, if there is anything else I can help with, please let me know, I would like to try to contribute to your module.
