### ISSUE TITLE
How to mock customized command instantiate from `sh.Command`

### ISSUE THREAD

**Issue by jkryanchou** [amoffat/sh#387]
I have instantiated a command from  Class `sh.Command` to wrap my own program executable. I want to mock up the command in unittest, While it seems not work correctly. I have read the documentations. Found nothing significant on mocking `sh.Command`, Is there any good suggestions on it? Here are my code snippet.
 
`foo.py`

```
import sh

foo_std_args = ["-p", "80", "-c", "200"]

def execute_foo():
       foo_command = sh.Command("foo").bake(*foo_std_args)
       foo_command(doo=1, zoo=2)
```

UnitTest

`test_foo.py`

```
import mock
import patch

import sh

from foo import execute_foo

class TestFooCommand(object):

      @patch.object(sh, "RunningCommand")
      def test_execute_foo_should_succeed(self, mock_running_command):
             execute_foo()
            `how to assert command args foo=1, zoo=2?`
```

Is there any good way to mock and test the `foo_command`?

**Comment by jkryanchou** [comment]
I though the repo-maintainer should give more examples on sh unittests which could do helpful to our TDD on `sh`.

**Comment by amoffat** [comment]
Why are you mocking `RunningCommand` and not `Command` ?

**Comment by jkryanchou** [comment]
@amoffat I also have tried to mock `Command` While it seems doesn`t work correctly yet. I have got insight into source-code, it has `__call__` Could you provide some examples on mock? `sh` API were so cool. I am so willing to develop in TDD with  it.

**Comment by jkryanchou** [comment]
Any better way to patch the `Command` for mocking or stub? Sometimes I don't want to run my program (executable) in real. Just only assert the final cmds_str which was built by `sh` below

```
       foo_std_args = ["-p", "80", "-c", "200"]

       foo_command = sh.Command("foo").bake(*foo_std_args)
       foo_command(doo=1, zoo=2)
      
       assert  foo_command(doo=1, zoo=2).__str__() == "foo --doc=1 --zoo=2 -p 80 -c 200"      
```
It would be helpful for me to validate and test whether my commands builder ran correctly.

**Comment by amoffat** [comment]
I understand.  If it's not working with `patch`, I think it might be a bug with sh.  If you really want to test it, before the bug is fixed, wrap your sh call in another function, and patch that function.  In your example, that would mean to patch `execute_foo`.  I will need to fix the bug for real patching to work.

**Comment by jkryanchou** [comment]
@amoffat Yes, This is the only way I could certainly patch the method. Thanks all the same. I wish it could be better and better.

**Comment by amoffat** [comment]
Sounds good @jkryanchou.  I will leave this issue open until it is made better

**Comment by amoffat** [comment]
@jkryanchou I was able to get testing working with `unittest.mock.patch` and I added an FAQ entry for it here http://amoffat.github.io/sh/sections/faq.html#how-do-i-patch-sh-in-my-tests

Does it work with your patch module?

**Comment by jkryanchou** [comment]
@amoffat Awesome, While I couldn't validate whether my full command string was correct follow your FAQ. Take a look my code-snippet 
```
# -*- coding: utf-8 -*-

import unittest
from unittest.mock import patch
import sh


def foo_head_something(filepath):
    head = sh.Command("head").bake(["-n", '-1'])
    return head(filepath)


class TestFooHeadCmd(unittest.TestCase):

    @patch.object(sh.Command, "bake")
    def test_foo_head_something(self, mock_bake):
        mock_bake.return_value = "expected_content"
        assert foo_head_something("./barfile") == "expected_content"
        #  Adding an `full_cmds_str` property to assert ?
        assert mock_bake.full_cmds_str == "head -n -1 ./barfile"
```
It's better to add an instance property `full_cmds_str`  to get assert work.
Or `get_full_cmds_str()` on Command.

**Comment by amoffat** [comment]
I'm going to call this "good enough" and close. The current docs seem to cover basic patching correctly.
