### ISSUE TITLE
Slow speed on _out to a file

### ISSUE THREAD

**Issue by Cediddi** [amoffat/sh#392]
Hi,
We're using sh 1.11 because of 1.12 breaks most of our code.

Our workflow is like this.
- We call a app and tell it the input file (approx 25G)
- That app outputs to stdout (unfortunately)
- We redirect output to a file (approx 40G)

In this case, bash finished 3-4 times faster. For applications that support outputting to a file, we use that but for applications that output to stdout only, we're stuck with sh's _out option.

We usually don't use piping and this is an issue of output redirection

**Comment by amoffat** [comment]
The breaking issue is separate from the speed issue?

**Comment by Cediddi** [comment]
Yes. I stated that 1.12 breaks our code because if you fixed such a problem in new release, we'd invest in upgrading to 1.12.-

**Comment by amoffat** [comment]
I can certainly look into the speed problem, but I'm still failing to see what is broken.  Unless I am misunderstanding you, you are saying the fact that it is slower than bash is considered broken?

**Comment by Cediddi** [comment]
Using > in bash is faster than using _out in sh
That's what I'm saying. I'm working with relatively big files (10-60GB) and the redirection overhead is very visible.

**Comment by amoffat** [comment]
And 1.11 is much faster than 1.12 on the large data sets?  Is it still slower than bash?

**Comment by Cediddi** [comment]
I'm sorry for being too late to reply. But here's my output, fresh from ipython.

  !time gzip --decompress --stdout infile.txt.gz > outfile.txt.bash 
  gzip --decompress --stdout infile.txt.gz  41,68s user 4,14s system 32% cpu 2:22,05 total

  %time sh.gzip("--decompress", "--stdout", "infile.txt.gz", _out="outfile.txt.sh")
  CPU times: user 5min 10s, sys: 2min 4s, total: 7min 15s
  Wall time: 9min 44s


As visible, there's 5 minute overhead. I'll try sh 1.12 asap.

**Comment by Cediddi** [comment]
Hi, I did something wicked. I wrote a bash script that still supports sh's argument escaping and does redirection on bash. Here's the code of proxy.sh

```
#!/usr/bin/env bash
set -e
TOTAL_LEN=${#@}
EXP_LEN=`expr ${TOTAL_LEN} - 2`
"${@:1:${EXP_LEN}}">"${@:${TOTAL_LEN}}"
```

I also changed all my sh callbacks from this;
```
sh.gzip("--decompress", "--stdout", "infile.txt.gz", _out="outfile.txt")
```
to that;
```
sh_proxy = sh.Command("./proxy.sh")
sh_proxy.gzip("--decompress", "--stdout", "infile.txt.gz", ">", "outfile.txt")
```
Yes I could totally omit ">" in argument list but, to be honest, this is more readable.

With this, there's no overhead.

**Comment by amoffat** [comment]
https://github.com/amoffat/sh/commit/56e18cff5a82c7a3253a0dfe8792a44ae7050aae should improve this. We will now `os.dup2()` a file-like object to the process's `_out` so writing to it will have native performance. This will ship with the next release.
