### ISSUE TITLE
ssh callback example is broken under v1.12

### ISSUE THREAD

**Issue by acceleratorguy** [amoffat/sh#393]
The ssh example, found at http://amoffat.github.io/sh/tutorials/interacting_with_processes.html#, works under v1.11 but doesn't work under v1.12. 
Symptoms:
The the callback function, ssh_interact, is never called.

Environment:
Python 2.7.5
sh (1.12.14)
Underlying OS: Redhat 7.3 derivative.

**Comment by amoffat** [comment]
Thanks for bringing this to my attention @acceleratorguy.  I will look into it

**Comment by tkossak** [comment]
same problem here (sh 1.12.14, Python 3.6.1, Linux Mint)

**Comment by BingmingWong** [comment]
> Thanks for bringing this to my attention @acceleratorguy. I will look into it

I have the same problem（Python 2.7.5 and Python 3.7.1, CentOS 7.2）, did you solve it?

**Comment by amoffat** [comment]
This is fixed, along with the documentation, in the next release, closing.
