### ISSUE TITLE
Importing sh excepts on further imports via Python C-API

### ISSUE THREAD

**Issue by cheriff** [amoffat/sh#398]
I've found that when writing a C Application against libpython that:

1. Use PyImport_ImportModule to import (directly or indirectly) sh
    * This will insert a ModuleImporterFromVariables in sys.meta_path
2. Try use PyImport_ImportModule to import anything else (say, datetime)

This results in:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sh.py", line 3421, in find_module
    while in_importlib(parent_frame):
  File "/usr/lib/python2.7/site-packages/sh.py", line 3368, in in_importlib
    return frame.f_code.co_filename == "<frozen importlib._bootstrap>"
AttributeError: 'NoneType' object has no attribute 'f_code'
```

After digging, it seems that find_module() is not happy when parent_frame is None, as it appears to be when  importing via the API. I found that having that return None in this case causes things to work, but cannot be sure if this doesn't have side-effects should anyone be using the "fancy importer"

---

In this situation, since I can't easily change either sh itself, or dependancies that pull it in I do have a workaround which I'm using for now:

```
    {   // begin workaround
        PyObject *sys = PyImport_ImportModule("sys");
        PyObject *meta_path = PyObject_GetAttrString(sys, "meta_path");
        PyObject *sh = PyImport_ImportModule("sh");
        PyObject* pop_ret = PyObject_CallMethod(meta_path, "pop", NULL);
        (void)pop_ret;
        (void)sh;
    }
```

I now can import my other stuff since there's no extra importers in the chain, and since sh is already imported, one won't be re-added. 
I understand this may break uses of sh in any module, particularly if anything uses the `my_sh = sh(_foo=bar); from my_sh import something` pattern which for now seems not to be a deal breaker but feels a bit fragile going forward.

---

Alternatively, if there's anything extra I need to do from the C side to set things up such that `inspect.currentframe().f_back` returns something sensible to also avoid this, I'd be happy to try that too.

**Comment by cheriff** [comment]
Repro code, with optional workaround:

```
12:10:37 [davidm@krill ~]$ cat importsh.c
#include <Python.h>
#include <stdio.h>

void workaround(void)
{
    PyObject *sys = PyImport_ImportModule("sys");
    PyObject *meta_path = PyObject_GetAttrString(sys, "meta_path");
    PyObject *sh = PyImport_ImportModule("sh");
    PyObject* pop_ret = PyObject_CallMethod(meta_path, "pop", NULL);
    (void)pop_ret;
    (void)sh;
}

int
main(int argc, char *argv[])
{

    Py_Initialize();

    // Uncomment to be able to import datetime!
    // workaround();

    PyObject *sh = PyImport_ImportModule("sh");
    printf("have sh: %p\n", sh);
    if (!sh) PyErr_Print();

    PyObject *datetime = PyImport_ImportModule("datetime");
    printf("have datetime: %p\n", datetime);
    if (!datetime) PyErr_Print();

    return 0;
}
12:10:27 [davidm@krill ~]$ gcc  $(python-config --cflags --ldflags) importsh.c -o importsh
12:10:37 [davidm@krill ~]$ ./importsh
have sh: 0x18a2590
have datetime: (nil)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sh.py", line 3433, in find_module
    while in_importlib(parent_frame):
  File "/usr/lib/python2.7/site-packages/sh.py", line 3381, in in_importlib
    return frame.f_code.co_filename == "<frozen importlib._bootstrap>"
AttributeError: 'NoneType' object has no attribute 'f_code'
```

**Comment by amoffat** [comment]
Interesting, thanks for reporting.  The `ModuleImporterFromVariables` class may be a bit too magical I think (even for sh).  Your workaround seems good.  If you can whip up a quick PR addressing just a temporary patch on the sh code that breaks in your case, I'll merge it in.

Long term, I think we will refactor the magic importing code.

**Comment by davidm-mm** [comment]
OK, done. (apologies for switching accounts)
Looks like Travis was unhappy with one check, but I claim pypy's issues with '-.tar.bz2' are unrelated to the patch in question :)

**Comment by thehcma** [comment]
I was also just hit by this - the proposed fix works for me too.

Are we planning to merge this?

**Comment by thehcma** [comment]
@amoffat: are you planning to release @davidm-mm's patch?

**Comment by amoffat** [comment]
Yes.  The release cycle for sh is very slow, but all work is appreciated and approved PRs do make it in.  If you find the cycle is too slow, please maintain a fork to use until it is merged into the main.

**Comment by Cheaterman** [comment]
Doesn't work here. I'm getting a relatively similar issue when using sh inside a Flask application run with gevent, all inside a docker container. For reference:
`web_1  | *** running gevent loop engine [addr:0x60f9e0] ***
web_1  | Traceback (most recent call last):
web_1  |   File "<frozen importlib._bootstrap>", line 888, in _find_spec
web_1  | AttributeError: 'ModuleImporterFromVariables' object has no attribute 'find_spec'
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 890, in _find_spec
web_1  |   File "<frozen importlib._bootstrap>", line 864, in _find_spec_legacy
web_1  |   File "/env/lib/python3.6/site-packages/sh.py", line 3440, in find_module
web_1  |     while in_importlib(parent_frame):
web_1  |   File "/env/lib/python3.6/site-packages/sh.py", line 3381, in in_importlib
web_1  |     return frame.f_code.co_filename == "<frozen importlib._bootstrap>"
web_1  | AttributeError: 'NoneType' object has no attribute 'f_code'
`

I proposed my own workaround here: https://github.com/amoffat/sh/pull/494

**Comment by amoffat** [comment]
https://github.com/amoffat/sh/pull/494 will go out with the next release. Thanks for reporting.
