### ISSUE TITLE
It's better if return a python iter object (list or dict) when run some command.

### ISSUE THREAD

**Issue by zaazbb** [amoffat/sh#401]
if return a  python iter, list or dict,  so, we can get some result easier.
eg:
run ifconfig,   and only get the ip in wlan0.

**Comment by amoffat** [comment]
http://amoffat.github.io/sh/sections/special_arguments.html#iter ?

**Comment by zaazbb** [comment]
i want return the common command results  as list or dict, 
for example, i want get the ip like this:

>import sh
eth1 = sh.ifconfig(interface='eth1')
print(eth1[inet addr']) \# print: 192.168.40.1

and the raw ifconfig result as below.
>ifconfg
eth1      Link encap:Ethernet  HWaddr 00:50:56:c0:00:01
          inet addr:192.168.40.1  Bcast:192.168.40.255  Mask:255.255.255.0
          inet6 addr: fe80::b105:e16f:4b5f:4fd9/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by zaazbb** [comment]
so i do not need use regular expression to match the result. 
just get the result i want from the dict.

**Comment by amoffat** [comment]
sh does not parse the output for you because it cannot know what your output will be.  sh simply runs processes for you.  it's up to you to parse out the information that you want.
