### ISSUE TITLE
ANSI color weirdness with sh.git("log")

### ISSUE THREAD

**Issue by paul-hammant** [amoffat/sh#402]
I can see ANSI color codes, but didn't expect to, for:

```
log = sh.git("log", "--pretty=oneline", "--no-color").stdout
print(log)
```

verification (Bash):

```
git log --pretty=oneline
# and 
git log --pretty=oneline --no-color
```

Seems Py.sh handing "--no-color" to git is having no effect :-(

**Comment by paul-hammant** [comment]
Ignore me, `_tty_out=False` was needed.

**Comment by KarateSnowMachine** [comment]
Hello, I recently ran across this but was also able to find the note in the docs about using `_tty_out=False`. And I totally understand that some programs detect a TTY and want to output colors as a result, but why does it still do so even when I explicitly ask for `--no-color` in my command? The part I'm finding extra confusing is that when I request `--no-color` in my terminal, git respects my choice even though I do have a TTY.

**Comment by ecederstrand** [comment]
I think this question is better directed at git. They would know in which circumstances they output colors.
