### ISSUE TITLE
Pass file descriptors to subprocess

### ISSUE THREAD

**Issue by Asuranceturix** [amoffat/sh#403]
Hi, I am trying to pass open file descriptors to my sh commands, but apparently that does not work (at least under Python 3). The Python library `subprocess` has an option to enable this behaviour, but I have been unable to find its equivalent in `sh`, that I would rather use.

I have prepared a fairly minimal example illustrating the issue:
```python
import sh
import os
import subprocess

p = os.pipe()
os.write(p[1], b"asdfasdf\n")
os.close(p[1])
c = sh.bash(["-c", "read -u {} foo; echo $foo".format(p[0])])
os.close(p[0])
print("SH.\n  stdout: {}\n  stderr: {}".format(c.stdout, c.stderr))

p = os.pipe()
os.write(p[1], b"asdfasdf\n")
os.close(p[1])
c = subprocess.Popen(["bash", "-c", "read -u {} foo; echo $foo".format(p[0])], stdout=subprocess.PIPE, stderr=subprocess.PIPE, pass_fds=[p[0]])
out, err = c.communicate()
os.close(p[0])
print("Subprocess.\n  stdout: {}\n  stderr: {}".format(out, err))
```

**Comment by amoffat** [comment]
Right, this is because sh closes all open fds in the child process after fork.  `subprocess` does a similar thing, but `pass_fds` must leave those fds open.  Unfortunately there is no option like that in sh, so if you want to read from an fd, you have to bind it to stdin:

`c = sh.bash("-c", "read foo; echo $foo", _in=p[0])`

**Comment by Asuranceturix** [comment]
Any chance to get such an option in a future release? My previous example was admittedly contrived, but there are reasonable use cases that demand being able to use other file descriptors in addition to standard input, such as securely communicating a secret passphrase  to applications such as gpg or openssl while reading actual cleartext from standard input:

```python
passphrase = b"foobar"
keypipe = os.pipe()
os.write(keypipe[1], passphrase + b'\n')
os.close(keypipe[1])

cleartext = b"secret message"

argv = ['gpg', '--passphrase-fd', str(keypipe[0]), '-q', '--batch', '--armor', '--symmetric']
p = subprocess.Popen(argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                     stderr=subprocess.PIPE, pass_fds=[keypipe[0]])
secretmessage, err = p.communicate(cleartext)
print(secretmessage)
```

**Comment by amoffat** [comment]
Yep that is reasonable @Asuranceturix.  I'll leave this issue open until it's implemented.

**Comment by amoffat** [comment]
Weirdly enough, I implemented this as a "nice to have" without remembering this issue: 58308b46fb675e33bcae3dd39b0b1fb1cb8a599e.  It will go out with the next release and should solve this problem.

**Comment by Asuranceturix** [comment]
Thanks a lot!
