### ISSUE TITLE
KeyboardInterrupt will mark process completed pre-maturely

### ISSUE THREAD

**Issue by honnix** [amoffat/sh#407]
At line https://github.com/amoffat/sh/blob/master/sh.py#L782 , this flag is set right after entering `wait` before calling command wait. In case of user hitting `ctrl-c` to interrupt the actual waiting, calling `wait` again will return immediately.

So this is what I did:

```
        q = Queue()
        p = None
        try:
            p = sh.cmd(args,
                               _bg=True,
                               _in=q,
                               _out=process_output,
                               _err=process_output,
                               _out_bufsize=0,
                               _bg_exc=False,
                               _tty_in=True)
            p.wait()
        except KeyboardInterrupt:
            if p is not None:
                p._process_completed = False # manually reset the flag
                q.put_nowait('\x03') # send ctrl-c to subprocess
                p.wait()
        finally:
            ...
```

For reasons, I can't use foreground.

Is there any better way to achieve this? This feels too hacky. Thanks!

**Comment by honnix** [comment]
To be clearer. The command I was running is `docker run`, so direct `terminate` or `signal` will not stop the container unfortunately. That's why I had to feed `^C` to stdin.

**Comment by amoffat** [comment]
It is creative, but it does feel hacky.  Unfortunately I think the nature of what you're doing needs a hack.  I can't think of a clean solution that sh could have that would help you without being super custom.  Let me know if you come up with any ideas that can generalize the problem though.

**Comment by honnix** [comment]
Yeah indeed quite hacky. It feels very uncomfortable resetting an internal variable ._process_completed. Could it be possible that a proper method be provided?

**Comment by honnix** [comment]
@amoffat Just saw [this change](https://github.com/amoffat/sh/commit/97f4f02228aae3fb7a9bcf0125d8c372402fc9aa). It is a nice feature. Unfortunately it will break this hack here. What do you think of adding a stable method to force reset completion state?

**Comment by honnix** [comment]
Or maybe we can swap these two lines? Not sure of the side effect.
```python
self._waited_until_completion = True
exit_code = self.process.wait()
```

**Comment by amoffat** [comment]
It might be as simple as doing what you suggest. I seem to remember there being a reason why it had to be set before `self.process.wait()`, but the tests are passing with that change, so it might be fine. I'm going to commit it.
