### ISSUE TITLE
how could I use '-F'  in sh.tail

### ISSUE THREAD

**Issue by kevinhuang06** [amoffat/sh#410]
my log file will rotate every 5 minutes,  '-f' will make OS unable to release file handler of that log file.
so, when i want to use '-F' param to trace this file, i found python script' memory rise up continuously , even to 1.3Gb(before i killed it). but '-f' runs cool for just using 48m memory at most.
the code blow shows how i use sh.tail
```
log_path = sys.argv[1]
for line in sh.tail("-F", log_path, _iter=True):
    pass
```

**Comment by amoffat** [comment]
Try setting [`_no_pipe`](http://amoffat.github.io/sh/sections/special_arguments.html?highlight=performance#no-pipe) as well as `_no_err`.  Re-open if the problem persists.
