### ISSUE TITLE
FAQ entry for how to get equivalent of -x behavior

### ISSUE THREAD

**Issue by jgarvin** [amoffat/sh#412]
When shell scripting one of my most common actions is to set -x in order to debug why something isn't getting invoked with the arguments I expect. I'm pretty sure this is possible with sh, I even have a code snippet that I'm pretty sure used to work but doesn't seem to anymore:
    logging.getLogger("sh.command").setLevel(logging.WARNING)

Anyway since I suspect the desire to do this is super common, it'd be nice if the FAQ described the recommended way to do it.

**Comment by deeplook** [comment]
It would be already nice to have access to the last executed command as if it was a line in a terminal, but it looks like this project was abandoned.

**Comment by amoffat** [comment]
I've added an FAQ entry that will be deployed with the next release 25862f8c454c4e1b9caf52fa861735ca3e874e3e.  You really just need to set the logger level to INFO for `sh.command`
