### ISSUE TITLE
_fg=True doesn't return the exit code

### ISSUE THREAD

**Issue by jeremysalwen** [amoffat/sh#418]
When using _fg=True, you can't get the exit code.  Instead it always returns None.

Example:

```
>>>a = sh.false(_fg=True, _ok_code=[1])
>>>print(a)
None
```

**Comment by jeremysalwen** [comment]
Also note that the alternative suggested in the docs

```
import sh
import sys
sh.your_command(_in=sys.stdin, _out=sys.stdout, _err=sys.stderr)
```

Does return the exit code, but doesn't work properly for interactive commands, e.g. ipython.

**Comment by amoffat** [comment]
Adjusted docs to include a warning about using other keyword args with `_fg`
