### ISSUE TITLE
Piping and sudo

### ISSUE THREAD

**Issue by machinekoder** [amoffat/sh#420]
Is it possible to use piping and sudo in the same instance?

For example:
```python
with sh.contrib.sudo:
        sh.dd(sh.xzcat(filepath, _piped=True), 'of=%s' % drive)
```
fails with
```
  RAN: /usr/bin/sudo -S -k /bin/dd of=/dev/sdc

  STDOUT:


  STDERR:
[sudo] password for alexander: Sorry, try again.
[sudo] password for alexander: Sorry, try again.
[sudo] password for alexander: sudo: 3 incorrect password attempts
```

because of course, we pipe to stdin

Any ideas?

**Comment by amoffat** [comment]
Your best bet would be to acquire the password before calling sudo (using getpass.getpass) and then call it like this https://amoffat.github.io/sh/sections/sudo.html#string-input

**Comment by machinekoder** [comment]
Unfortunately, this didn't work.

I ended up doing something like:
```python
    with sh.contrib.sudo:
        output = sh.sh('-c', shlex.split('"xzcat %s | dd bs=1M of=%s"' % (filepath, drive)))
```

**Comment by machinekoder** [comment]
Yeah, it's kind of nasty, but that's also the way you would do it in bash:

```bash
sudo sh -c "xzcat %s | dd bs=1M of=%s"
```
