### ISSUE TITLE
security issues as reported by 'bandit'

### ISSUE THREAD

**Issue by chinchani** [amoffat/sh#424]
[main]  INFO    profile include tests: None  
[main]  INFO    profile exclude tests: None  
[main]  INFO    cli include tests: None      
[main]  INFO    cli exclude tests: None      
[main]  INFO    running on Python 3.6.3      
Run started:2018-03-08 12:32:40.819211       

Test results:                                
>> Issue: [B606:start_process_with_no_shell] Starting a process without a shell.          
   Severity: Low   Confidence: Medium        
   Location: sh/sh.py:1400                   
1399                if call_args["env"] is None:                                          
1400                    launch = lambda: os.spawnv(os.P_WAIT, cmd[0], cmd)                
1401                else:                    

--------------------------------------------------                                        
>> Issue: [B606:start_process_with_no_shell] Starting a process without a shell.          
   Severity: Low   Confidence: Medium        
   Location: sh/sh.py:1402                   
1401                else:                    
1402                    launch = lambda: os.spawnve(os.P_WAIT, cmd[0], cmd, call_args["env"])                                                                                       
1403                                         

--------------------------------------------------                                        
>> Issue: [B606:start_process_with_no_shell] Starting a process without a shell.          
   Severity: Low   Confidence: Medium        
   Location: sh/sh.py:1960                   
1959                    if ca["env"] is None:                                             
1960                        os.execv(cmd[0], cmd)                                         
1961                    else:                

--------------------------------------------------                                        
>> Issue: [B606:start_process_with_no_shell] Starting a process without a shell.          
   Severity: Low   Confidence: Medium        
   Location: sh/sh.py:1962                   
1961                    else:                
1962                        os.execve(cmd[0], cmd, ca["env"])                            
1963    

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: sh/sh.py:3316
3315            try:
3316                exec(compile(line, "<dummy>", "single"), env, env)
3317            except SystemExit:

--------------------------------------------------
>> Issue: [B606:start_process_with_no_shell] Starting a process without a shell.
   Severity: Low   Confidence: Medium
   Location: sh/sh.py:3491
3490            cmd = [py_bin, "-W", "ignore", os.path.join(THIS_DIR, "test.py")] + args[1:]
3491            launch = lambda: os.spawnve(os.P_WAIT, cmd[0], cmd, env)
3492            return_code = launch()

--------------------------------------------------
>> Issue: [B101:assert_used] Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
   Severity: Low   Confidence: High
   Location: sh/test.py:212
211     
212                 assert len(w) == 1
213                 assert issubclass(w[-1].category, DeprecationWarning)

--------------------------------------------------
>> Issue: [B101:assert_used] Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
   Severity: Low   Confidence: High
   Location: sh/test.py:213
212                 assert len(w) == 1
213                 assert issubclass(w[-1].category, DeprecationWarning)
214     

--------------------------------------------------
>> Issue: [B108:hardcoded_tmp_directory] Probable insecure usage of temp file/directory.
   Severity: Medium   Confidence: Medium
   Location: sh/test.py:1681
1680            from os.path import realpath
1681            self.assertEqual(str(pwd(_cwd="/tmp")), realpath("/tmp") + "\n")
1682            self.assertEqual(str(pwd(_cwd="/etc")), realpath("/etc") + "\n")

--------------------------------------------------
>> Issue: [B108:hardcoded_tmp_directory] Probable insecure usage of temp file/directory.
   Severity: Medium   Confidence: Medium
   Location: sh/test.py:1681
1680            from os.path import realpath
1681            self.assertEqual(str(pwd(_cwd="/tmp")), realpath("/tmp") + "\n")
1682            self.assertEqual(str(pwd(_cwd="/etc")), realpath("/etc") + "\n")

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: sh/test.py:2647
2646                # SyntaxError upon compilation
2647                exec("from sh import *")
2648            self.assertRaises(RuntimeError, go)

--------------------------------------------------

Code scanned:
        Total lines of code: 4519
        Total lines skipped (#nosec): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0.0
                Low: 7.0
                Medium: 4.0
                High: 0.0
        Total issues (by confidence):
                Undefined: 0.0
                Low: 0.0
                Medium: 7.0
                High: 4.0
                Files skipped (0):

**Comment by amoffat** [comment]
Thanks for reporting, but considering the nature of this software, these all look fine
