### ISSUE TITLE
Terminate a background process launched with sudo?

### ISSUE THREAD

**Issue by pavja2** [amoffat/sh#434]
I get a permissions error when attempting to terminate a background process using sudo, even when I try to terminate the process (using RunningCommand.terminate()) from within a sudo context. For example:
```
    with sh.contrib.sudo(password='secret', _with=True):
        p = sh.background_task(_bg=True)
    with sh.contrib.sudo(password='secret', _with=True):
        p.terminate()
```
Gives me "PermissionError: [Errno 1] Operation not permitted". Is there a better way to kill a process that was spawned as root?

**Hackish workaround**
I can kill the process in a less cosmetic way by using the bash kill command and swallowing the resultant exception from the background process like this:
```
    with sh.contrib.sudo(password='secret', _with=True):
        p = sh.background_task(_bg=True, _bg_exc=False)
    with sh.contrib.sudo(password='secret', _with=True):
        sh.kill(p.pid)
```

**Comment by amoffat** [comment]
I can't reproduce this on the `master` and the `develop` branch.  I'm using the following code:

```python
import sh
with sh.contrib.sudo(password='secret', _with=True):
    p = sh.sleep(30, _bg=True, _bg_exc=False)

p.kill()
p.wait()
```

And it works fine. Please re-open the issue if you can reproduce the problem with real commands that I can try.
