### ISSUE TITLE
ErrorReturnCode.full_cmd behaves deceptively.

### ISSUE THREAD

**Issue by AIJIJI** [amoffat/sh#435]
(Sorry I'm not a native English speaker so please ignore grammar and typo)
***
Platfom: `CentOS 7.4.1708` + `Python 3.8.0` + `sh 1.12.14` + `Python 2.7.9`
***
After I run a command and it returns non-zero value, I try to watch the ErrorReturnCode.full_cmd for debug. But strange thing happens when I pass an `str` parameter with space in them like this:
```python3
try:
    sh.python2('-t', 'print 3')  # Use a wrong -t option to raise ErrorReturnCode
except ErrorReturnCode as e:
    print(e.full_cmd)
``` 
You will get this:
`/usr/bin/python2 -t print 3`
However the right format seems to be
`/usr/bin/python2 -t 'print 3'`
This confused me until I figure out how `subprocess.Popen()` works - the space don't separates the args. So should it be mentioned in document or just enclose the arguement if it contains any space?

**Comment by amoffat** [comment]
This will be fixed in the next release by https://github.com/amoffat/sh/pull/472
