### ISSUE TITLE
Can not pickle errors

### ISSUE THREAD

**Issue by wichert** [amoffat/sh#439]
I am using sh in a celery task. When an exception is thrown in that context it needs to be pickled by celery so it can be re-raised in another task. This does not work with sh. Here is a simple script to test pickling:

```python
import sh
import pickle

try:
    sh.false()
except sh.ErrorReturnCode as e:
    pck = pickle.dumps(e)
    exc = pickle.loads(pck)
```

This aborts with the following error:

```
Traceback (most recent call last):
  File "c.py", line 9, in <module>
    exc = pickle.loads(pck)
TypeError: __init__() missing 2 required positional arguments: 'stdout' and 'stderr'
```

**Comment by amoffat** [comment]
Thanks for reporting.
