### ISSUE TITLE
How can I run a full command given as string using sh.py?

### ISSUE THREAD

**Issue by danijar** [amoffat/sh#443]
Let's say the user of my script passes a command to my script via a command line argument. Is there a convenient way to run that command using sh.py? The problem is that the string might contain quoted sequences that should not be split, so I cannot just do

```python
command = "git commit -m 'Hello World'"  # Passed into my script as string.
chunks = command.split()  # This incorrectly splits Hello and World apart.
sh.Command(chunks[0])(*chunks[1:])  # As a result, this command fails.
```

**Comment by amoffat** [comment]
It's not supported.  Sh has deliberately avoided a lot of the stuff a shell (like bash) would do, for example parsing out complicated quoted strings to be fed to exec.  Your best bet is to use a python builtin (subprocess or os.system) to run your string directly.

**Comment by danijar** [comment]
Thanks for the clarification.

**Comment by xmnlab** [comment]
sorry for commenting in a very old issue!
@danijar if you still have this problem, maybe you can resolve that using shlex.split https://docs.python.org/3/library/shlex.html#shlex.split
