### ISSUE TITLE
Improve autocomplete in Python 3.7 using the new module level `__dir__` and `__getattr__`

### ISSUE THREAD

**Issue by scardine** [amoffat/sh#444]
Hi,

I would love to be able to type `sh.<TAB>` at the Jupyter/IDE prompt and get a nice list of every executable in `$PATH`.

Python 3.7 introduced [dynamic module attributes](https://docs.python.org/3/whatsnew/3.7.html#pep-562-customization-of-access-to-module-attributes). Using this feature we can improve autocomplete for the `sh` module. If you think this is a good idea I can send a PR.

Thoughts?

**Comment by amoffat** [comment]
Interesting idea, but very niche feature that would be a lot more work than you might initially assume, given how magical sh can be. That said, I'm not opposed to it and if you still feel inspired, I would consider the PR for merge. Submit it if that is the case.
