### ISSUE TITLE
Put documentation on read the docs

### ISSUE THREAD

**Issue by u2berggeist** [amoffat/sh#445]
...or put it somewhere where I don't have to download and compile files. 

I'm sure it's easy to compile the documentation together, but I'm just trying to figure out what the package can do. I'm not going to download and compile documentation for something I'm not even sure I'll use.

**Comment by meantheory** [comment]
Is the docs website insufficient in some way? http://amoffat.github.io/sh/

and of course you should be using `sh` :smile:

**Comment by u2berggeist** [comment]
Alright, I see what happened. On `README`, you have "Updating the docs" in a Header 2 format. That caught my attention before the smaller "Complete Documentation here". 

All that plus, it was tired and impatient at the time. lol

Thanks for putting up with my brain fart in a nice way! 😅
