### ISSUE TITLE
unexpected error piping to gzip

### ISSUE THREAD

**Issue by dtenenba** [amoffat/sh#449]
I'm trying to do the python sh equivalent of:

```
echo hello | gzip > file.gz
```

Here's my attempt:

```python
import sh

sh.gzip(sh.echo("hello", _piped=True), _out="file.gz")
```

and the result:

```
---------------------------------------------------------------------------
ErrorReturnCode_1                         Traceback (most recent call last)
<ipython-input-16-17a5c91e2a9a> in <module>()
----> 1 sh.gzip(sh.echo("hello", _piped=True), _out="file.gz")

~/envs/sra-pipeline-i02dZRQF/lib/python3.6/site-packages/sh.py in __call__(self, *args, **kwargs)
   1425             stderr = open(str(stderr), "wb")
   1426
-> 1427         return RunningCommand(cmd, call_args, stdin, stdout, stderr)
   1428
   1429

~/envs/sra-pipeline-i02dZRQF/lib/python3.6/site-packages/sh.py in __init__(self, cmd, call_args, stdin, stdout, stderr)
    772
    773             if should_wait:
--> 774                 self.wait()
    775
    776

~/envs/sra-pipeline-i02dZRQF/lib/python3.6/site-packages/sh.py in wait(self)
    790
    791             else:
--> 792                 self.handle_command_exit_code(exit_code)
    793
    794                 # if an iterable command is using an instance of OProc for its stdin,

~/envs/sra-pipeline-i02dZRQF/lib/python3.6/site-packages/sh.py in handle_command_exit_code(self, code)
    813             exc = exc_class(self.ran, self.process.stdout, self.process.stderr,
    814                     ca["truncate_exc"])
--> 815             raise exc
    816
    817

ErrorReturnCode_1:

  RAN: /usr/bin/gzip

  STDOUT:


  STDERR:
gzip: standard output is a terminal -- ignoring

```

It says standard out is a terminal, yet I explicitly set `_out` to be a filename.

What am I doing wrong?

This is with sh 1.12.14 and python 3.6.0 on macOS High Sierra 10.13.6 (17G65).

**UPDATE**: Figured it out, you have to pass the `-f` flag to gzip to tell it to compress anyway, even if (it thinks) that standard output is a terminal:

```python
import sh

sh.gzip(sh.echo("hello", _piped=True), "-f", _out="file.gz")
```

Not sure if this is a bug in `sh` or not. Leaving this here in case others run into the same problem. 
If it's not an `sh` bug you can close it. I guess I expected the presence of `_out` would somehow clue the `gzip` process into knowing it's writing to a file.

**Comment by amoffat** [comment]
This was indeed a subtle bug. It's been fixed with 56e18cff5a82c7a3253a0dfe8792a44ae7050aae and will go out with the next release. I tested locally with gzip, and your example works with that change without the `-f` flag. Basically it's as you assumed, sh wasn't being smart enough when it detected that it was writing output to a file.
