### ISSUE TITLE
Attach a RunningCommand to a running process

### ISSUE THREAD

**Issue by Ellon** [amoffat/sh#451]
Hello,

I'm trying to control some processes on my machine from python. I may launch these processes from python using sh without problems, but they may be already launched in the system, and in this case I would like to "grab them" and control them from python, eventually killing and relaunching them.

So I was wondering: is there a way (maybe a "hackish" one) to attach a RunningCommand to a process that is already being run in the machine before the python terminal is launched? If not, could this be a feature to be implemented soon?

**Comment by amoffat** [comment]
Interesting idea but outside of the scope of sh.
