### ISSUE TITLE
Implement `__getitem__` to pass extra arguments/options to parent command

### ISSUE THREAD

**Issue by cgarciae** [amoffat/sh#452]
Say you have the command e.g.
```
gsutil cp -r some/folder gs://bucket/some/folder
```
you can call it very nicely like this
```python
sh.gsutil.cp("-r", "some/folder" "gs://bucket/some/folder")
```
On the other hand, if you want to run this command
```
gsutil -m cp -r some/folder gs://bucket/some/folder
```
now you can't use the nice attribute syntax anymore because of the intermediate `-m` option. However, if you implement the `__getitem__` method on the `Command` correctly you could have an API that looked like this

```python
sh.gsutil["-m"].cp("-r", "some/folder" "gs://bucket/some/folder")
```
I think this is very pythonic and looks very appealing.

**Comment by amoffat** [comment]
I'm not a fan of that syntax. The best you can get now is to bake, and I would like to stick to this:

```python
import sh
gsutil = sh.gsutil.bake("-m")
gsutil.cp("-r", "some/folder" "gs://bucket/some/folder")
```
