### ISSUE TITLE
When can it support Python3.7?

### ISSUE THREAD

**Issue by yuluo-ding** [amoffat/sh#456]

**Comment by andersgs** [comment]
It works fine for me on 3.7.

**Comment by yuluo-ding** [comment]
When i write `from sh import ifconfig`, the ide shows some wrong.

> Inspection info: This inspection detects names that should resolve but don't. Due to dynamic >dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and >class-level items are supported better than instance items.

**Comment by shvechikov** [comment]
It's not a bug. `sh` uses custom import hook for magic importing of any shell command. IDE just can't discover it.

**Comment by amoffat** [comment]
The next release will have official 3.7 and 3.8 support.
