### ISSUE TITLE
Python 2: Non-ASCII characters in stderr or stdout during non-zero exit result in exception with no message

### ISSUE THREAD

**Issue by mjpieters** [amoffat/sh#463]
The `sh` `ErrorReturnCode` exception class [sets the exception message to a Unicode string](https://github.com/amoffat/sh/blob/858adf0c682af4c40e41f34d6926696b7a5d3b12/sh.py#L384-L388), regardless of Python version. That's not really an option in Python 2, but it just happens to work when your Unicode string is ASCII safe.

However, when the process exited with non-ASCII characters on stderr or stdout, then showing the exception in a traceback results in a `<exception str() failed>` exception message, because the `str()` call on the exception instance fails.

Demo reproducing the problem, run with Python 2.7:

```python
import sh, sys
print(sys.version_info)
python27 = sh.Command(sys.executable)
python27(c=r"import sys; sys.stderr.write(u'\u2603\n'.encode('utf8')); sys.exit(1)")
```

This outputs

```python
sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/.../lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/.../lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/.../lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: <exception str() failed>
```

When you catch the exception, the `.args[0]` attribute shows why:

```python
>>> try:
...     python27(c=r"import sys; sys.stderr.write(u'\u2603\n'.encode('utf8')); sys.exit(1)")
... except sh.ErrorReturnCode as exc:
...     print(repr(exc.args[0]))
...     str(exc)
...
u"\n\n  RAN: /.../bin/python -c import sys; sys.stderr.write(u'\\u2603\\n'.encode('utf8')); sys.exit(1)\n\n  STDOUT:\n\n\n  STDERR:\n\u2603\n"
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 129: ordinal not in range(128)
```

So on Python 2, please encode the message to a suitable `str` object before setting it.

**Comment by amoffat** [comment]
Thanks for reporting and taking the time to write a clear sample to reproduce.  @abadger's fix will be deployed with the next release.
