### ISSUE TITLE
can't create sh object with param inside class

### ISSUE THREAD

**Issue by ddstreet** [amoffat/sh#464]
$ cat test-sh.py 
```python
import sh

class MyClass():
    def __init__(self):
        self.git = sh(_tty_out=False).git

MyClass()

print('great!')
```

$ ./test-sh.py 
Traceback (most recent call last):
  File "./test-sh.py", line 9, in <module>
    MyClass()
  File "./test-sh.py", line 7, in __init__
    self.git = sh(_tty_out=False).git
  File "/usr/lib/python3/dist-packages/sh.py", line 3369, in __call__
    module_name = parsed.body[0].targets[0].id
AttributeError: 'Attribute' object has no attribute 'id'

**Comment by ddstreet** [comment]
this also fails without any param, e.g:

self.git = sh().git

fails.

self.git = sh.git

does work.

am i just using it wrong?

**Comment by amoffat** [comment]
Yes. I recommend you look at some examples on the home page http://amoffat.github.io/sh/index.html
