### ISSUE TITLE
Support for shell variables? and for a set -xv mode?

### ISSUE THREAD

**Issue by dkmbw** [amoffat/sh#470]
Hi,
first i have to say, your tool is fantastic. i really love writing stuff with sh instead of bash. i have a few  proposals for enhancements:

1. support for a set -xv mode so i can see which actual shell commands are run? that would be helpful
2. is there a possibility to support shell variables? for example in bash "a=b c=d command" will have a and c as variables available (and modify commands behaviour), this is not the same as environment variables apparently (was new to me, too).

at least for the last one, i will try to make a patch, but my python is very hacky...

Yours,
Dennis

**Comment by amoffat** [comment]
Hi Dennis, thanks for your thoughts.

1. This is accomplished through Python's logging:

```python
import logging
import sh
logging.basicConfig(level=logging.INFO)
sh.ls()
```
Output:
```
INFO:sh.command:<Command '/bin/ls'>: starting process
INFO:sh.command:<Command '/bin/ls', pid 32394>: process started
INFO:sh.command:<Command '/bin/ls', pid 32394>: process completed
```

2. It won't be supported.

**Comment by dkmbw** [comment]
Okay, cool, thanks. Could you reference the first one in the documentation? it was not clear to me and i would bet i could forget it. And i suppose other people would appreciate it as well

**Comment by amoffat** [comment]
Good idea 25862f8c454c4e1b9caf52fa861735ca3e874e3e

**Comment by dkmbw** [comment]
<3
