### ISSUE TITLE
ErrorReturnCode 255 when debugging with PyCharm

### ISSUE THREAD

**Issue by xapple** [amoffat/sh#475]
On my linux server I have the following setup:

    $ lsb_release -a
    Description:    Ubuntu 18.04.2 LTS
    $ python3 -V
    Python 3.7.1

I have a simple test script called `test.py` containing the following lines:
 
    import sh
    sh.ls('/')

Which works perfectly when called from a shell:

    $ python3 /home/xapple/test/test.py
    bin   home        lib64   opt sbin  tmp      vmlinuz.old
    boot  initrd.img      lost+found  proc  snap  usr
    dev   initrd.img.old  media   root  srv   var
    etc   lib       mnt   run sys   vmlinuz

But not when invoked through a PyCharm remote interpreter debugger as such:

     $ python3 -u /home/xapple/.pycharm_helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 0.0.0.0 --port 37511 --file /home/xapple/test/test.py
    pydev debugger: process 31311 is connecting

    Connected to pydev debugger (build 191.6605.12)
    Traceback (most recent call last):
      File "/home/xapple/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
        main()
      File "/home/xapple/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
        globals = debugger.run(setup['file'], None, None, is_module)
      File "/home/xapple/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
        pydev_imports.execfile(file, globals, locals)  # execute the script
      File "/home/xapple/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
        exec(compile(contents+"\n", file, 'exec'), glob, loc)
      File "/home/xapple/test/test.py", line 2, in <module>
        print(sh.ls('/'))
      File "/home/xapple/.local/lib/python3.7/site-packages/sh.py", line 1427, in __call__
        return RunningCommand(cmd, call_args, stdin, stdout, stderr)
      File "/home/xapple/.local/lib/python3.7/site-packages/sh.py", line 774, in __init__
        self.wait()
      File "/home/xapple/.local/lib/python3.7/site-packages/sh.py", line 792, in wait
        self.handle_command_exit_code(exit_code)
      File "/home/xapple/.local/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
        raise exc
    sh.ErrorReturnCode_255: 

      RAN: /bin/ls /

      STDOUT:

      STDERR:

I suspect this is because the forking process is affected by running within the debugger environment somehow and it triggers this exception:

https://github.com/amoffat/sh/blob/master/sh.py#L1968

Replacing the script with the following lines instead removes the error:
 
    import pbs
    pbs.ls('/')

So this regression must have been introduced somewhere with the new version of `sh`.

**Comment by xapple** [comment]
I can confirm that the problem occurs at line 1978 here where `sh` simply calls `os._exit(255)`:

https://github.com/amoffat/sh/blob/master/sh.py#L1978

I have tested this on python 3.6 and 3.7

For anyone else coming here with the same problem, all I can recommend is using one of the other available libraries:

| Package | Unix / Python 2 | Unix / Python 3 | Windows / Python 2 | Windows / Python 3 | Compatible forking* |
| ------- | --------------- | --------------- | ---------------    | ---------------    | ------------------- |
| `sh`    | ✅ Works        | ✅  Works       | 🔴 Not supported   | 🔴 Not supported   | 🔴 Fails            |
| `pbs`   | ✅ Works        | 🔴  Fails       | ✅ Works           | 🔴 Fails           | ✅ Works            |
| `pbs3`  | ✅ Works        | ✅  Works       | ✅ Works           | ✅ Works           | ✅ Works            |

\* By 'compatible forking' we mean a method of creating subprocesses that can work successfully inside a debugging environment such as the one provided by PyCharm.

**Comment by schaffino** [comment]
Just bumped into this issue. We're using sh pretty heavily and it's made some debugging efforts a pita.

**Comment by ssbarnea** [comment]
I encountered something similar and after spending a lot of time trying to debug what caused it I ended up proposing https://github.com/amoffat/sh/pull/491 -- this should at least provide meaningful information about what caused the 255.

**Comment by amoffat** [comment]
Yes, the work that landed as a result of #491, which will be released shortly, should provide clarity on the 255 exception.
