### ISSUE TITLE
Covering all the error cases

### ISSUE THREAD

**Issue by clintolsen** [amoffat/sh#476]
Hi:

I'm playing around with sh. It's very interesting compared to subprocess. However, there are a few error cases I was trying to explore to make sure I know how to write a Swiss Army knife wrapper around it.

For flexibility reasons, I'm always going to need to use the `Command()` constructor. It looks like exit codes are well handled but the following are either not documented entirely or I am unsure how to catch them:

1) `sh.CommandNotFound`: Currently printing this exception just prints the command. I didn't see this in the Exception section of the docs.
2) Permission denied: What if the program is not executable or we don't have the privileges to run it? This appears to be caught by 1) above.

Thanks,

-Clint

**Comment by amoffat** [comment]
https://amoffat.github.io/sh/sections/command_class.html#commandnotfound
