### ISSUE TITLE
contextmanager for cleaning up _bg processes

### ISSUE THREAD

**Issue by mahnen** [amoffat/sh#480]
Thanks so much for this library, it is beautiful. I wanted to use it in heavy parallel multiprocessing mode replacing some bash scripts that achieve that with anonymous pipes (|). One issue I encountered was that the processes are not cleaned after killing the script (e.g. ctrl-c ). I was experimenting with a context manager and found something like this could be useful:

```python
from contextlib import contextmanager

@contextmanager
def process_cleaner(*processes):
  try:
    yield
  except:
    for one_process in processes:
        one_process.kill()
        print("killed one")
```
this could then be invoked on one _bg process or many _bg processes:

```python
from sh import cat, grep

my_process1 = grep(cat('lines.txt', _piped=True), '"^...1"', _bg=True)
my_process2 = grep(cat('lines.txt', _piped=True), '"^...1"', _bg=True)

with process_cleaner(my_process1, my_process2):
    print("running")
    my_process1.wait()
    my_process2.wait()
```

to clean up automagically.

**Comment by amoffat** [comment]
Related to https://github.com/amoffat/sh/issues/495

**Comment by ecederstrand** [comment]
I'm voting to close this one. The argumentation in #495 is leaning towards it being a feature to not kill background processes on process exit.

If you do want to clean up background processes anyway, the OP has a nice implementation to do that. It doesn't have to be part of `sh`.

**Comment by ecederstrand** [comment]
I'm closing this issue now. But thanks for the nice process cleaner implementation!
