### ISSUE TITLE
Python 3.7 sh hangs when using in threads

### ISSUE THREAD

**Issue by mzbuild** [amoffat/sh#483]
Hi,
We use the sh module in a threaded context to execute shell commands.  When we were migrating to python 3 from python 2 we encountered some commands hanging.  We created a test script that recreates the issue we are seeing.
`import sh
import logging
import concurrent.futures.thread

def execmd(exe):
    print(sh.ls())
execution_pool = concurrent.futures.thread.ThreadPoolExecutor(20)
i = 0
thread_results = []
while i<500:
    i+= 1
    thread_results.append(execution_pool.map(execmd, ['ls']))

execution_pool.shutdown()`
When running this in python 3.7 it hangs but in python 3.6 it works fine.  We think it is releated to this issue https://bugs.python.org/issue36533.  Installing the latest 3.7.4 didn't fix the issue. We tried recreating the issue without the sh module using threading, forking and logging but we couldn't.  If we could either fix the issue on the sh module side or recreate it in a simple context and file a bug with python that would great.  This is blocking us from migrating our code base from python 2 to python 3 and would prefer not to install python 3.6 as a solution.

**Comment by bsergean** [comment]
Script is:

```
import sh
import logging
import concurrent.futures.thread

def execmd(exe):
    print(sh.ls())

execution_pool = concurrent.futures.thread.ThreadPoolExecutor(20)
i = 0
thread_results = []
while i<500:
    i+= 1
    thread_results.append(execution_pool.map(execmd, ['ls']))

execution_pool.shutdown()
```

**Comment by amoffat** [comment]
I'm unable to reproduce this in the docker image contained [here](https://github.com/amoffat/sh/tree/develop/docker_test_suite) using the installed python 3.7.7.  Please re-open with a test that will fail on the provided docker image.

**Comment by bsergean** [comment]
I can't reproduce either at the time, on a mac with python 3.8.1
