### ISSUE TITLE
It's very difficult to google anything relating to this module

### ISSUE THREAD

**Issue by rlewkowicz** [amoffat/sh#486]
I have a hard time finding the github or even the read the docs sometimes. 

python sh

python sh run shell commands

python "sh" 

python sh module

and on and on. You should just bite the bullet and rename it to something like "python_shell_exec" or something.

**Comment by lfaraone** [comment]
`python-sh` works as a search for me, and the maintainer can name it what they want...

**Comment by rlewkowicz** [comment]
@lfaraone Yep and anyone can request anything they want
