### ISSUE TITLE
output of "at" command directed to stderr instead of stdout

### ISSUE THREAD

**Issue by MikeBusuttil** [amoffat/sh#489]
expecting:
`>>> from sh import at, ls`
`>>> print(at(ls('/'), 'now', '+', '5', 'minutes'))`
`job 6 at Thu Oct  3 14:53:00 2019`

actual result:
`>>> from sh import at, ls`
`>>> print(at(ls('/'), 'now', '+', '5', 'minutes'))`
` `

however:
`>>> from sh import at, ls`
`>>> print(at(ls('/'), 'now', '+', '5', 'minutes').stderr)`
`job 6 at Thu Oct  3 14:53:00 2019`

Observed on python 3.6.8 and python 2.7 on Ubuntu 18.04.3 LTS as well as python 2.7 on CentOS.

Anyway, great package!!  Has really helped me a lot with my most recent project and I plan to add it to some older projects for improved readability and code quality.

Many thanks.

-Mike

keywords: empty, blank, linux at command

**Comment by amoffat** [comment]
Hey @MikeBusuttil, this looks by design of the `at` command:

>        In the POSIX locale, the following shall be written to standard error when a job has  been
>        successfully submitted:
> 
>               "job %s at %s\n", at_job_id, <date>
> 
>        where  date has the same format as that described in the STDOUT section. Neither this, nor
>        warning messages concerning the selection of the command interpreter, shall be  considered
>        a diagnostic that changes the exit status.
> 
>        Diagnostic messages, if any, shall be written to standard error.

http://manpages.ubuntu.com/manpages/trusty/man1/at.1posix.html

You are probably looking for this though http://amoffat.github.io/sh/sections/special_arguments.html#err-to-out

**Comment by MikeBusuttil** [comment]
Thanks so much @amoffat !  Look at that - it's by design.  I appreciate your help and thank you for the great package :)
