### ISSUE TITLE
Shell expansion and globbing made easier?

### ISSUE THREAD

**Issue by jrvarma** [amoffat/sh#496]
I frequently use the function `sh_expand` (listed below at the bottom) to allow shell environment variables, globbing, `~` expansion inside the `sh` module. With this function, the `bash` command 

```
ls -l ~/.bash*  $SHELL $XAUTHORITY
```

can be repllicated with 

```
sh.ls(sh_expand("-l", "~/.bash*", "$SHELL", "$XAUTHORITY")).
```
Is it possible to make it easier to use this without explicitly calling `sh_expand` each time? I was thinking of something on the lines of `bake` which would automatically apply `sh_expand` or even a global setting in the `sh` module that would apply it automatically every time. 

My definition of `sh_expand` is as follows:

```
from glob import glob
from os.path import expandvars, expanduser


def sh_expand(*v):
    def expand_one_arg(s):
        s_expand = expandvars(expanduser(s))
        if "*" in s_expand:
            return glob(s_expand)
        else:
            return [s_expand]

    return [item for s in v for item in expand_one_arg(s)]
```

**Comment by amoffat** [comment]
It's not a crazy request but I personally think it is not in line with sh's goals. sh executes programs and doesn't do fancy shell things like argument-splitting or glob expansions. We leave that to the user. It is inconvenient, but it keeps sh doing one thing and one thing well.
