### ISSUE TITLE
How to use lmod functions in sh

### ISSUE THREAD

**Issue by eylenth** [amoffat/sh#500]
Hi
How can I use the lmod environment( https://lmod.readthedocs.io/en/latest/  ) in the sh function?

I want to execute the following command 
```
[eylenbt@by0q4n] ~ $ module load BCFtools
[eylenbt@by0q4n] ~ $ 

```
But the problem is that 'module' does not exists in path, but it is a function.

```sh
[eylenbt@by0q4n] ~ $ type module
module is a function
module () 
{ 
    eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}

```

If this not possible yet, Could this be a new feature request ?

**Comment by amoffat** [comment]
The trick to running bash builtins:

```python
import sh
sh.bash("-c", "type alias")
```
Output:
```
alias is a shell builtin
```
Or more conveniently:

```python
import sh
builtins = sh.bash.bake("-c")
builtins("type alias")
```

**Comment by amoffat** [comment]
Docs update for next release 796617b991907bb2743a273ac01e7340f389bec9
