### ISSUE TITLE
Should stdout return `bytes`?

### ISSUE THREAD

**Issue by consal** [amoffat/sh#501]
On migration from Python 2.7 to Python 3.6.9 I noticed that `stdout` returns `bytes` instead of `str`. Is it normal? Is there any flag so the sh module decodes the output for me?

```python
>>> import sh
>>> result = sh.ls("-l").stdout
>>> type(result)
<class 'bytes'>
>>> 
```

Cheers

**Comment by ssbarnea** [comment]
yeah, is normal
