### ISSUE TITLE
Piping with |

### ISSUE THREAD

**Issue by cgarciae** [amoffat/sh#510]
Hey, it would be really nice if we could use python `|` operator to do piping so it looked more like in bash. The idea is that you could turn code like this:

```python
sh.wc(sh.ls("-1"), "-l")
```
into this:

```python
sh.ls("-1") | sh.wc("-l")
```

It would require mutating the `wc` Command object after creation in this case. Not familiar with the codebase so I don't know the complexity of adding this feature.

**Comment by amoffat** [comment]
This has been asked many times and there is an FAQ entry for it.
