### ISSUE TITLE
sh ABANDONED? Any active fork?

### ISSUE THREAD

**Issue by cgarciae** [amoffat/sh#511]
There hasn't been new commits in 3 years but the project is great. 
Is there any active fork we can move to?

**Comment by meantheory** [comment]
possible duplicate of #450 - project maintainer comments on roadmap

**Comment by amoffat** [comment]
@cgarciae what critical bug or missing feature is blocking you?

**Comment by amoffat** [comment]
Please see https://github.com/amoffat/sh/issues/512
