### ISSUE TITLE
Maintainer application thread

### ISSUE THREAD

**Issue by amoffat** [amoffat/sh#512]
Hi all,

There have been a number of threads about the activity of `sh` as a project going forward, and I thought I would address them here.  Sh is not abandoned, but admittedly, the lifecycle of maintenance is a lot longer than I would like.  It's on my TODO list, but I am pressured to take care of more pressing priorities in my life right now.  Rather than go down a negative path with the community by arguing about why my timeline is more important, I am opening up sh to take on additional maintainer(s) to alleviate that friction.

If you would like to be a maintainer, please reply to this post.  I will be considering people who are visible in the OSS community, who write high-quality, tested code, and who have similar responsibilities maintaining projects.  You will be responsible for:

* Ensuring sh tests pass on Linux, MacOS, and Unix-like OSes
* Answering issues and questions in a timely manner
* Reviewing PRs and ensuring that they fit in line with the existing philosophy of sh as well as its coding standards (testing, comments, documentation, etc)
* Maintaining documentation
* Developing support for future Python versions across supported OSes
* And most importantly: not breaking the builds

If this is you, voice your interest here and I will reach out to you.

**Comment by lestercheung** [comment]
Hi Andrew!

I have been using sh over the years and noticed that it didn't make it to the CentOS8 official repo (probably because of https://github.com/amoffat/sh/issues/498). I don't have a lot of open source credentials but would love to help.

/me goes clone repo...

**Comment by amoffat** [comment]
Hi @lestercheung thanks for your interest.  Your willingness to help out is much appreciated.  However, I am looking for someone with a bit more experience in open source maintenance.  Cheers.

**Comment by lestercheung** [comment]
I completely understand. All the best finding a co-maintainer and stay safe in Seattle/wherever you are!

**Comment by ecederstrand** [comment]
Hi @amoffat 

I’d like to volunteer. I can’t take full responsibility but I can start with the low-hanging fruit and work my way up. I would prefer if you can at least mentor in the beginning as I find my way around.

I already maintain the https://github.com/ecederstrand/exchangelib package and generally strive for good quality and being a nice person. And we use `sh` at my day job.

**Comment by amoffat** [comment]
Hi Erik! Thanks for your interest. You've been an early contributor to sh as well...I'm seeing commits from you [as early as 2014](https://github.com/amoffat/sh/commit/9664d04ffe946290cd2c6f7551124362a3ce0de4). I'd be very happy to have you as a maintainer, in whatever capacity you can offer. I will reach out to you over the email in your profile.

**Comment by lestercheung** [comment]
That's fantastic news! A lot of us would be sad to see this project getting bitrot.

**Comment by amoffat** [comment]
Welcome aboard Erik and thank you for volunteering your time! 6ba7f7b4ab7a339d361a20bd4b5c49f82d320473
