### ISSUE TITLE
ob_is_tty returns false for stdin even when stdin is a tty

### ISSUE THREAD

**Issue by hartmans** [amoffat/sh#514]
ob_is_tty calls `get_fileno` and then does

```python
if fileno:
```

The problem is that stdin has fileno 0, and 0 is falsy, so this is always false for stdin.
So, similar to what's going on in #414 , you will never be able to pass an unmodified stdin tty through to the subprocess.
Probably that should be

```python
if fileno is None:
```

**Comment by amoffat** [comment]
I think you mean `fileno is not None`, but yes, excellent catch on this :+1: . 1e151901c5f7fcec63b9449f1f24456a943aac4e will go out with the next release
