### ISSUE TITLE
Feature Request: RunningCommand.wait(_timeout)

### ISSUE THREAD

**Issue by MatrixManAtYrService** [amoffat/sh#515]
Firstly, thanks for your work on `sh`, it's great.

I would like to be able to do this:

```
running_command.terminate()
try:
    running_command.wait(_timeout=15) 
except sh.TimeoutException:
    running_command.kill()
running_command.wait()
```

But the `wait` function doesn't accept a timeout.  Is there a convenient way to achieve this elsewhere in the API?  If not, I'd like to propose the above method.

**Comment by MatrixManAtYrService** [comment]
In the meantime, I find that this works reasonably well:

```
def term_wait_kill(self):
    self.terminate()
    for _ in range(15):
        sleep(1)
        if self.process.is_alive()[0]:
            continue
    self.kill()
    self.wait()
running_command.term_wait_kill = lambda: term_wait_kill(running_command)

... elsewhere ...

running_command.term_wait_kill()
```

**Comment by amoffat** [comment]
Yeah, either that or you could do possibly something fancy (and ugly) with `signal.alarm`.  I like the suggestion though, and agree it should be added.

**Comment by amoffat** [comment]
```python
import sh

p = sh.sleep(5, _bg=True)
try:
    p.wait(timeout=1)
except sh.TimeoutException:
    p.kill()
```

Will go out with the next release.
