### ISSUE TITLE
Preventing pydev code analysis and pylint tools from complaining

### ISSUE THREAD

**Issue by dannystaple** [amoffat/sh#52]
PBS generates dynamic class members, which is a great thing but can cause pydev, pylint and other checkers to fail.
Could attributes be added to the pbs module (in docs, comment and other) to prevent the most common python validators from complaining about these.

**Comment by peterdemin** [comment]
This issue will celebrate 5th birthday in 2 days :-)
I understand why it has a low priority, but consider this: Every developer who uses static analyzer (such as pylint or PyCharm) is going to ask: "How do I disable these warnings?".
And these days more people are using static analyzer than not.

**Comment by peterdemin** [comment]
I wish I could PR FAQ section about this to your docs.
Pylint supports this. [no-member] errors can be suppressed by adding following lines to `pylintrc`:
```
[TYPECHECK]                                                                                                             
generated-members=sh 
```

**Comment by amoffat** [comment]
> I wish I could PR FAQ section about this to your docs.

You can :)

**Comment by peterdemin** [comment]
Hm... Where do your docs live? I didn't find it in your repos...

**Comment by amoffat** [comment]
`gh-pages` branch.  follow the readme instructions in that branch

**Comment by peterdemin** [comment]
Opened #374

**Comment by amoffat** [comment]
Closing due to docs changes being live
