### ISSUE TITLE
On v1.13.0, calls with `_fg=False` fail with error "TypeError: Invalid special arguments:    'fg': _fg is invalid with nearly every other option"

### ISSUE THREAD

**Issue by Nicolas-Duboc-IBM** [amoffat/sh#520]
In 1.13.0, the new fg_validator considers only if the `_fg` arg is in the passed arguments without considering if the value of the arg is True :
https://github.com/amoffat/sh/blob/1.13.0/sh.py#L1107

This makes it refuse legitimate calls like sh.ls(*args, _out=self.process_line, _err=self.process_line, _fg=False)` .

**Comment by amoffat** [comment]
Thanks for reporting.  This is fixed on`1.13.1` with e2cb0202ee55930b45ffaa82330f9d9f32b050e4, please upgrade.
