### ISSUE TITLE
Some way to easily handle boolean options

### ISSUE THREAD

**Issue by amoffat** [amoffat/sh#522]
I've been writing some scripts lately that make heavy use of including/excluding options based on some boolean flag. It's clunky:

```python
if dry_run:
    sh.rsync("-n", ...)
else:
    sh.rsync(...)
```
It would be nicer if there was something, maybe `sh.Cond` that takes an object that evaluates to truthy, and a flag to be set if that evaluation is `True`.  So:

```python
sh.rsync(sh.Cond(dry_run, "-n"), ...)
```

I'm not sure if it should be a class (`Cond`) or a function (`cond`), or something named different altogether, but I would want to minimize its chances of colliding its name with other binaries on the system. Thoughts? @ecederstrand

**Comment by amoffat** [comment]
Or maybe even just a tuple, which would be simpler syntax, but that would break backwards compatibility:

```python
sh.rsync((dry_run, "-n"), ...)
```

Currently if `sh` sees a tuple or list, it iterates over the elements and includes them in the final call as if they were entered individually. So that would change/break.

**Comment by ecederstrand** [comment]
The general problem you are trying to solve is building up context-dependent command-line args, right?

The easy cases are easy to solve in a general manner like the above, but it quickly becomes complicated to support weird requirements of arcane tools, like the order of arguments, argument dependencies, differences in key-value syntax etc. I'm worried that this is a can of worms. If you look at [argparse](https://docs.python.org/3/library/argparse.html), it's a non-trivial problem, and even that package doesn't cover all cases in the wild.

I'm not sure building up command-line args needs assistance from `sh`. This is an exercise that is neither difficult or verbose to handle yourself. I also think that the code to build up args should go before calling `sh.some_tool()`. When you're ready to actually call your tool, you should already know your args - just like in a normal shell. Adding logic into the list of args also lowers the readability considerably - I'm not sure we should encourage that.

Here are some examples of how to to the above without assistance from `sh`:

```python
args = list(...)
if dry_run:
    args.append("-n")
if to_file:
    args.append("-o", to_file)
sh.rsync(*args)
```

or if you have many conditions and want more compact code:

```python
def conditionally_add_arg(args, arg, cond):
    if (callable(cond) and cond()) or cond:
        args.append(arg)

args = list(...)
conditionally_add_arg(args, '-n', dry_run)
conditionally_add_arg(args, ('-o', to_file), lambda: os.path.exists(to_file))
sh.rsync(*args)
```

You could be even more fancy, using only built-in Python functionality. If you need validation logic for the final list of args, you can even use `argparse`:

```python
parser = argparse.ArgumentParser(prog='rsync')
parser.add_argument('-n')
parser.parse_args(args)
sh.rsync(*args)
```

**Comment by ecederstrand** [comment]
Implementing your `Cond` class was quite simple, but also without much actual value I can see in real-life programs since the implementation dwarfs any business logic you would need:

```python
import sh

class Cond:
    def __init__(self, *args):
        # Expects an iterable of either arg or 2-tuple containing arg and cond
        self.args_with_cond = args

    def __iter__(self):
         for arg in self.args_with_cond:
              if is instance(arg, str):
                  yield arg
              elif arg[1]:
                  yield arg[0]


sh.ls(*Cond(('-l', True), '-a', ('-h', False)))
```

**Comment by amoffat** [comment]
Good points @ecederstrand. Building up a list of arguments is probably what we want to encourage.

Related, while exploring this issue, one thing I noticed is how `None` is handled as an argument:

```python
import sh
sh.ls(None)
```
```
...

sh.ErrorReturnCode_2: 

  RAN: /bin/ls None

  STDOUT:


  STDERR:
/bin/ls: cannot access 'None': No such file or directory
```
It looks like I'm running `str()` on `None` which doesn't make much sense. If this behavior was changed so that a `None` value excluded the argument altogether, something like this would be possible:

```python
maybe_dry_run = "-n" if dry_run else None
sh.rsync(maybe_dry_run, ...)
```
Technically this is a breaking change if we made it work the above way, but I am tempted to say that nobody could be relying on the old behavior, as `str(None)` doesn't make sense in the first place.

**Comment by ecederstrand** [comment]
If `None` as an argument doesn't make sense, wouldn't it be better for `sh` to validate args properly and throw an error? Does any non-string argument make sense at all? 

If you do have args that are possibly None, it's really easy to filter them out before passing them to `sh`:

```python
args = ('-a', None, '-l')
sh.ls(*filter(None, args))
```

**Comment by amoffat** [comment]
`None` only doesn't make sense if it is passed through literally, as it was. I think it should have special meaning as "ignored" because it allows for better handling of flags.  This:

```python
args = []
if dry_run:
    args.append("-n")
sh.rsync("-v", "-a", *args)
```
versus this:
```python
sh.rsync("-v", "-a",  "-n" if dry_run else None)
```
In fact, if booleans had special meaning, it could made even cleaner, while preserving readability with:
```python
sh.rsync("-v", "-a", dry_run and "-n")
```
To me, it is clear that the last two examples are the most ergonomic, with the last being the most concise.

Building up a list of arguments is probably still a good practice for long complicated commands, but for short commands, of which I just wrote a ton of in my own personal code, I found that having to build up a short list for a single argument was tedious and ugly.

**Comment by ecederstrand** [comment]
I generally lean towards less magic, more validation, and being explicit rather than implicit. I'm slightly worried about weird bugs caused by accepting non-str arguments. Here's an (admittedly very contrived) example:

```python
def get_path(dangerous):
    path = '/' if dangerous else '/tmp/build-dir'

ls.find(get_path(dangerous=False), '-name', 'libc.so.*')
```

I'll let you take the decision on this one. I definitely see the simplicity in code of the examples you have given.

**Comment by amoffat** [comment]
This example works even without accepting booleans, no?

In any case, I appreciate the push back to test the merit of the idea. I'm going to go ahead and merge as it seems like this particular feature has more upsides than downsides.

**Comment by ecederstrand** [comment]
That’s fine with me.

The bug I tried to illustrate is that `get_path()` is missing a return statement. If we only accepted strings as args, the bug would have been caught immediately. By accepting `None`, `find` suddenly searches in `cwd` instead, which would be quite confusing.
