### ISSUE TITLE
Issues enabling unbuffered output

### ISSUE THREAD

**Issue by beaugunderson** [amoffat/sh#524]
Hi there--I'm trying to use `_out` with a callback to print unbuffered output to the screen. Unfortunately the output is line buffered, and to illustrate the issue see this screenshot:

![image](https://user-images.githubusercontent.com/61791/80873297-5b0a9c00-8c6c-11ea-8f29-07721d6df873.png)

My output callback prefixes each line with `xxx`.

The 'Parsing' and 'Rendered' lines contain many updates (they update as the project is parsed and rendered), but only print after the next newline is sent--so the net effect is that there are no updates sent to the screen for 5 minutes, even though the program is printing updates.

I've tried setting `_internal_bufsize=0`, `_out_bufsize=0`, and various combinations of all the other buffer, TTY, and output options.

(Sidenote: the documentation seems to have a mistake, as specifying `_unify_ttys` passes `--unify-ttys` to the underlying application instead of enabling the `unify_ttys` option in `sh`).

I've also tried wrapping my application in `stdbuf -i0 -o0 -e0`, for what it's worth.

**Comment by beaugunderson** [comment]
Oh, I didn't realize there was a corresponding `_err_bufsize` parameter! That totally fixed my issue.

`_err_bufsize` seems to be undocumented right now--because only `_out_bufsize` is mentioned in the docs I assumed that applied to all output, whether to stdout or stderr.

**Comment by amoffat** [comment]
Thanks for reporting, fixed issue with the docs. wrt `_unify_ttys`, that only applies to version `1.13.0` or later, as marked in the docs, so make sure you update if you need it in the future.

**Comment by beaugunderson** [comment]
@amoffat thanks for the quick fix! re: `_unify_ttys`, you are correct--I had `1.13.1` in a virtualenv but managed to run against the older I had in my global. :)
