### ISSUE TITLE
`_env` param does not work with dict-like objects

### ISSUE THREAD

**Issue by saytosid** [amoffat/sh#527]
https://github.com/amoffat/sh/blob/114e6eedf5db022d2a0e5a5b5104ea18394da1a6/sh.py#L1149-L1151
wrt the above snippet, is it necessary to enforce `dict`? This breaks compatibility with other dict-like objects. eg: `os.environ` returns a dict-like object `os._Environ`.

Perhaps a check for `isinstance(env, collections.Mapping)` would allow for more general interface?

**Comment by ecederstrand** [comment]
That sounds very reasonable.
