### ISSUE TITLE
No logs when using _fg=True

### ISSUE THREAD

**Issue by Exidex** [amoffat/sh#528]
With this code:
```
import logging
import sh

logging.basicConfig(level=logging.INFO)
sh.ls(_fg=True)
```
there is no logs printed from library to show what command was actually executed

**Comment by amoffat** [comment]
Thanks for reporting.

**Comment by ecederstrand** [comment]
I'm inclined to think that we shouldn't try to fix this. The docs for [_fg](https://amoffat.github.io/sh/sections/special_arguments.html#fg) already has a warning about sidestepping standard functionality. The reason that running in the foreground does not produce normal log output is that it completely bypasses the `RunningCommand` class where this log output is created.

**Comment by amoffat** [comment]
Good call @ecederstrand, closing.
