### ISSUE TITLE
A better solution to the SignalException_SIGPIPE error

### ISSUE THREAD

**Issue by SegundoBob** [amoffat/sh#533]
A little below this link [Documentation link](https://amoffat.github.io/sh/sections/faq.html#why-is-tty-out-true-the-default) there is the following documentation

> Of course, there are some gotchas with TTY STDOUT. One of them is commands that use a pager, for example:
> 
> import sh
> print(sh.git.log())
> 
> This will raise a SignalException_SIGPIPE, and it’s unclear exactly why. The reason is because git log detects a TTY STDOUT and forks the system’s pager (typically less) to handle the output. The pager checks for a controlling terminal, and, finding none, exits with exit code 1. The exit of the pager means no more readers on git log’s output, and thus a SIGPIPE is received.
> 
> The solution to the git log problem above is simply to use _tty_out=False, but this is not totally obvious.

I suggest changing the above to something like this:

> Of course, there are some gotchas with TTY STDOUT. One of them is commands that use a pager, for example:
> 
> import sh
> print(sh.git.log())
> 
> This will sometimes raise a SignalException_SIGPIPE. The reason is because git log detects a TTY STDOUT and forks the system’s pager (typically less) to handle the output. The pager checks for a controlling terminal, and, finding none, exits with exit code 1. The exit of the pager means no more readers on git log’s output, and thus a SIGPIPE is received.
> 
> import sh
> print(sh.git('--no-pager', 'log'))
> 
> Note that the --no-pager option must come before the git command (in this case log).

[Link to relevant git documentation](https://git-scm.com/docs/git#Documentation/git.txt--P):
```
-P
--no-pager

    Do not pipe Git output into a pager.
```
I was unable to determine when this option was added to git or if it has always been an option.

**Comment by amoffat** [comment]
@SegundoBob This is good information to include. I will probably still keep the bit about setting `_tty_out=False` because that is the issue that the FAQ question is addressing, but I agree that including information about the `--no-pager` option is helpful. Thanks for reporting.
