### ISSUE TITLE
Overloading bitwise OR operator for more shell-like piping?

### ISSUE THREAD

**Issue by mentalisttraceur** [amoffat/sh#546]
I feel like any time you have a non-trivial shell pipeline, or want to ease the transition for someone familiar with how shell works, it would be vastly nicer to write and read

```python
sh.foo(...) \
| sh.bar(...) \
| sh.qux(...)
```

instead of something like

```python
foo = sh.foo(..., _piped=True)
bar = sh.bar(foo, ..., _piped=True)
qux = sh.qux(bar..., _piped=True)
```

There might be even better ways to write the latter? But if so, then they don't seem to be obviously documented anywhere?

**Comment by amoffat** [comment]
Hi @mentalisttraceur. As you can imagine, this is a requested feature from people who prefer bash piping to function composition. There is [an FAQ entry](http://amoffat.github.io/sh/sections/faq.html#why-not-use-to-pipe-commands)

With a little work, you could make your example a little more minimal:

```
shp = sh.bake(_piped=True)
from shp import foo, bar, qux
qux(bar(foo()))
```

**Comment by mentalisttraceur** [comment]
Thanks! Though that's a deceptively minimal example, because it omits arguments to each individual command, which I used `...` for in my first example, but let's expand it with some examples to see how it becomes harder to read for any substantially large pipeline or argument list:

```python
qux(bar(foo("--something", "/tmp/foo"), "--quiet", "--symmetric", "--cipher-algo=AES256"), "-xyz", "-a1")
```

Hence why I split it up into individual lines:

```python
foo = shp.foo("--something", "/tmp/foo")
bar = shp.bar(foo, "--quiet", "--symmetric", "--cipher-algo=AES256")
shp.qux(bar, "-xyz", "-a1")
```

**Comment by mentalisttraceur** [comment]
Anyway, I strongly relate to the desire to bend commands to be function-like, rather than bending Python to be shell-like. I would say overall that's a great design principle! Bourne shell was a bad language in many ways, and trying to make things more shell-like is often a bad idea.

That said, please also consider:

Bourne shell was bad in so many ways precisely because it was designed to be a good DSL for a couple of specific things:

1. executing external programs
2. redirecting file descriptors

and the pipeline is the intersection of both, pretty much the most well-designed aspect of the DSL. Everything else, like the quoting/escaping/field-splitting mess, didn't have as much time to be optimized "for humans" by the time it got locked in by backwards compatibility and wide adoption, but I would argue that pipeline was pretty much close to optimal for the exact problem that it's solving.

I don't mean necessarily the pipe `|` character, but I mean the shape `{{ cmd }} {{ operator }} {{ cmd }} {{ operator }} {{ cmd }} ...`.

Did you notice how that looks exactly like the shape that Haskell uses to compose monads together?

I mention that because we both seem to agree that functions are great, and making things like functions is good, so I hope you know of Haskell, which is one of the most "things should be functions!" languages out there, and I hope you are familiar enough with the monad design pattern to recognize that *processes are basically monads*, and piping them is basically monadic application.

So the most radically functional language since Lisp has settled on monads as the design pattern that solves a bunch of problems with function composition, and then settled on the pattern `{{ thing }} {{ operator }} {{ thing }} {{ operator }} {{ thing }} ...` as the syntactic sugar to make that easier to program.

The shell pipeline shape isn't just a shell thing. It's just one occurrence that the shell stumbled into of a natural pattern, a natural optimum that has proven itself useful in very function-oriented programming that looks nothing like shell.

**Comment by mentalisttraceur** [comment]
To elaborate on "processes are monads", consider: a monad, when you strip it down and oversimplify it, is basically a way to compose functions while doing some operation in between each composition, which may or may not conditionally control the composition (for example error handling might look as if you did `compose(e, f3, e, f2, e, f1)` except if `e` could "short circuit" the composition and just bypass all the other functions and return the first error as soon as it happened).

I think there is a notable parallel between functions that use an I/O monad and these processes-made-to-look-like-functions. Just as functions in Haskell that do I/O have to be composed in a way that weaves the I/O monad through their code, these function-like processes, when piped, are weaving their `stdin` and `stdout` together.

Which doesn't seem like a "thing" being woven between them, but remember that

1. the I/O monad represents, conceptually, the external world (mutable shared state!), and

2. the piping between processes is *just an optimized implementation equivalent to* one process dumping all of its output into some file or memory (mutable shared state!), and then after its done the other reading it from there.

So there is a really substantial equivalence here, and monads as a programming pattern and syntactic sugar for composing them was driven almost 100% by a desire to represent and use things as functions.

**Comment by mentalisttraceur** [comment]
Though you could say that using any one of the Python libraries that implements function composition, we can build on and combine our earlier examples to get pretty nice pipelining as-is:

```python
compose(
    qux.bake("-xyz", "-a1"),
    bar.bake("--quiet", "--symmetric", "--cipher-algo=AES256"),
    foo.bake("--something", "/tmp/foo"),
)
# this reads backwards but it's easy enough to make an `rcompose`
# that calls from first argument to last (rightwards / in reverse).
```

A little boilerplate left from calling `.bake` each time, but pretty good. Might be nice if there was a way to make `foo`, `bar`, and `qux` partially apply their first call's arguments automatically, then execute upon being called the second time (or as I call it, "partialize" them).

So I guess if my ramble about monads still didn't convince you, maybe next I'll ask for a `shpb = sh.bake(_piped=True, _auto_bake=True)` feature?  (Maybe called `_auto_bake_once` instead? `_prebaked`?)

**Comment by amoffat** [comment]
I appreciate you explaining your thoughts clearly in this thread.

sh is mostly "complete" software. There are a couple of medium-sized architectural design changes that will happen in 2.0.0, but everything else is largely bug fixes and documentation improvements. If something is a very compelling change, it can be added, but mostly I am against adding small new subjective improvements.
