### ISSUE TITLE
Windows compatible?

### ISSUE THREAD

**Issue by paulobear** [amoffat/sh#547]
I'm guessing not, since the examples don't seem to include windows commands?

Thx,
Paul E Ourada

**Comment by ecederstrand** [comment]
Windows is not supported: https://amoffat.github.io/sh/sections/faq.html#will-windows-be-supported

See also discussion in #155

**Comment by xmnlab** [comment]
Hi folks!

I use sh in some projects such as makim, sugar, irx, etc.
And I needed to add support for windows, so I created a new library called xhell (xh): https://github.com/osl-incubator/xh/

it is a wrapper to sh, when the OS is linux or mac, but it implements a a similar api provided to sh, but for windows.

it is still in earlier stages, but I am already using it in my projects, I am still waiting feedback from windows users.

Usually I don't promote another lib in other repos, but in this case it is partially a wrapper on sh. so I hope it would not be a problem here.
