### ISSUE TITLE
Clarify that Windows isn't supported on Readme and PyPI

### ISSUE THREAD

**Issue by cool-RR** [amoffat/sh#548]

**Comment by Muffo** [comment]
I agree it should be explicitly mentioned.

`pip` command to install `sh` works okay, but when I try to import the library I get this:

```
ModuleNotFoundError: No module named 'fcntl'
```

See also [this question on stackoverflow](https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl).

**Comment by ecederstrand** [comment]
@amoffat What do you think about the wording in the two referenced PRs (one for the README shown here on GitHub and PYPI, and one for the GitHub Pages docs)?

**Comment by amoffat** [comment]
LGTM @ecederstrand

**Comment by ecederstrand** [comment]
Merged
