### ISSUE TITLE
Return not the same as in terminal

### ISSUE THREAD

**Issue by michaelaye** [amoffat/sh#549]
I'm trying to get the key.value pairs of the output of `conda env list`.
Trying out the baked command, I am seeing quite a difference in the returned items.
Basically, all but one key ('base') are lost:

https://gist.github.com/e95780508568f7a1ea0a844debe22f02

Versions:
conda: 4.9.2
sh: 1.13.1
OS: PopOS (Ubuntu)

**Comment by amoffat** [comment]
I'm not too familiar with conda, but one thing I might try is to turn off [TTY output](https://amoffat.github.io/sh/sections/special_arguments.html#tty-out) with `_tty_out=False`. Conda might be formatting things weird for the [size of the TTY](https://amoffat.github.io/sh/sections/special_arguments.html#tty-size) that it sees when executed.

Also you can use [subcommands](https://amoffat.github.io/sh/sections/subcommands.html), which might serve you better. I might do something like this:

```python
import sh
conda = sh.conda.bake(_tty=False)
conda.env.list()
```

**Comment by michaelaye** [comment]
Thanks for the fast feedback! Unfortunately, no change:

![image](https://user-images.githubusercontent.com/69774/103387151-75c53700-4abf-11eb-95ba-ed3624781906.png)

**Comment by michaelaye** [comment]
WTH? I just checked with 

`print(subprocess.check_output(["conda", "env", "list"]).decode('ascii'))`

and it returns what `sh` is returning. (I guess you use subprocess internally?)
So what tricks are happening when `conda env list` runs in the terminal??

**Comment by amoffat** [comment]
We don't use subprocess internally (it does a fork/exec manually), but what you found is a good clue. There aren't many things that should be different between executing in python vs commandline. Are you using a conda shell plugin by any chance that would alter the output?

Also do you get the same output from doing `conda info --envs` ?

**Comment by michaelaye** [comment]
When i execute `!conda info --envs` in the notebook I get the same as in the terminal, but the env names are also swallowed using subprocess and sh.

I'm unsure what would constitute a "shell plugin", maybe it's relevant that my default shell is `fish`? And, you might not know that, if you are not a conda user, here is how the conda script is initialized to be used with fish:

1)
In `config.fish` (executed at every fish launch):

`eval /home/maye/miniconda3/bin/conda "shell.fish" "hook" $argv | source`

and that script looks like this:

```bash
$ cat /home/maye/miniconda3/bin/conda                                                                                                                (py38) 
#!/home/maye/miniconda3/bin/python
# -*- coding: utf-8 -*-
import sys
# Before any more imports, leave cwd out of sys.path for internal 'conda shell.*' commands.
# see https://github.com/conda/conda/issues/6549
if len(sys.argv) > 1 and sys.argv[1].startswith('shell.') and sys.path and sys.path[0] == '':
    # The standard first entry in sys.path is an empty string,
    # and os.path.abspath('') expands to os.getcwd().
    del sys.path[0]

if __name__ == '__main__':
    from conda.cli import main
    sys.exit(main())
```
Hope that helps?

**Comment by amoffat** [comment]
Hmm, yeah I'm not sure what could be going on. But from your results from `subprocess.check_output()`, it doesn't look like this is a result of any quirks with `sh`, since both outputs match. I would say your best bet is to visit the conda issues and see if they can help you out. Hope you figure it out!
