### ISSUE TITLE
Test and document Python 3.9 support

### ISSUE THREAD

**Issue by ecederstrand** [amoffat/sh#551]
@amoffat Python 3.9 was released in October 2020. What do we need to update to test and a announce support for 3.9? I'm looking at .travis.yml, tox.ini, sh.py, setup.py and the front page of the docs. Anything else?

**Comment by amoffat** [comment]
Hey Erik, thanks for staying up on this. I think that would cover it. Assuming the tests pass, we should be mostly good to go, code-wise. I like to run the tests on MacOS as well, but if you don't have access to a Mac machine, I can run them.
