### ISSUE TITLE
Would it be possible for pushd to have a "create_directory_if_nonexistent" argument (default False?)

### ISSUE THREAD

**Issue by jerkstorecaller** [amoffat/sh#558]
In situations where you're creating things from scratch, every call to pushd has to be preceded with a mkdir to create the target directory, it's kind of annoying. The directory names I use branch depending on user input, configurations, etc so I can't just do a single "mkdir -p" at the start.

**Comment by amoffat** [comment]
This functionality makes the most sense as a helper function that the user implements when they need it, so we can leave `pushd` as a function that just changes directory, which stays truer to its shell analog [pushd](http://www.gnu.org/software/bash/manual/html_node/Directory-Stack-Builtins.html#Directory-Stack-Builtins)

**Comment by jerkstorecaller** [comment]
Fair enough, thank you
