### ISSUE TITLE
Baking bash commands?

### ISSUE THREAD

**Issue by cupdike** [amoffat/sh#560]
Is there any way to bake an extra part of a bash command?  I'm trying to run a command that runs properly like this:

`/bin/bash -c '/usr/local/bin/scontrol show hostnames server1'`

Note that the quotes are required around the whole command string.

This correctly runs it:

`sh.bash("-c", "scontrol show hostnames server1")`

I would really like to bake it down to the scontrol command.  When I try like this, I can't get the quotes to work out because they don't wrap the scontrol part.

```
>>> scontrol = bash.bake("-c","scontrol")
>>> scontrol("show hostnames server1")
Traceback (most recent call last):
<SNIP>
sh.ErrorReturnCode_1: 

  RAN: /bin/bash -c scontrol 'show hostnames server1'
```
I tried playing around but no luck.  I can at least cover the -c:

`bashc = sh.bash.bake("-c")`

And I guess a workaround would be to just wrap it in a function:

```
>>> def scontrol(command):
...    return bashc(f"scontrol {command}")
... 
>>> scontrol("show hostnames server1")
```

Honestly, that's not that bad--but if there is an sh "native" way to do it, please let me know...

**Comment by amoffat** [comment]
Yeah, it's the quotes that makes this kind of thing difficult. Everything in quotes is considered a single argument passed to the command, and what we do with baking and subcommands would require breaking up that single argument somehow. Your suggested workaround is probably the best way to do it.

**Comment by cupdike** [comment]
Got it--thanks!
