### ISSUE TITLE
Problem mocking sh call to process

### ISSUE THREAD

**Issue by mike10010100** [amoffat/sh#563]
Hi there! I'm currently trying to mock out a call to a binary (`hab`) that may or may not exist on a given build machine.

I'd like to simply ensure that the command passed to sh is the command we'd like for it to run.

The command itself is:

```
import sh

sh.hab.config.apply(....)
```

The closest I've gotten mock to properly working is with:

```
@mock.patch("sh.hab", create=True)
    def test_execute_apply(self, hab_cmd):
        hab_cmd.return_value = "sample_response"
```

However, when trying to see what command was actually run, mock only returns more mocked objects.

Is there some way I can specifically mock out the system call so that the tests run and I can compare what command *should* have been sent to the OS?

Thanks!

**Comment by ecederstrand** [comment]
When you mock `sh`, then by definition you're bypassing all code in `sh` and thus also the code that would compile the final command to be executed.

If the only thing you want to do is to mock out the actual command execution in sh, but keep all other functionality, then it's not simple to do. You can start by looking at `sh.OProc`, but I wouldn't get my hopes too high.

That said, your mock should fail if you're not mocking the right binary. And you can assert the mock call arguments like this:

```python
from unittest import mock
import sh

@mock.patch("sh.doesnotexist", create=True)
def test_sh_mock(sh_cmd):
    sh_cmd.return_value = "XXX"
    assert sh.doesnotexist('status') == 'XXX'
    sh_cmd.assert_called_with('status')

    sh_cmd.alsodoesnotexist.return_value = 'YYY'
    assert sh.doesnotexist.alsodoesnotexist() == 'YYY'
    sh_cmd.alsodoesnotexist.assert_called_with()
```

**Comment by ecederstrand** [comment]
I'm closing this issue. Feel free to reopen if you have additional questions related to this.
