### ISSUE TITLE
_done callback consistent deadlock when accessing RunningCommand arg passed to callback

### ISSUE THREAD

**Issue by 0xkag** [amoffat/sh#564]
This consistently deadlocks:

```python
from sh import sleep

def done(cmd, success, exit_code):
    print(cmd, success, exit_code)

sleep('1', _done=done)
```

This is possibly related to #413 and #518.  This is on version 1.14.1 and Python 3.7 (but I doubt that matters).

Now I suppose one might say "Well, don't do that with cmd and the done callback" ... However, if the argument is passed to the callback it should be safe to use, IMO.  And none of the test cases cover accessing done callback arg 0 at all.

The reason it deadlocks is because of a double wait on `_wait_lock`: `_wait_lock` is already held whenever `self._process_just_ended()` is called (either via `self.is_alive()` or `self.wait()`), `self._process_just_ended()` is what calls the done callback, and then the printing of `cmd` tries to coerce it to a string using its stdout value, which then also calls `self.wait()`, which tries to acquire `_wait_lock` again and deadlocks.

You can see this in the stack trace:

```
^CTraceback (most recent call last):
  File "y.py", line 6, in <module>
    sleep('1', _done=done)
  File ".../site-packages/sh.py", line 1520, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File ".../site-packages/sh.py", line 784, in __init__
    self.wait()
  File ".../site-packages/sh.py", line 831, in wait
    exit_code = self.process.wait()
  File ".../site-packages/sh.py", line 2491, in wait
    self._process_just_ended()
  File ".../site-packages/sh.py", line 2442, in _process_just_ended
    done_callback(success, self.exit_code)
  File "y.py", line 4, in done
    print(cmd, success, exit_code)
  File ".../site-packages/sh.py", line 930, in __str__
    return self.__unicode__()
  File ".../site-packages/sh.py", line 937, in __unicode__
    if self.process and self.stdout:
  File ".../site-packages/sh.py", line 869, in stdout
    self.wait()
  File ".../site-packages/sh.py", line 831, in wait
    exit_code = self.process.wait()
  File ".../site-packages/sh.py", line 2457, in wait
    with self._wait_lock:
KeyboardInterrupt 
```

I believe this can be fixed simply by changing `_wait_lock` to a `threading.RLock()` instead of `threading.Lock()`.  (I tried it, and it seemed to work just fine.)

However, I do think a fresh look is needed at what `_wait_lock` is protecting.  The comments suggest it is _only_ for `self.exit_code` race prevention, but the lock is being held for much more than that.  I think the acquisition of this lock can be more fine-grained: only when `self.exit_code` is being _written_, and since `self.exit_code` never changes once written you don't need to hold the lock while reading it once you know it's not None.

You can do something like this, I think:

```python
def _do_stuff_when_exit_code_is_already_set():
    pass

if self.exit_code is not None:
    _do_stuff_when_exit_code_is_already_set()
    return

#  it appears that wait lock is None, but now we acquire the lock to be sure
while True:
    with self._wait_lock:
        if self.exit_code is not None:
            break
        # do stuff that will set exit_code
        break
_do_stuff_when_exit_code_is_already_set()
```

(Also, thanks for this library; I like the interface.)

**Comment by amoffat** [comment]
This is great info @0xkag , thank you for doing the deep dive, I appreciate it. I will follow up on this 👍
