### ISSUE TITLE
Documentation URL 404 (because of change in github pages)

### ISSUE THREAD

**Issue by rjmill** [amoffat/sh#565]
As of April 15, gh pages [doesn't redirect subdomains of github.com anymore](https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/).

The docs are still available through the github.io domain:

https://amoffat.github.io/sh/

**Comment by amoffat** [comment]
Thanks for reporting 👍
