### ISSUE TITLE
missing GitHub Pages site: pypi "Complete documentation here" link is broken

### ISSUE THREAD

**Issue by mpictor** [amoffat/sh#568]
At https://pypi.org/project/sh/ there is a `Complete documentation here` link pointing to https://amoffat.github.com/sh
If I click it, I get a 404 stating `There isn't a GitHub Pages site here.`

**Comment by ecederstrand** [comment]
This was also reported in https://github.com/amoffat/sh/issues/565

We'll need to release a new package to PyPI before the link is actually fixed there.

**Comment by amoffat** [comment]
Thanks for bumping, I'll take care of this tonight

**Comment by amoffat** [comment]
Alright, it's back. Thanks again for reporting and bumping
