### ISSUE TITLE
How to use grep in command (example: ls /home |grep -w abc)

### ISSUE THREAD

**Issue by tSupan** [amoffat/sh#577]

**Comment by ecederstrand** [comment]
I assume a better question is how to use pipes with `sh`, since `grep` is not a special command as far as `sh` is concerned.

Here's the relevant part of the documentation describing how to work with pipes: https://amoffat.github.io/sh/sections/piping.html?highlight=pipe#piping

**Comment by ecederstrand** [comment]
Assuming this has been solved. Closing.
