### ISSUE TITLE
PicklingError encountered when using multiprocessing

### ISSUE THREAD

**Issue by TotalVariation** [amoffat/sh#590]
Hello,

I was using Slurm-based HPC with multiple GPUs to train deep learning models. I used some packages to process data that is dependent on sh.
![Screenshot from 2021-11-02 14-31-12](https://user-images.githubusercontent.com/36463966/139867537-5ada96e0-975a-4b87-982b-310f5b714dce.png)
![Screenshot from 2021-11-02 14-32-20](https://user-images.githubusercontent.com/36463966/139867632-607bc086-37aa-4ed2-93d7-8d3fdde3ca2b.png)

I believe this error was caused by multiprocessing but I have little knowledge about this.

Can you help me resolve this issue? Thank you very much.

**Comment by ecederstrand** [comment]
`GlobResults` is not meant for pickling. If you want to run a command using `sh` in a multithreaded environment, then pass around the args for the `sh` command, not the command object itself.

**Comment by TotalVariation** [comment]
@ecederstrand Yes, thank you for your explanation.
