### ISSUE TITLE
How to use result of RunningCommand in JSON.loads  ?

### ISSUE THREAD

**Issue by mattbryson** [amoffat/sh#593]
Im converting an old Python 2 app to Python 3 

It loads JSON via `sh` commands, which has stopped working.  

I understand from the docs that methods like `json.loads` won't work with an instance of `RunningCommand` even though its string like.

However, I can't appear to get a string value that does work!

This is the original code that did work.
```python
aws = sh.aws 
......
data = aws.s3api("list-objects", bucket=s3url.bucket, prefix=s3url.path, max_keys=1)
data.wait()
items = json.loads(data)
``` 

But that now throws `TypeError: the JSON object must be str, bytes or bytearray, not RunningCommand`

So I have attempted to use both `bytes` and `str` but nothing appears to work...

Convert to string:
```python
....
data.wait()
jsonStr = str(data)
print (type(jsonStr))
print (jsonStr)
items = json.loads(jsonStr)
```
Outputs

```python
<class 'str'>
{
    "IsTruncated": true,
    "Marker": "",
    "Contents": [
        {
            "Key": "a/path/to/object/",
            "LastModified": "2021-10-06T10:45:45+00:00",
            "ETag": "\"g41d8gd98f10b204g9800998gcf8527e\"",
            "Size": 100,
            "StorageClass": "STANDARD"
        }
    ],
    "Name": "bucket-name",
    "Prefix": "a/path/to/object/",
    "MaxKeys": 1,
    "EncodingType": "url"
}

Traceback (most recent call last):
.....
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Use stdout bytes:
```python
....
jsonBytes = data.stdout
print (type(jsonBytes))
print (jsonBytes)
items = json.loads(jsonBytes)
```
Outputs

```python
<class 'bytes'>
b'\x1b[?1h\x1b=\r{\x1b[m\n    "IsTruncated": true,\x1b[m\n    "Marker": "",\x1b[m\n    "Contents": [\x1b[m\n        {\x1b[m\n            "Key": "a/path/to/object//",\x1b[m\n            "LastModified": "2021-10-06T10:45:45+00:00",\x1b[m\n            "ETag": "\\"g41d8gd98f10b204g9800998gcf8527e\\"",\x1b[m\n            "Size": 100,\x1b[m\n            "StorageClass": "STANDARD",\x1b[m\n      }\x1b[m\n    ],\x1b[m\n    "Name": "idetailaid-demo",\x1b[m\n    "Prefix": "a/path/to/object//",\x1b[m\n    "MaxKeys": 1,\x1b[m\n    "EncodingType": "url"\x1b[m\n}\x1b[m\n\r\x1b[K\x1b[?1l\x1b>'

Traceback (most recent call last):
.....
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any help much appreciated!

**Comment by amoffat** [comment]
The "bytes" version above looks suspicious... you have a bunch of escape sequences in the beginning of your json that appear to be used for visual formatting. I bet the aws command is adding those because it thinks that it is printing to a terminal. You can change this behavior by adding `_tty_out=False` to your sh command, or there might be another option on the aws command for disabling pretty printing.

**Comment by mattbryson** [comment]
Legend.  That fixed it.  You were correct, looks like the AWS CLI puts off load of ASCII Esc codes in there for formatting on the terminal.
