### ISSUE TITLE
How can I output the command before it's executed?

### ISSUE THREAD

**Issue by dAnjou** [amoffat/sh#596]
sh's logging is not really an option, I think, because I'd like to customize the output to my liking.

I tried using `_out` with a callback, and it kinda works, but only if and when the command produces output.

Is there something like the `_done` hook but before execution?

Thank you 🙇

**Comment by ecederstrand** [comment]
Why do you need the help of `sh` for this? You should already know which command you want to execute before invoking `sh`.

**Comment by dAnjou** [comment]
I'm using sh in my project's build script and I'd like to keep it as clean and concise as possible. Therefore I'd like to avoid duplication like:
```python
print("poetry run pytest")
sh.poetry.run.pytest()
```

**Comment by ecederstrand** [comment]
You can get the `Command` object before executing it, and use that for your print statement:

```python
>>> cmd = sh.git.status
>>> print(f'Running {cmd}')
Running /usr/local/bin/git status
>>> cmd()
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by dAnjou** [comment]
Ah, thanks! That should work well enough.
