### ISSUE TITLE
sudo with-context does not apply to _out and _err redirection.

### ISSUE THREAD

**Issue by amoffat** [amoffat/sh#60]
This is a problem, example:

``` python

import pbs as sh

with sh.sudo:
    sh.sed(sh.echo("omg"), "s/omg/lol/", _out="/root/wat")
```

This is because PBS internally handles open()ing the redirection files, so that it can pass the file descriptors to subprocess.  Unfortunately, PBS doesn't have sudo access for the open(), only the commands PBS is running.  One possible solution would be to give PBS sudo access for its operations, but this means making PBS handle all the authentication, and all the fun that goes along with that.

**Comment by JackLeo** [comment]
No updates?

**Comment by amoffat** [comment]
unfortunately, it seems that nobody has gotten around to implementing it yet.  i will review all PRs that address this though

**Comment by amoffat** [comment]
Going to close this as a "will not fix." If  you are interested in giving your `sh` code full root access, outside of basic `sh.sudo`, start the python script with sudo, drop privs, and use calls to `os.setuid(0)` around areas where you need your subprocesses to have full root access.
