### ISSUE TITLE
test_no_fd_leak fails on CentOS Stream 8

### ISSUE THREAD

**Issue by sandrobonazzola** [amoffat/sh#600]
Fails `test_no_fd_leak` while building on CentOS Stream 8: https://cbs.centos.org/kojifiles/work/tasks/9987/2689987/build.log

Not sure what causes the failure, it passes the build on CentOS Stream 9: https://cbs.centos.org/kojifiles/packages/python-sh/1.14.2/5.el9/data/logs/noarch/build.log

```
FAIL: test_no_fd_leak (__main__.MiscTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/sh-1.14.2/test.py", line 2856, in test_no_fd_leak
    self.assertEqual(baseline, num_fds)
AssertionError: 22 != 20
```

**Comment by amoffat** [comment]
Strange, but thank you for reporting. It is a flaky test by nature ([too flaky to run on macos](https://github.com/amoffat/sh/blob/develop/test.py#L2777-L2779), because it tries to get a baseline number of file descriptors for the parent process before launching the subprocess.

**Comment by ecederstrand** [comment]
Also failing in CI/CD pipeline: https://github.com/amoffat/sh/runs/6879109379?check_suite_focus=true

**Comment by ecederstrand** [comment]
Closing this one because there's very little debug information. If it pops up again, we should now get better output in the error logs.
