### ISSUE TITLE
Support binding a callable with a baked command

### ISSUE THREAD

**Issue by supriyo-biswas** [amoffat/sh#604]
First of all, I'd like to say thanks for this module, it's a lifesaver when working with stuff that only provides command line tools.

Sometimes, I'd like to bind a callable so that I can easily process the output of a command without repetitive boilerplate.

As an example, I'm currently working with the `gcloud` CLI, where I do stuff like this:

```python
iam = sh.gcloud.iam.bake(format='json')
list_of_roles = json.loads(str(iam.roles.list(show_deleted=True, project='my-project')))
```

Having to do stuff like `json.loads(str(...))` for every invocation gets repetitive quickly, and it also makes stuff a little more difficult to reason about.

Therefore, I'd like to have a feature to bind a callable such that `callable(RunningCommand())` is returned. Usage of the API might look like this:

```
iam = sh.gcloud.iam.bake(format='json', _callable=lambda x: json.loads(str(x))
list_of_roles = iam.roles.list(show_deleted=True, project='my-project') # returns a list
```

**Comment by amoffat** [comment]
Thanks for bringing it up. I can relate to your issue though, and have had a similar experience with repetition.

There is another feature I have been thinking about, called "shims" that would do something similar to what you describe. Basically, anyone in the community could write a "shim package" plugin, named something like `sh-shim-gcloud`. It would contain input and output shims that could be hooked into the underlying commands.

So for example, if you had the `sh-shim-gcloud` package installed, you would be able to call `sh.gcloud.iam.roles.list(...)` and if the `format='json'` arg was detected by the shim, it would automatically deserialize to python objects. Similarly, it could detect `format='yaml'`.

It's a very general solution, but it would allow community members to add their own shim packages, and sh would pick them up and use them automatically.

We can leave this issue open to invite more discussion around this topic.

**Comment by ecederstrand** [comment]
I have a feeling we're special-casing something that could be solved if it was easier to use standard Python customization patterns. The above could also be achieved by subclassing `RunningCommand`:

```python
import sh

class MyRunningCommand(sh.RunningCommand):
    def json(self):
        return json.loads(str(self))

sh.RunningCommand = MyRunningCommand

sh.echo("{'a': 123}").json()
```

The above doesn't actually work because of the module loading tricks in `SelfWrapper`, so this is just to show the idea.

**Comment by ecederstrand** [comment]
@supriyo-biswas I just committed the above patch. Would my suggested solution work for you?

**Comment by ecederstrand** [comment]
With the second PR, the standard case without the `sh.Command()` indirection also works:

```python
import json
from sh import RunningCommand, Command, echo


class MyRunningCommand(RunningCommand):
    def json(self):
        return json.loads(str(self))


Command.RunningCommandCls = MyRunningCommand

res = echo('{"a": 123}').json()
print(res, type(res)). # {'a': 123} <class 'dict'>
```

**Comment by supriyo-biswas** [comment]
There are other commands for which I’d like to have the ability to get their raw outputs. If I understand correctly, the current proposal is a all-or-nothing deal?

**Comment by ecederstrand** [comment]
Nope, this will work just like before in the normal case. But if you want the output transformed to JSON, you call the `.json()` method.

**Comment by supriyo-biswas** [comment]
In my opinion the JSON method is still repetitive boilerplate, my aim for this feature being something that feels natural, as if the externally called command were a part of Python itself.

However, I would understand if you want to take the project in a different direction. The PRs that I made continue to work for me :)

**Comment by ecederstrand** [comment]
Coming from C# and Java, I'm not sure I would call the 7 chars in `.json()` "boilerplate", compared to the alternative `_callable=...`. Anyway, if you really want to avoid them, then you could have your `__str__` autodetect the output format:

```python
import json
from sh import RunningCommand, Command, some_command

class MyRunningCommand(RunningCommand):
    def __str__(self):
        res = super().__str__()
        if b'--format=json' in self.cmd:
            return json.loads(res)
        return res


Command.RunningCommandCls = MyRunningCommand

res = some_command('{"a": 123}', format="json")
print(res, type(res))
```

**Comment by amoffat** [comment]
@ecederstrand one concern I have is manipulating the global `Command.RunningCommandCls` from potentially different places. Not only as a race condition, but with different submodules competing and overwriting that class type. There would need to be a way to scope that change locally. We have at least one mechanism for scoping sh objects ([execution contexts](https://amoffat.github.io/sh/sections/default_arguments.html)), but it will add to the complexity.

Revisiting this thread again, @supriyo-biswas your original suggestion is ergonomic but the complication with it is that output from a subprocess is not produced at once... it is streamed in asynchronously, in different chunk sizes, and put into different buffers. The pseudocode from your original suggestion implies that all of the data has been received and the process has ended, but it would need to account for the streaming cases somehow. Do you have some thoughts on how a post processor should the streaming case?

**Comment by ecederstrand** [comment]
@amoffat I understand your concern and agree that messing with global state is problematic.

It is actually possible to change the `RunningCommandCls` of just the execution context:

```python
import sh

sh2 = sh()

class A(sh.RunningCommand):
    def __str__(self):
        print("In", self.__class__)
        return super().__str__()

class B(A):
    pass

sh.Command.RunningCommandCls = A
sh2.Command.RunningCommandCls = B
print(sh.echo('{"a": 123}'))
print(sh2.echo('{"b": 456}'))
```

which outputs:

```
In <class '__main__.A'>
{"a": 123}

In <class '__main__.B'>
{"b": 456}
```

**Comment by amoffat** [comment]
@ecederstrand oh, great! that solves my concern. it sounds like this issue is solved then yeah?  @supriyo-biswas if you'd like to work on your original suggestion, feel free to start a PR. i think there is no reason why both solutions can't exist.
