### ISSUE TITLE
Piping output to stdout AND a variable

### ISSUE THREAD

**Issue by kotborealis** [amoffat/sh#608]
I would like to be able to pipe command output to stdout AND to variable, something like this:
```python
text = sh.bash("echo 123", _out=sys.stdout)
# text == `123`
# stdout gets `123` too
```

Is this a feature, or should I go around it with callbacks?

**Comment by amoffat** [comment]
Like `tee` right? No, there is no feature for that. A callback would do
what you want, as would iterating over the lines with `_iter`

**Comment by kotborealis** [comment]
Thanks, I've tried to implement it using callback, but iterating might be cleaner.

**Comment by ecederstrand** [comment]
Closing. Feel free to post your solution here for others to benefit.

**Comment by kotborealis** [comment]
Alright.
I needed a wrapper that calls `bash`, returns output and prints it to stdout. I came up with this code:
```py
import sh
import io
import sys


def bash(*args, **kwargs):
    """
    Call bash command.
    By default, returns stdout+stderr or raises a `sh.ErrorReturnCode`
    and pipes stdout+stderr into sys.stdout.
    """
    stdout = io.StringIO()

    def stdout_cb(data):
        [s.write(data) for s in [stdout, sys.stdout]]

    out = kwargs.pop("_out", stdout_cb)
    err_to_out = kwargs.pop("_err_to_out", True)

    sh.bash.bake("-c")(
        *args,
        _out=out,
        _err_to_out=err_to_out,
        **kwargs
    )

    return stdout.getvalue()
```

**Comment by amoffat** [comment]
It turns out there actually is a `_tee` option that I completely forgot about https://amoffat.github.io/sh/sections/special_arguments.html#tee. It will do exactly what you want:

```
>>> greeting = sh.echo("hello", _out=sys.stdout, _tee="out")
hello
>>> greeting
hello
```

**Comment by kotborealis** [comment]
Wow! Thank you so much! This will simplify my code.

By the way, "issues" might be the wrong way to discuss such questions, maybe you should try to enable "discussions" for those. 
https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions

**Comment by amoffat** [comment]
Good idea @kotborealis. Are you able to see the discussions tab now?

**Comment by kotborealis** [comment]
Yep, it works.
