### ISSUE TITLE
Python 2 deprecation?

### ISSUE THREAD

**Issue by zdog234** [amoffat/sh#619]
Hi, this should be treated as a suuuper low-priority item, but would you be open to deprecating python 2.7?

The motivation for me to submit this issue is that I want to submit a PR to add a type hint to `pushd`, but I haven't actually worked with typed code prior to 3.6, and I haven't worked with 2.X since college.

My one experience isn't enough to drop 2.X support -- I still feel motivated enough to figure out how to get backwards-compatible type hints added.

That being said, I'm guessing that, as time goes by, more and more wannabe contributors like myself will find python 2 support intimidating.

I'm not really in a position to weigh the tradeoffs though, and I'm in a privileged position of not having to maintain any old python codebases that'd be hurt by not being able to receive security & feature updates for what could be a really crucial library

**Comment by amoffat** [comment]
Hey there, we are deprecating all of 2.* in the release/2.0.0 branch, take a look here https://github.com/amoffat/sh/blob/release/v2.0.0/pyproject.toml#L22-L25

Feel free to make changes against that branch to be up to date with the next release

**Comment by zdog234** [comment]
Ooh, thx :D
