### ISSUE TITLE
change is behaviour of which, breaking change I think

### ISSUE THREAD

**Issue by dmeecs** [amoffat/sh#621]
Hi,

Just noticed when upgrading from 1.14.2 to 1.14.3 there seems to be a change in the behaviour of the `sh.which` function. http://amoffat.github.io/sh/sections/command_class.html#which 

In 1.14.2 which returns a string. In 1.14.3 which returns a RunningCommand.

In 1.14.2

```
> type(sh.which('python'))
str
```

In 1.14.3

```
> type(sh.which('python'))
<class 'sh.RunningCommand'>
```

Is this an intentional change? It broke our tests, we were depending on which being a string. I wouldn't be surprised if it trips some other people up moving from 1.14.2 to 1.14.3. 

We were passing the output of which to subprocess open, e.g. the output of which is the binary to call with Popen

```
/usr/lib/python3.7/subprocess.py:1465: in _execute_child
    executable = os.fsencode(executable)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def fsencode(filename):
        """Encode filename (an os.PathLike, bytes, or str) to the filesystem
        encoding with 'surrogateescape' error handler, return bytes unchanged.
        On Windows, use 'strict' error handler if the file system encoding is
        'mbcs' (which is the default encoding).
        """
>       filename = fspath(filename)  # Does type-checking of `filename`.
E       TypeError: expected str, bytes or os.PathLike object, not RunningCommand

../deps/venv/lib/python3.7/os.py:812: TypeError
```

**Comment by ecederstrand** [comment]
This is an intentional change and was discussed in https://github.com/amoffat/sh/issues/579

Basically, our view is that `sh.which()` returning `str` is a bug, not a feature, and thus fixing it is not a breaking change.

**Comment by dmeecs** [comment]
thanks for the reply.
