### ISSUE TITLE
output of sh.which('packer') returning as 'str' and RunningCommand in different python versions

### ISSUE THREAD

**Issue by minskmaz** [amoffat/sh#625]
Both macOS v12.6 and shells are zsh

 sh.which('packer', _env=os.environ)

python 3.9.7 -  returns a string type (the path I want from which)
python 3.9.14 - returns a RunningCommand

1) wondering what could cause this? shell configuration?
2) in 3.9.14 there seems to be nothing that will coax the RunningCommand object to yield a string, though it shows up in the terminal session's stdout.

suggestions welcomed and thanks in advance!

**Comment by ecederstrand** [comment]
Duplicate of https://github.com/amoffat/sh/issues/621

**Comment by ecederstrand** [comment]
Regards to 1., I'm pretty sure you have two different version of `sh` running in the two Python environments.

**Comment by minskmaz** [comment]
Yes I found this right after posting  Thank you for quick response.
