### ISSUE TITLE
Threading issue with loop

### ISSUE THREAD

**Issue by fardarter** [amoffat/sh#629]
When running the following:

```python
for tuple in replacement_tuples:
     for line in sh.grep(
        "-rl",
         tuple[0],
         target_dir,
         _iter=True,
     ):
        print(line)
```

I get the following error.

```sh
./foo/README copy.md
./foo/README copy 5.md
./foo/README copy 4.md
./foo/README copy 2.md

exit code: 0
Exception in thread background thread for pid 46533:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/opt/homebrew/lib/python3.10/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/opt/homebrew/lib/python3.10/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/grep -rl couchbasenode-1.cnm.org ./foo

  STDOUT:


  STDERR:

Traceback (most recent call last):
  File "/Users/saulnachman/Repos/dev.azure.com/HealthDevOps/CatchAndMatchWeb/./test.py", line 61, in <module>
    print(stuff)
  File "/opt/homebrew/lib/python3.10/site-packages/sh.py", line 934, in __str__
    return self.__unicode__()
  File "/opt/homebrew/lib/python3.10/site-packages/sh.py", line 941, in __unicode__
    if self.process and self.stdout:
  File "/opt/homebrew/lib/python3.10/site-packages/sh.py", line 873, in stdout
    self.wait()
  File "/opt/homebrew/lib/python3.10/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/opt/homebrew/lib/python3.10/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/grep -rl couchbasenode-1.cnm.org ./foo
  
  
  STDOUT:


  STDERR:

```

New to this lib and to python, so not sure if I'm doing something dumb or not, but I suspect if I am there's something useful that could be added to the docs.

**Comment by ecederstrand** [comment]
grep returns exit code 1 if it doesn't match anything. So most likely, `/usr/bin/grep -rl couchbasenode-1.cnm.org ./foo` doesn't return any matches.

If you don't want exceptions even if grep matches nothing, then you can use the special `_ok_code` kwarg: `sh.grep(..., _ok_code=[0, 1])`

**Comment by fardarter** [comment]
Can we keep this open as a docs example request?

If I can muster the energy I'll try make a PR sometime.

**Comment by ecederstrand** [comment]
Can you explain what would you like to improve in the docs?

Exit codes and the ErrorReturnCode exceptions are documented in https://amoffat.github.io/sh/sections/exit_codes.html and also mentions the `_ok_code` kwarg, which is doecumented in https://amoffat.github.io/sh/sections/special_arguments.html#ok-code

**Comment by fardarter** [comment]
IMO examples for common gotchas are useful. I looked at the error codes item and didn't connect the dots. 

The mostly suffer from the curse of knowledge as devs, so the places where beginners stumble are important. 

I'd just add a nice loop example to show the case.

**Comment by ecederstrand** [comment]
I see what you mean. It's difficult to describe what seems obvious when you're the package developer.

I'm not sure how adding a for loop to the examples would help, though. The exception is raised also without it:

```python
>>> sh.grep("this string does not match", "some_file.txt")
[...]
sh.ErrorReturnCode_1: 

  RAN: /bin/grep this string does not match .bashrc

  STDOUT:

  STDERR:
```

**Comment by fardarter** [comment]
Right, but the loop would be an elaboration showing how the `_ok_cod` kwarg could get involved.

I'm new to the lib as well as python and I got distracted by all the other things going on in the output. I didn't click that it was errors codes I was dealing with and an example would have alerted me to the possibility. 

One of the things I really like about this library is that it's making shell error handling much more tractable but my intuitions around looping here are different than if I were writing bash, since it would just be a noop in bash.

Even if you don't agree that it's useful, it might be, and then my question is: do you see a harm? If not, then I'd argue the asymmetry suggests that adding the doc is a valid step because of possible upside but no downside.

**Comment by ecederstrand** [comment]
I can see how adding an example on using `_ok_code` would be useful. I just don't get how adding an example with a for loop would help somebody better understand how `_ok_code` works.

```python
>>> sh.grep("this string does not match", "some_file.txt", _ok_code=(0, 1))
>>>
```

seems more clear to me than:

```python
>>> for i in range(10):
>>>     sh.grep("this string does not match", f"some_file_{i}.txt", _ok_code=(0, 1))
>>>
```

**Comment by fardarter** [comment]
Just in general most of the interesting things in programming happen in loops. It's a nice example of when the case may occur with not a lot of extra detail.
