### ISSUE TITLE
Provide wheels for sh

### ISSUE THREAD

**Issue by psontag** [amoffat/sh#635]
Hey, would it be possible to provide Python wheels for the latest sh version?

Wheels seem to be available on pypi for older versions, but they are missing for version 1.14.3 https://pypi.org/project/sh/1.14.3/#files

**Comment by ecederstrand** [comment]
@amoffat Can you upload wheels for the latest version?

**Comment by amoffat** [comment]
CD is live and 2.0.0 [wheels are up](https://pypi.org/project/sh/2.0.0/#files)
