### ISSUE TITLE
parsing default argument for `_env` does not work for `dict` literals spanning multiple lines

### ISSUE THREAD

**Issue by jimustafa** [amoffat/sh#636]
The following

```python
import sh


def test1():
    sh2 = sh(_env=dict(
        PATH='/usr/bin'
        ))
    output = sh2.env()
    print(f'test1 env: {output.stdout}')


def test2():
    sh2 = sh(_env={'PATH': '/usr/bin'})
    output = sh2.env()
    print(f'test2 env: {output.stdout}')


def test3():
    sh2 = sh(_env={
        'PATH': '/usr/bin'
        })
    output = sh2.env()
    print(f'test3 env: {output.stdout}')


test1()
test2()
test3()

```

gives

```
test1 env: b'PATH=/usr/bin\n'
test2 env: b'PATH=/usr/bin\n'
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    test3()
  File "test.py", line 20, in test3
    'PATH': '/usr/bin'
  File "/home/jimustafa/.pyenv/versions/cookiecutter-voila-app/lib/python3.7/site-packages/sh.py", line 3581, in __call__
    parsed = ast.parse(code)
  File "/home/jimustafa/.pyenv/versions/3.7.13/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
SyntaxError: illegal target for annotation
```

**Comment by ecederstrand** [comment]
Thanks for reporting!

This is a bug in sh. It's also a really tacky part of sh, as the comment in https://github.com/amoffat/sh/blob/develop/sh.py#L3564 indicates. Basically, the problem is that `inspect.stack()` only returns the line containing `sh2 = sh(...`, not the entire statement in the following lines. This leads us to evaluate a non-complete code snippet.

**Comment by jimustafa** [comment]
Thanks @ecederstrand! Yeah, thought it might have to do with newlines in the `dict` literal. `sh` is great! And this bug is not a big issue, as we can work around it with the `dict` constructor if we wanted to pass in a large environment split over many lines. Thanks again!

**Comment by amoffat** [comment]
This has been remedied in 2.0.0. Note however that the `sh2 = sh(` syntax has changed to `sh2 = sh.bake(`. See more details [here](https://github.com/amoffat/sh/blob/develop/MIGRATION.md#removed-execution-contexts--default-arguments)
