### ISSUE TITLE
Cannot iterate stderr while discarding stdout

### ISSUE THREAD

**Issue by N-Coder** [amoffat/sh#638]
I want to iterate the lines written to stderr by my program, while discarding the massive amounts written to stdout with as little overhead as possible. Unfortunately, this use case seems to be forbidden by the current argument validation:
```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sh
>>> sh.ls(_iter="err", _no_out=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/finksim/.venv/lib/python3.9/site-packages/sh.py", line 1456, in __call__
    extracted_call_args, kwargs = self._extract_call_args(kwargs)
  File "/scratch/finksim/.venv/lib/python3.9/site-packages/sh.py", line 1366, in _extract_call_args
    raise TypeError("Invalid special arguments:\n\n%s\n" % exc_msg)
TypeError: Invalid special arguments:

  ('no_out', 'iter'): You cannot iterate over output if there is no output

>>> sh.__version__
'1.14.3'
```
My workaround is to pass `_out="/dev/null"` instead of `no_out`, but I'm not sure what this actually causes under the hood. Is the data still read by python and then "written" to /dev/null? So some more info in the docs how the redirection is done would be awesome. :wink: 

Besides this minor annoyance, a big thank you for this awesome library, I wouldn't want to call commands from python without it anymore. :heart:

**Comment by amoffat** [comment]
This has been fixed in 2.0.0, you can now specify `_iter="err"` and `_no_out=True`. Thank you for reporting and for the kind words

**Comment by N-Coder** [comment]
Thanks! Could you please also comment on whether `..., _iter="err", _no_out=True)` is the recommended way of doing this or do I also need something like `_out="/dev/null"`?

PS: The docs still refer to version 1.14. ;)

**Comment by amoffat** [comment]
If I'm understanding the problem correctly, ` _iter="err", _no_out=True` should be what you want, but the more I look at it, the more I could see how that might be interpreted to have different behavior. Does it work for you, and do you have any suggestions wrt to ergonomics?

Wrt the docs, thanks for the reminder. They will be updated soon
