### ISSUE TITLE
Add "sh v2 no longer returns RunningCommand by default" to CHANGELOG

### ISSUE THREAD

**Issue by JacobHayes** [amoffat/sh#648]
Hi, thanks for the great package! I updated to v2 recently and was confused by a handful of `str object has no attribute .stderr` sorts of messages. I didn't see anything in the changelog that seemed relevant until I came across [MIGRATING](https://github.com/amoffat/sh/blob/develop/MIGRATION.md#return-value-now-a-true-string) (so thanks for that!). The RunningCommand->str output seems like a pretty big breaking change, so might be nice to add to the CHANGELOG. Cheers!

**Comment by amoffatgmi** [comment]
Thanks, for some reason I missed that one
