### ISSUE TITLE
process substitution / anonymous named pipes

### ISSUE THREAD

**Issue by warpfork** [amoffat/sh#66]
I have a situation where I want to call one program which can only accept a certain kind of input via a file which must be named in the arguments, but I want to feed it content generated from another program.

In other words, I have a situation that would be expressed in bash with a process substitution like this:

```
 tail -f <(echo "generated")
```

(Relevant: https://en.wikipedia.org/wiki/Process_substitution )

In python, I can solve this with a tempfile fairly easily.

A step better: I can also solve it with a named pipe with a mkfifo call fairly easily, which gives me the joys of in-memory rather than actually hitting the filesystem needlessly.

However, that still leaves something to be desired; I have to pick a name for my fifo, and I have to remove it again when I'm done.  If I get SIGKILL, I leave a dangling fifo hanging around on my filesystem.  What would really be excellent is if I could tap into the magic stuff in the /proc/$pid/fd and /dev/fd/$fd areas common in a linux world... that would give me a system where the kernel itself is functioning as my cleanup.

That example of process substitution in bash up above does something clever like that.  If you run that example and then look at what actually happened with `ps`, you'll see something like this:

```
tail -f /dev/fd/63
```

Bash created a fifo somewhere where I don't have to worry about it (I think it's somewhere under /proc/ so it just goes away when the processes die?); stdout of the `echo` writes into the fifo and the reading end of the fifo is made into file descriptor 63 for  `tail`.  And then the "/dev/fd/63" part is magic that happens to be a name for the fifo that is fd 63 to the current process.

What would really be excellent is if I could tap into the same level of magic up in the python world.

In the course of writing this, I ended up realizing that I can use "/dev/fd/0" as an argument to get a program to read its own standard in as a file, and since I don't happen to be using stdin already in my current case, this solves my immediate problem.  A more general solution would still be excellent, though, and for that we would need the ability to pass arbitrarily numbered file descriptors into child processes, instead of being limited to stdin/stdout/stderr aka 0/1/2.

Also, I'm not sure how portable the "/dev/fd/$fd" stuff is; I feel a little uncomfortable hardcoding that in, and bash takes care of it for me, but I have no idea how I'd go about finding out in a cross platform way what the location is for the magic filenames-to-selfprocess-file-descriptors.

**Comment by ecederstrand** [comment]
@amoffat This is a really old suggestion and hasn't seem any support from others for the last many years. Maybe we should just close it without fixing?

**Comment by fracai** [comment]
I for one would still be interested in this. Granted, my use case is currently handled by just using sh to call a script that handles the named pipes, but in the interest of feature completeness I think it'd be useful to at least keep this on the roadmap.

**Comment by amoffat** [comment]
@ecederstrand I think I tend to agree with you. It is a cool idea, and it seems like when people need it, it would very very convenient, but it also seems like people don't need it very often. I'll close it and we can re-open if more momentum builds behind it.
