### ISSUE TITLE
_fg validator seems to be overly strict

### ISSUE THREAD

**Issue by iamjackg** [amoffat/sh#663]
I noticed that the [`_fg` validator](https://github.com/amoffat/sh/blob/aa8ed42bccfad4e1d08bf46397f19f12822f129e/sh.py#L1111) only allows `{"env", "fg", "cwd"}` as kwargs, but it looks to me like at least `ok_code` is [still used in an `fg` context](https://github.com/amoffat/sh/blob/aa8ed42bccfad4e1d08bf46397f19f12822f129e/sh.py#L1506).

I understand not wanting `piped` there, but should the restriction for `ok_code` be relaxed?

**Comment by amoffat** [comment]
That seems reasonable to me. Want to make a PR?
