### ISSUE TITLE
[bug] Exception when creating instance of ErrorReturnCode

### ISSUE THREAD

**Issue by honnix** [amoffat/sh#664]
sh Version: 2.0.3
Python version: 3.8.16

```python
>>> from sh import ErrorReturnCode
>>> ErrorReturnCode("", None, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/sh.py", line 313, in __init__
    self.exit_code = self.exit_code  # makes pylint happy
AttributeError: 'ErrorReturnCode' object has no attribute 'exit_code'
```

**Comment by ecederstrand** [comment]
ErrorReturnCode instances are not meant to be created like that. They are created from the metaclass. See e.g. https://github.com/amoffat/sh/blob/develop/sh.py#L445

Do you have an actual use case where being able to do the above would be useful?

**Comment by honnix** [comment]
Hmm, I think I can do this instead:

```python
from sh import ErrorReturnCode_42

erc = ErrorReturnCode_42("foo", b"stdout", b"stderr", False)
```

**Comment by ecederstrand** [comment]
Yes, that would be the recommended solution. Closing, but feel free to reopen if you have additional questions related to this.
