### ISSUE TITLE
TypeError: 'SelfWrapper' object is not callable

### ISSUE THREAD

**Issue by MiaoheLin** [amoffat/sh#667]
I'm newbie to python and sh, I meet a problem when using sh. It's very kind of you if you could help me. 
I want to use the _cwd to set the current working directory of a new shell. But I got the below error:

```
[root@hce2 kernel]# python3
Python 3.9.9 (main, Feb  9 2022, 09:00:41) 
[GCC 10.3.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sh
>>> sh(_cwd="/root/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'SelfWrapper' object is not callable
```

Is there anything wrong? Or I just misunderstand the sh(_cwd)?
Many thanks in advace.

**Comment by ecederstrand** [comment]
Since version 2.0 this syntax has been deprecated. Instead, use the `sh.bake()` method. See https://github.com/amoffat/sh/blob/develop/MIGRATION.md#removed-execution-contexts--default-arguments

**Comment by MiaoheLin** [comment]
That works for me. Many thanks for your reply!

**Comment by jcrben** [comment]
@MiaoheLin I'm trying the workaround and I see this:
<img width="1405" alt="image" src="https://github.com/amoffat/sh/assets/5614134/af5e7a80-f290-44ed-aa01-53ed757d89ca">

not sure what I'm doing wrong
