### ISSUE TITLE
sh documentation is outdated 

### ISSUE THREAD

**Issue by mtelka** [amoffat/sh#674]
The official `sh` documentation at https://amoffat.github.io/sh/ seems to be for version 1.14.0 (HTML page title says so), while the latest `sh` version is 2.0.3.  Please update.

There is also missing documentation for `new_group`/`_new_group`.

Thank you.

**Comment by amoffat** [comment]
Duplicate of #656, closing

**Comment by amoffat** [comment]
FWIW, if this is blocking you, https://github.com/amoffat/sh/blob/develop/MIGRATION.md describes the major differences
