### ISSUE TITLE
ssh contrib doesn't interact 

### ISSUE THREAD

**Issue by 4l1fe** [amoffat/sh#685]
I don't understand what i'm doing wrong but my case is basic.

I'm simply trying to run ssh
```python
import sys
from sh.contrib import ssh
import logging

logging.basicConfig(level=logging.INFO)


def ssh_interact(content, stdin):
    sys.stdout.write(content.cur_char)
    sys.stdout.flush()


cmd = ssh("192.168.3.51", interact=ssh_interact)

print(cmd)

cmd.wait()
```

While running it looks like
```shell
$ python3 contrib_ssh.py

INFO:sh.command:<Command '/usr/bin/ssh 192.168.3.51', pid 43938>: process started
```

If to run the command in a shell, ssh asks the question
```shell
$ ssh 192.168.3.51

The authenticity of host '192.168.3.51 (192.168.3.51)' can't be established.
ED25519 key fingerprint is SHA256:w+chO1NXZkCcSSkcN8k5CyeusreCMGT3TmFaDpIAlPI.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```
And this is what i expect to see from `ssh()` for interaction later on, but now the process is hanged on.

**Comment by amoffat** [comment]
https://amoffat.github.io/sh/tutorials/interacting_with_processes.html

**Comment by 4l1fe** [comment]
> https://amoffat.github.io/sh/tutorials/interacting_with_processes.html

What i'm doing wrong in general?
Should i interact with a process manually not using `sh.contrib.ssh`?

**Comment by amoffat** [comment]
This is more of a support issue than a bug with the sh software. If you or your company would like to purchase a support package, reach out to me at my email. Otherwise we can leave the issue open for a bit to see if someone else will debug it with you.

**Comment by 4l1fe** [comment]
I didn't that you sell OSS.

**Comment by amoffat** [comment]
The software is free and has been for 12 years
