### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [amoffat/sh#697]
Is it possible next time on release new version make the github release to have entry on https://github.com/amoffat/sh/releases entries? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by amoffat** [comment]
Good idea @kloczek, thank you for bringing it to my attention

**Comment by kloczek** [comment]
Thank you for understanding 👍 😄

**Comment by ecederstrand** [comment]
I created releases from all the 2.X tags now.

@amoffat if you have a checklist for releases, then you might want to add creating GitHub releases to that list. There's also possibility for automation: https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by kloczek** [comment]
Thank you 👍 😄

**Comment by amoffat** [comment]
Thanks @ecederstrand for doing that leg work.

Going to automate it for sure. I have done this [somewhat recently](https://github.com/amoffat/HeimdaLLM/blob/dev/.github/workflows/main.yml#L186-L195) so it should be a matter of copy pasting. I'll make a separate issue for this.

**Comment by kloczek** [comment]
This may be useful https://pgjones.dev/blog/trusted-plublishing-2023/
