### ISSUE TITLE
cannot import name 'pg_dump' from 'sh'

### ISSUE THREAD

**Issue by boukhasmarsoufian** [amoffat/sh#706]
cannot import name 'pg_dump' from 'sh' 
![image](https://github.com/amoffat/sh/assets/29687010/1f7f4f2a-7c5a-4735-9cd0-488e7a55296e)

**Comment by boukhasmarsoufian** [comment]
python version : 3.11.4
sh version : 2.0.6

**Comment by ecederstrand** [comment]
This usually means that `pg_dump` is not in your PATH. Does `which pg_dump` tell you where the binary is located?
