### ISSUE TITLE
Special kwarg _cwd and sh.pushd() not working

### ISSUE THREAD

**Issue by mnwdbase** [amoffat/sh#710]
i try:
```python
with sh.pushd("/remote/dir"):
    my_server = sh.ssh.bake("root@1.2.3.4")
    my_server.npm("run")
```
ERROR: cannot find package.json in /root
how can fix?

**Comment by amoffat** [comment]
`sh.pushd` only changes the current working directory of your local commands. it doesn't influence `sh.ssh`'s  remote cwd. advanced ssh usage is outside of the scope of provided support of this library.

**Comment by amoffat** [comment]
Do it on the command line first and you will see it doesn't work like you expect. Once you get it working on the commandline, then convert it to `sh`

**Comment by amoffat** [comment]
You first need to learn how ssh runs command line arguments on a remote server, then it will become clear to you https://linux.die.net/man/1/ssh

In any case, this is not an sh issue.
