### ISSUE TITLE
baking piped commands

### ISSUE THREAD

**Issue by git-os** [amoffat/sh#712]
```python
import sh
sh.awk.bake("{print $5}", _in=sh.df("-h", "/"))
sh.awk.bake("{print $5}", _in=sh.df.bake("-h", "/"))
```
None of these seem to work, instead df is executed right away, is this intended behvaiour because baking piped commands is not supported?

**Comment by amoffat** [comment]
Piping baked commands it not supported, correct. Your best option is to write a small function to wrap what you want to do and call that function when you need the results.

**Comment by git-os** [comment]
Understood, interestingly this one works (even in combination with a baked `sh.ssh`)
```python
sh.head("-n5", _in=sh.cat("/proc/meminfo")
```
