### ISSUE TITLE
Add GitHub release for 2.0.7

### ISSUE THREAD

**Issue by jakirkham** [amoffat/sh#727]
Currently there is a GitHub tag for [`2.0.7`]( https://github.com/amoffat/sh/releases/tag/2.0.7 ). Could someone please add a GitHub release as well?

**Comment by ecederstrand** [comment]
Done. Thanks for the heads-up!

**Comment by amoffat** [comment]
There's an open issue here to automate releases so I don't forget :man_facepalming: https://github.com/amoffat/sh/issues/698

**Comment by jakirkham** [comment]
Thank you both! 🙏
