### ISSUE TITLE
Proposal: sh("<cmd> ...") as alias for sh.bash("-c", "<cmd> ...")

### ISSUE THREAD

**Issue by axsaucedo** [amoffat/sh#735]
Using sh extensively I often find myself having to use the `sh.bash("-c", "<cmd> ...")`. Although the `sh.<cmd>` interface is great initially for convenience, I often find myself adding the full command directly, whether for easier consistency when testing or due to limitations such as commands that contain a special character (`-`, `.`, etc). Indeed it's possible to `bash = sh.bash.bake("-c")` which is what I tend to do instead, but it would be quite convenient if this was supported by default as a contrib command that is accessible directly from the callable interface, and could potentially be a relatively simple interface (e.g. a `__call__` implementation). Thanks for the great project!

**Comment by amoffat** [comment]
Is the request something like this?
```python
from sh.contrib import bash
bash.ls() # runs bash -c ls
```

**Comment by axsaucedo** [comment]
Thank you for your prompt reply! Yes exactly, the only extra I would add is being able to call directly - e.g:

```python
from sh.contrib import bash
bash("command-with-dash [...]") # runs bash -c <cmd> [...] directly
```

**Comment by amoffat** [comment]
Ok, I would merge it if you (or someone) made a PR. Here's the `git` contrib command to use as a template https://github.com/amoffat/sh/blob/develop/sh.py#L3467-L3471

**Comment by axsaucedo** [comment]
Sounds good @amoffat - added #736 with functionality discussed:

<img width="691" alt="image" src="https://github.com/user-attachments/assets/6b25841c-8d53-43e7-bbab-dc2b3fc9f1f8">

Let me know if further changes requred - thanks!
